### PR TITLE
Creates the (Towner) Doctor (for males)

### PR DESCRIPTION
**Pull request by WindowTalents**
Court Physician, but worse!
Added notes to things that might need changes, since I am not active on the discord.

Feel free to do whatever you want with this rough draft.

## About The Pull Request
I've been wanting to make this for awhile. I am also stupid, so feel free to make it better. Everything here is copied from other roles. Yes, that is the extent of my coding power. The goal is to make a "male seamstress" that is not just, male seamstress.

I have no idea what most of the clothing lines are and got sick of looking for them, so if these won't do, change them to what will.
Do not give this role the Plague Doctor stuff, that should be a unique Pilgrim or stay unique for the Court Physician

## Why It's Good For The Game
There really needs to be more ways for players to interact with the medical stuff. As of right now, some kid the Church took in and a recovered leper are the **only two doctors in the entirety of Rockhill.** Something about that ain't right.

I also genuinely hope this helps the Church feel less like a medbay, and more like a Church. This is just the first step towards that. Obviously this does not come with a place to practice medicine, but we have beggars and beds in the sewers for that.

### CODE REVIEW

**Comment by WindowTalents** [comment]
I would like to add that this probably SHOULD have been a 'draft' as my intention was to have people let me know if this was balanced enough or not. I am the farthest thing from an expert, this is all copy pasted code. I have no idea what I am doing.

I want this to be one of *the* "anti-frag" roles. So I might actually remove the combat track and hit this with some combat nerfs.
The goal is to have high INT, be combat weak without high effort, and be somebody who can casually help out the town with their various injuries from falling out of windows or drinking sewage as cleric. (Why do those creechers do that?)

I also would ***LOVE*** it if the "scissors" that let you change people's hair were added, if that is even possible, you can JUST rename this to Barber. That would be better in EVERY single way. (I just can't, I could barely do this, lol.)

If this is something the community wants, I would personally love to also see more Towner roles in general - as that would ACTUALLY reduce the "adventurer spam" some people really dislike and have been limiting with various systems. I play adventurer to walk around, talk to people, and kill people who fuck with innocent players doing their own thing - THIS IS NOT EVERYONE, and I am aware of this. I don't want "combat towners" because that is what guards are, but the ability to "help" or "fulfill a goal" for the town should be what they are designed to do.

I appreciate the fun of goofin' with you folks. Roles like this should help that be more possible for more players, especially new ones. Let me know what to change if anything, or... just, change it, if you can/want. (I have no idea how this works, have mercy lol.)

**Comment by Real-MAGNUM** [comment]
This is a great addition to towner. Nice stuff.

**Comment by WindowTalents** [comment]
It genuinely makes me happy to read that, wow.

Let me know if you think this is good AS IS - or, if you think it should be changed up at all.

I was VERY LAZY with the outfit, if it needs a different one, please let me know.

**Comment by YosemiteYam** [comment]
"You are an average town doctor. Unfortunately you live in Rockhill."

The flavourtext is a bit wanting, you can use this if you want; 

"Blurring the line between healer and harbinger of death, you are the closest thing to a doctor that the townsfolk here can afford. Wielding crude tools and accumulated knowledge, you try to combat the unending disease and suffering the masses here endure"

This role could also be the one that later forms into the alchemist when alchemy becomes a thing, as an alchemist and town healer at the same time could be abit much, but would work as a fusion.

**Comment by pilotmans** [comment]
I think this would really help flesh out the medical side of things.

**Comment by ophaq** [comment]
Currently broken according to my testing. Tried out middleage/old on dwarf, human and elf about 23 iterations total. Could not get doctor to show up in the towner listing at all. Pestra was the patron for it.

**Comment by WindowTalents** [comment]
> Currently broken according to my testing. Tried out middleage/old and a few young on dwarf, human and elf about 23 iterations total. Could not get doctor to show up in the towner listing at all. Pestra was the patron for it. Was super stoked to play this and the minstrel and drunkard show up, just not this.

That's a huge bummer. I literally have no clue what I did wrong then, especially considering that... like, the maintainers loved my work or something I guess?

I am so sorry about this, damn.

**Comment by WindowTalents** [comment]
Fixed it.
I didn't name it a .dm LOL AAAAAAAA

**Comment by ophaq** [comment]
Do they get diagnose spell by the way? Seems like they should if they don't because how the hell are you supposed to know if they have fractures and such otherwise? Would make it too hard.

**Pull request merged**
