### PR TITLE
Just a Vampire Lord lore change.

### PR DESCRIPTION
**Pull request by Sarkness**
## About The Pull Request

Decided to be a dick, modify some lore lines about the Vampire Lord due to it being Creature of Noc (as seen in books around the game if people play archivist) and steal the 1000th PR

## Why It's Good For The Game

That's literally it, lol

### CODE REVIEW

**Comment by pismorizzo** [comment]
Undead are 100% Zizo's domain. Noc is part of the Divine Pantheon not the Inhumane one meaning that for some reason a child of Psydon created life sucking undead. Probably makes more sense to change the books that say vamps are made by Noc instead.

**Comment by wgtjunior743** [comment]
Might as well change "CHILD OF KAIN" to "CHILD OF MICHAEL", and they are Corrupted Creatures of Noc, corrupted by zizo later in the story, a true creature of Noc would not mindless kill people and get help from the undead (zizo creatures)

**Comment by wgtjunior743** [comment]
> Undead are 100% Zizo's domain. Noc is part of the Divine Pantheon not the Inhumane one meaning that for some reason a child of Psydon created life sucking undead. Probably makes more sense to change the books that say vamps are made by Noc instead.

Read the tale first : [https://github.com/Blackstone-SS13/BLACKSTONE/blob/main/strings/books/tales14.json](url) , this does not is the editor edition, but the editor edition only adds that Noc gave them the power to survive under the moonlight but later zizo stole the moonlight power and started using the vampires as his tools, the Vampires are cursed creatures spawns from a son of Astrata that fell into a plot made by Xylix , becoming an horrible creature that was rejected by Astrata but accepted to Noc because of his love to his twin sister Astrata, but they become corrupted somehow and by unknown reasons by Zizo.

**Comment by pismorizzo** [comment]
> > Undead are 100% Zizo's domain. Noc is part of the Divine Pantheon not the Inhumane one meaning that for some reason a child of Psydon created life sucking undead. Probably makes more sense to change the books that say vamps are made by Noc instead.
> 
> Read the tale first : [https://github.com/Blackstone-SS13/BLACKSTONE/blob/main/strings/books/tales14.json](url) , this does not is the editor edition, but the editor edition only adds that Noc gave them the power to survive under the moonlight but later zizo stole the moonlight power and started using the vampires as his tools, the Vampires are cursed creatures spawns from a son of Astrata that fell into a plot made by Xylix , becoming an horrible creature that was rejected by Astrata but accepted to Noc because of his love to his twin sister Astrata, but they become corrupted somehow and by unknown reasons by Zizo.

These are confession lines, someone saying they are a child of Noc will just sound like they arent an antag at all and just have Noc set as patron.

**Comment by wgtjunior743** [comment]
> > > Undead are 100% Zizo's domain. Noc is part of the Divine Pantheon not the Inhumane one meaning that for some reason a child of Psydon created life sucking undead. Probably makes more sense to change the books that say vamps are made by Noc instead.
> > 
> > 
> > Read the tale first : [https://github.com/Blackstone-SS13/BLACKSTONE/blob/main/strings/books/tales14.json](url) , this does not is the editor edition, but the editor edition only adds that Noc gave them the power to survive under the moonlight but later zizo stole the moonlight power and started using the vampires as his tools, the Vampires are cursed creatures spawns from a son of Astrata that fell into a plot made by Xylix , becoming an horrible creature that was rejected by Astrata but accepted to Noc because of his love to his twin sister Astrata, but they become corrupted somehow and by unknown reasons by Zizo.
> 
> These are confession lines, someone saying they are a child of Noc will just sound like they arent an antag at all and just have Noc set as patron.

Yes i agree, that is why i said it would be better to say "Corrupted Children of Noc" because they are not a children of noc anymore, they have become corrupted by Zizo and now seek to destroy and kill people

**Comment by ChungusGamer666** [comment]
this makes no sense whatsoever, vampires worship zizo

**Pull request closed without merging**
