### PR TITLE
Friendly zombie destruction

### PR DESCRIPTION
**Pull request by ChungusGamer666**
Friendly zombies are really starting to get on my damn nerves.

For every 2 minutes you don't bite a living human, one of your limb falls off - The last limb to fall off is your head, then you fucking DIE.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
Does not apply to zombies without a client.

**Comment by Alexeivichi** [comment]
Terrible way of doing honestly.

**Comment by ChungusGamer666** [comment]
I have a better idea

**Comment by OrbitalParadise** [comment]
Could you make it if a human enters a distance close to the zombie the timer starts, then the timer goes away if they are not close

**Pull request closed without merging**
