### PR TITLE
Restricts separated bogtown to 100 players, map rotation at roundend

### PR DESCRIPTION
**Pull request by PotatoTomahto**
## About The Pull Request
Readds Blackstone map with boggers next to gate as "Blackstone Dense". Map voting is called at the end of each round, and Blackstone with separated bog town requires 100 players minimum to be votable.

## Why It's Good For The Game
The new Blackstone map is designed only for highpop and feels miserable to play with less people.

### CODE REVIEW

**Comment by TheManWithNoHands** [comment]
holup, let me wip you something up

**Comment by wgtjunior743** [comment]
Truly feels like this, the seperation is Nice but with low pop ,everyone feels distant and interactions are harder to come by

**Comment by CVSthePharmacy** [comment]
WAIT OLD BLACKSTONE MAP WITH THE BOG GATE GAURDING THE TRAVEL POINT???????????

**Comment by CVSthePharmacy** [comment]
IF SO THEN WE'RE GOATED

**Pull request merged**
