### PR TITLE
THE ONLY CURE

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Zombie infections can now be CURED...
###...at a cost!
Untitled

Changes:
1. Zomble/verewolf infection is wound based
2. Arteries have higher zomble infection chance, a whole 50% for zombles and 100% for verewolves
3. Amputating a limb with an infected wound means the infection is cured
4. Timer for zombie infection is 3 minutes, timer for verewolf infection is 2 minutes

image
image
image

## Why It's Good For The Game

People have been asking for a way to cure zombie infections and for more lenient timers for a while, this is a NON HUGBOXY WAY to have a cure.

### CODE REVIEW

**Comment by dunsel-hordon** [comment]
So when you cut it off is the limb still infected?

**Comment by ChungusGamer666** [comment]
> So when you cut it off is the limb still infected?

yes, dont reattach it, that will jsut infect you again

**Comment by Xkallubar** [comment]
Does it really matter for zombies when you can't play as them?

**Comment by wow50000** [comment]
does greater limb miracle remove the infection ?

**Comment by WindowTalents** [comment]
This is a cool idea, except I bite necks lol.

**Comment by ChungusGamer666** [comment]
> does greater limb miracle remove the infection ?

no, amputate it

**Comment by ChungusGamer666** [comment]
> This is a cool idea, except I bite necks lol.
> 
> EDIT: Jokes aside, this actually highlights "my" issues with this antag. I want to infect people and turn them into werewolves, I hate how hard it is to do that - when I can just decap people instead with the dumb claws... which I don't want to do, at all lol. If this is an infection based antag, I want to be able to actually infect people, and it is hard to do that. This removes the ability to bite the places that don't kill people as easily, which means I'm just gonna be accidental fragging as the infection antag more.
> 
> THIS IS NOT TO SAY THAT I DO NOT THINK THIS IS A COOL CHANGE LOL. I really like this, I just want to add these thoughts. Stuff like this is actually great.
> 
> Also remove zombie infection, just make them an enemy when people rot, please.

why would i do that zombie infections are cool and make zombles really threatening

**Comment by WindowTalents** [comment]
Cause I can't play as them anymore cause people kept being friendly, lol.

*shrug*

**Comment by Ambrose997** [comment]
Dumb making it incurable to miracles imo, but alright.

**Pull request merged**
