### PR TITLE
Removes Job PQ Checks

### PR DESCRIPTION
**Pull request by SELFHELL**
PQ is an inherently flawed and janky system; I am slapping a band-aid on top of this wound by making it irrelevant for job selection.

### CODE REVIEW

**Comment by zakanater19** [comment]
PLEASE merge

**Comment by ChungusGamer666** [comment]
Not necessary anymore because the typo stuff has been nuked. PQ is now more or less working as intended as we updated the accent. I'll close this.

Reopen later if deemed necessary.

**Comment by Noobetski** [comment]
petition to impeach the @ChungusGamer666 and reopen this PR. Like the commend to sign it

**Comment by thebigtony** [comment]
Impeaching is going too far. But I think this PR should be given more consideration.

**Pull request closed without merging**
