### PR TITLE
Bogmaster "nerf"

### PR DESCRIPTION
**Pull request by MickDick1**
## About The Pull Request

Brings the bogmaster down from a legendary warrior to rival the captain in town to something more reasonable and thematically appropriate for a peasant sergeant. A brutish fighter with a blunt instrument to break anyone stepping out of line.

He was also buffed in a few areas that made sense to me, like having a little more athletics and 1 medicine skill. An experienced warrior ought to know some first aid. Whips/flail set to journeyman since he would be punishing boggards with whippings to keep discipline and naturally be accustomed to a similar blunt weapon like flails.

## Why It's Good For The Game

Bog master should never have been a legendary status warrior. He's an idiot in charge of a band of idiot peasant militia and are expected to die in contact with major enemies unless they really pull together. He can't solo the entire bandit gang now quite like he used to, but he can still stand his ground like the experienced warrior he is.

### CODE REVIEW

**Comment by GreenHoodiedEthan** [comment]
dwarf bog master is going to be built like an absolute tank.

**Comment by CVSthePharmacy** [comment]
Also the reason they were made legendary is because they're the bog guards' training role, he trains the bog guard. This was done since vet and village elder were removed. Removing this prevents the bog guards from being able to train. You're ruining the game with these nerfs btw.

**Comment by Yellows91** [comment]
Personally looks fine to me if we are turning him from A legendary warrior who has dealt with threats all his lifetime to a "Big Criminal boss enforcer" who keeps his men in check. Though Mace skill should be Master in my opinion.

**Comment by MickDick1** [comment]
Chungus made me give him master mace skill. He's arguably stronger than the guard captain now.

**Comment by dunsel-hordon** [comment]
I mean the whole bog is its own fucking barony now so he should have legendary as the bog master. Is there even a damn Baron role in for the Bog?

**Comment by efzapa** [comment]
> Also the reason they were made legendary is because they're the bog guards' training role, he trains the bog guard. This was done since vet and village elder were removed. Removing this prevents the bog guards from being able to train. You're ruining the game with these nerfs btw.

because not being able to powergame getting master 15 minutes in and fragging people you don't like is "ruining the game"

please do something other than combat and actually enjoy the game (there's a really cool role called merchant, you should try it out)

**Comment by Coastfront** [comment]
> I mean the whole bog is its own fucking barony now so he should have legendary as the bog master. Is there even a damn Baron role in for the Bog?

Fair point as-well.
Now; The bog is even more independent, having it make EVEN LESS sense that the bog-master wouldn't be an outright amazing fighter, given that the bog town is practically its own tiny state.

**Comment by CVSthePharmacy** [comment]
> > Also the reason they were made legendary is because they're the bog guards' training role, he trains the bog guard. This was done since vet and village elder were removed. Removing this prevents the bog guards from being able to train. You're ruining the game with these nerfs btw.
> 
> because not being able to powergame getting master 15 minutes in and fragging people you don't like is "ruining the game"
> 
> please do something other than combat and actually enjoy the game (there's a really cool role called merchant, you should try it out)

Ok so people talk about 15 minutes as if it's nothing, 15 minutes is a lot of time, A LOT of things happen in 15 minutes, and with bog guards having 8-7 intelligence, they take about 30 minutes to get to master

**Comment by efzapa** [comment]
> > > Also the reason they were made legendary is because they're the bog guards' training role, he trains the bog guard. This was done since vet and village elder were removed. Removing this prevents the bog guards from being able to train. You're ruining the game with these nerfs btw.
> > 
> > because not being able to powergame getting master 15 minutes in and fragging people you don't like is "ruining the game"
> > 
> > please do something other than combat and actually enjoy the game (there's a really cool role called merchant, you should try it out)
> 
> Ok so people talk about 15 minutes as if it's nothing, 15 minutes is a lot of time, A LOT of things happen in 15 minutes, and with bog guards having 8-7 intelligence, they take about 30 minutes to get to master

which still leaves 3/4s of the round for fragging people, what is your point here

we already have a dedicated training role and they are called Captain of the **_GUARD_**

Guards have already been powercrept to hell, and they don't need to stay that way

**Comment by Wozzy09** [comment]
> we already have a dedicated training role and they are called Captain of the **_GUARD_**
> 
> Guards have already been powercrept to hell, and they don't need to stay that way

Where logic? having only guard Captain as trainer makes guard even more powercreep, since there no way he train someone not guard. bog masters at least was training random people unlike guard captains

**Pull request merged**
