### PR TITLE
Adds a little fort/building for the bogguard just on the otherside of the bridge

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Let's the bogguard extend their influence into the bog region, gives them some beds and windows to look out of and adds a SCOM near the door so they can call for backup if needed

## Why It's Good For The Game

Nothing crazy in there just beds and closets with needles/cloth like in the bog garrison dorms, will let the bog master send troops to tame the wild areas if needed or asked too by the king, let's RP happen outside the protected bog village, so it's more dangerous

Z5 with areas view

Z5
Z5

Z4
Z4

Z3
Z3

Me testing the stairs ingame because i somehow always fuck them up LOL, also tested bushes/grass is spawning as it should
stairs testing
BUSH

### CODE REVIEW

**Comment by TopHatPenguin** [comment]
i'm personally of the opinion that this is rather unneeded for the bog guard, as if they wanting to tame and secure the other side of the bridge it should be an /active/ effort and not something supplied by the game already.

**Comment by Gyrandola** [comment]
Bog guards already have more facilities than the town guard. I think this is a bit unneeded and the Anarchy zone should be respected for what it is, Anarchy.

**Comment by Hmeister-real** [comment]
make the tower smaller, too wide and blocky

**Comment by dunsel-hordon** [comment]
Bog guard already have their area this is bloat

**Comment by CVSthePharmacy** [comment]
give them crossbows in this building

**Comment by Real-MAGNUM** [comment]
Bloat, players can build this on their own.

**Comment by CVSthePharmacy** [comment]
> Bloat, players can build this on their own.

maaaaaan you're bloat

**Pull request closed without merging**
