### PR TITLE
+BogInn -BogSmith and bogtown+river tweaks AND NEW ZOMBIE SOUNDS

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request
Removes smithing equipment in the bogtown blacksmith. It's now a general store that pilgrims can sell anything out of. More of these types of houses eventually.

Basically rebuilds the bog tavern because it sucked bad. It resembles the town tavern, except it has less starting stuff.

Fixes a lot of annoying path placements, holes in staircases, adds another bridge, and adds places to swim out of the river sooner, as well as new streams that the river splits off into new lakes/caves.

## Why It's Good For The Game

Bog needs polish now that we're playtesting it.

### CODE REVIEW

**Comment by Osmos123** [comment]
I am liking the bogtown a lot now

**Comment by YosemiteYam** [comment]
Can we get palisades/murderholes above the bog gate to shoot southwards from the top z level? And is the grill above the gates supposed to be openable with a lever to throw rocks down or something?

**Comment by YosemiteYam** [comment]
Also the boggates are extremely easy to break into now because of t he walls being replaced by weak-ass metal bars, I thought the idea was that people had to break the gates or figure out ways to scale the boggate with carpentry instead? Please replace the metal bars with walls again

**Comment by kacperpl1234pl** [comment]
bogsmith was so fun give it back

**Comment by Real-MAGNUM** [comment]
Make your own smithy now.

**Pull request merged**
