### PR TITLE
Alchemy (and Bombs)

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About The Pull Request

Adds alchemy, makes it possible to craft Bottle bombs, Manna and health potions, also in bulk. Allows for future implementation of actual potion making using this as a template. Also adds chemistry to a lot of roles, and changes some stats about. Notably for sorceress since they were using shit-stats from zeth era roguetown

## Why It's Good For The Game

Potion making is fun :) Also bomb making is REALLY fun :D

### CODE REVIEW

**Review by DerFlammenwerfer — CHANGES_REQUESTED** [review]
For the x3 recipes, you need to alter the datum paths so that they don't conflict with the singleton recipes. Also, make sure your indentations are all correct, or else it won't compile correctly and there will be errors.

For example, 
`/datum/crafting_recipe/roguetown/alchemy/health_pot_3`
`     name = "3x Health Potion"`

Finally, Mortar and Pestle exist in the game already and are craftable. You can include them as required tools using their object paths, which are `/obj/item/reagent_containers/glass/mortar` and `/obj/item/pestle`

**Comment by CVSthePharmacy** [comment]
how will you level it up

**Comment by dunsel-hordon** [comment]
there already is a mortar and pestle

**Comment by Hmeister-real** [comment]
> how will you level it up

making fire bombs 🧌, just needs 11 int for the 2% chance

**Comment by lovegreenstuff** [comment]
why do you need bowls instead of bottles

**Comment by Hmeister-real** [comment]
> why do you need bowls instead of bottles
i think it's the bottles it just has a weird name. Unless im wrong, then direct me to where the bottles are

**Comment by lovegreenstuff** [comment]
> > why do you need bowls instead of bottles
> 
> i think it's the bottles it just has a weird name. Unless im wrong, then direct me to where the bottles are

/obj/item/reagent_containers/glass/bottle/rogue/
its in roguejobs/alchemist if youre wondering where to find it

**Comment by BlueMemesauce** [comment]
it would be way cooler if you had to use the mortar and pestle and it was a chemical recipe rather than it being a crafting recipe

**Comment by Hmeister-real** [comment]
> it would be way cooler if you had to use the mortar and pestle and it was a chemical recipe rather than it being a crafting recipe

dont know code

**Comment by BlueMemesauce** [comment]
i mean you added crafting recipes and chemical recipes are basically the same thing but with reagents instead of items

**Comment by Hmeister-real** [comment]
> i mean you added crafting recipes and chemical recipes are basically the same thing but with reagents instead of items

i wouldnt know how to make the bbomb work as a reagent, and everything else uses the crafting menu anyway, so it would be weird to make it reagent based. also reagents wouldnt work for bulk 3x potions, since it would dupe reagents meaning infinite manna/health currently

**Comment by ophaq** [comment]
Make it so that it requires a mortar and pestle to craft if it isn't already like how you would need a table to sew a bag.

**Comment by WindowTalents** [comment]
I'm going to give my Towner Doctor level 2 in alchemy to go along with the stuff you have here, I gave him 1, but 2 seems more fitting.

I don't really see the point for 3x recipes when I can right click the craft button and just - remake more lol. But I am not complaining, I just dunno if it is fair to be able to mass produce SORTA the best items in the whole game LOL.

I LOVE preventing certain death with funny red drink, and you can even fit two in a pouch! Just to let you know, I usually loot 2 of those from the Terrorbog every round - and that is MORE than enough for a single player to have haha. Manna pots are situational, but EXTREMELY potent in those situations, since you can completely refill your "blue" meter when you would otherwise be basically done for in fights.

For basic alchemy implementation, this is perfect, absolutely NOTHING will go wrong from being able to craft the bombs!

**Comment by TheManWithNoHands** [comment]
Maybe make the crafting recipys a bit more expensive. Just berrys is a bit little. They are magical drugs after all. MAybe use the actual drugs we have already.

**Comment by Hmeister-real** [comment]
> Maybe make the crafting recipys a bit more expensive. Just berrys is a bit little. They are magical drugs after all. MAybe use the actual drugs we have already.

thats why it's level 4 to craft them, so that Wizzos can sell potions others cannot make, for far cheaper than you can get at the merchants, but less reliably

**Comment by Hmeister-real** [comment]
i dont think merge conflicts are valid, from looking at them. it's literally just adding the alchemy skill to the two roles

**Comment by Hmeister-real** [comment]
I think this should be test mergd @ChungusGamer666 @Real-MAGNUM

**Comment by WindowTalents** [comment]
I am not a crafting expert. How much INT is required to no skill craft these?
Keep this in mind basically.

**Comment by Hmeister-real** [comment]
> I am not a crafting expert. How much INT is required to no skill craft these? Keep this in mind basically.

all of these are at least 3+, so more than 14 if you have no skill i believe to craft any actual potions. The bombs however just 12 to have a 2% chance. You could also hit a training dummy with a mortar and pestle or a bomb to train untill training gets fixed by Chungus...

**Comment by WindowTalents** [comment]
FOURTEEN IS VERY LOW LOL.

Orphans can make those... can it be made to be something SUPER hard to craft?

Health pots should be craftable, only, by the best lol.

**Comment by TheManWithNoHands** [comment]
> thats why it's level 4 to craft them, so that Wizzos can sell potions others cannot make, for far cheaper than you can get at the merchants, but less reliably

As already stated, 4 isnt that high. And potions arent that expensive at the merchant. Costing about 21 mammons.
But the fishes as ingredient is a fun idea. Maybe play with the rare versions of fish for recipys, could make the fisher more involved.

**Comment by Hmeister-real** [comment]
> FOURTEEN IS VERY LOW LOL.
> 
> Orphans can make those... can it be made to be something SUPER hard to craft?
> 
> Health pots should be craftable, only, by the best lol.

sure, il make it 6

**Comment by Hmeister-real** [comment]
I've reverted my two new potions because 
A) i dont know how to code and they were almost entirely made with other peoples help
B) They do not function correctly (dont remove stats after use, and dont decrease stats)
C) someone more experienced can do a better job 100%

**Comment by Hmeister-real** [comment]
this is good for review, not gonna touch it again unless there are balance concerns

**Comment by Hmeister-real** [comment]
@ChungusGamer666 @ me on disc if you're gonna review

**Comment by ChungusGamer666** [comment]
resolve conflicts and i merge

**Comment by Hmeister-real** [comment]
will fix later. FIguring out how to fix merg conflicts with VSC

**Comment by Hmeister-real** [comment]
Im just gonna remake this PR, wont take long. Later today GMT time

**Comment by Hmeister-real** [comment]
#1308

**Pull request closed without merging**
