### PR TITLE
Worms 3d

### PR DESCRIPTION
**Pull request by ChungusGamer666**
rewrites emote pitch code to be less stupid and idiotic and moronic and makes it use pitch instead of frequency

### CODE REVIEW

**Comment by Xkallubar** [comment]
no way you compared it to worms lmao

**Comment by Hmeister-real** [comment]
FINALLY, I CAN CRY WITHOUT SOUNDING LIKE A CARTOON CHARACTER. CHUNGUS I LOVE YOU

**Comment by rusher210** [comment]
hoomins sound very....... strange....

**Comment by WindowTalents** [comment]
NO! MY IRRITATING ASS DORF HUM SPAM _IS SO OVER!_


(Thanks for fixing this shit finally, lol.)

**Comment by WindowTalents** [comment]
The emote sounds are now extremely distorted, in the completely opposite way.
Everybody needs to hear this before it gets fixed again lol, this sounds fucking hilarious haha.

**Pull request merged**
