### PR TITLE
let me axe you a question: why does wielding an axe do nothing?

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
because no force_wielded defined, thats why
they also had no minimum  STR required either, despite being big primitive weapons

all axes other than battle axe
STR REQ: 0 -> 8
you need at least 4 STR to use it 2 handed and 8 STR to use it single handed (most combat classes wont notice this change)
damage decreased across the board, but damage increased when wielded
10 pen on cut and 20 pen on chop added (except stone axe)
no additional performance vs metal armor, but allows damage to go through chain coifs and leather armor

iron sword used as the basis for balance
18 damage, 25 wielded damage

iron axe:
damage: 23 -> 20
wielded damage: 23 -> 26

steel axe:
damage: 26 -> 22
wielded damage: 26 -> 28

steel mace used as basis for balance
30 one handed, 40 wielded, 80 pen on smash
battleaxe: 
damage: 33 -> 24
wielded damage: 33 -> 30
has 30 pen when wielded and its chop deals 36 damage with 70 pen when wielded
70 pen is the minimum amount of pen needed to get partial damage through the weakest metal armor, 30 pen is just enough to get some damage through gambeson

added:
iron hand axe (admin spawn only)
classic one handed axe with 19 damage and no wield
no strength requirement at all 

## Why It's Good For The Game
possibly an oversight
almost all swords benefitted from using two hands, for instance
also big heavy axes should have stricter STR REQs compared to swords, and should deal more damage than swords to compensate for really low defensive stats

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
you're nerfing an already ass battle axe, actually all axes in general, can you not? they're underused already for being the WORST category of weapons. In my honest opinion, just keep the damage as it already was, or close this PR, you're using the fucking IRON SWORD as a basis.

**Comment by FlickTee** [comment]
> you're nerfing an already ass battle axe, actually all axes in general, can you not? they're underused already for being the WORST category of weapons. In my honest opinion, just keep the damage as it already was, or close this PR, you're using the fucking IRON SWORD as a basis.

the hell are you on about, already ass? single hand battle axe does more damage than a wielded greatsword

**Comment by CVSthePharmacy** [comment]
> > you're nerfing an already ass battle axe, actually all axes in general, can you not? they're underused already for being the WORST category of weapons. In my honest opinion, just keep the damage as it already was, or close this PR, you're using the fucking IRON SWORD as a basis.
> 
> the hell are you on about, already ass? single hand battle axe does more damage than a wielded greatsword

it's already put away from the massive str requirement and there are weapons much better than this, and stop trying to make everything do some low ass damage, this is hugbox shit and I heavily encourage you to close this pr. Hugboxes suck

**Comment by Ambrose997** [comment]
> > > you're nerfing an already ass battle axe, actually all axes in general, can you not? they're underused already for being the WORST category of weapons. In my honest opinion, just keep the damage as it already was, or close this PR, you're using the fucking IRON SWORD as a basis.
> > 
> > 
> > the hell are you on about, already ass? single hand battle axe does more damage than a wielded greatsword
> 
> it's already put away from the massive str requirement and there are weapons much better than this, and stop trying to make everything do some low ass damage, this is hugbox shit and I heavily encourage you to close this pr. Hugboxes suck

Cope

**Comment by cornercube** [comment]
> you're nerfing an already ass battle axe, actually all axes in general, can you not? they're underused already for being the WORST category of weapons. In my honest opinion, just keep the damage as it already was, or close this PR, you're using the fucking IRON SWORD as a basis.

mostly, it seems like an actual oversight that axes have no wield bonus and no STR req
the axe will remain stronger than the sword even when in one hand even with a malus to damage, but the wielded damage will be much higher than even the previous one handed damage

what would you suggest would be fair values for wield and unwielded?

**Comment by cornercube** [comment]
> * Give Axes in general more AP. Axes are kinda the AP weapon conceptually. Large heavy blade that focuses all its energy on a small point. There is a reason you use an axe to chop the large fortified plant instead of a mace or sword.
>   Give maces some competion in terms of anti armor weapon.
> * Add higher AP if you wield it, and highest if on chop. And let the battle axe have a chance against steel armor if you manage to hit a chop attack with it. (so maybe dont nerf its dmg)
> * Give it a higher Parry chance if you wield it in two hands. Axe is a large wooden stick for the most part. So make sense that you can parry somewhat decently hits with it if you hold it in both hands.

I could balance the battle axe against the steel mace, which is 30 damage and 40 wielded damage with 80 pen
but at 80 pen, the battleaxe will start to become an energon axe and just slice through armor like butter, theres a very narrow range of values where your weapon doesnt ignore armor but isnt stopped completely by it
baseline armor pen of 40 on all axes would allow you to decap people through chain coifs, but not the gorget, so that could be a good number to aim for, though 80 pen on the battleaxe being able to behead someone through their gorget might be frustrating to some

**Comment by TheManWithNoHands** [comment]
> I could balance the battle axe against the steel mace, which is 30 damage and 40 wielded damage with 80 pen but at 80 pen, the battleaxe will start to become an energon axe and just slice through armor like butter, theres a very narrow range of values where your weapon doesnt ignore armor but isnt stopped completely by it baseline armor pen of 40 on all axes would allow you to decap people through chain coifs, but not the gorget, so that could be a good number to aim for, though 80 pen on the battleaxe being able to behead someone through their gorget might be frustrating to some

Fair, sounds like a solid plan. But maybe don't give the stone axe the ability to decap someone through a coif. Or only iron ones (i actually don't know if iron and steel maille have a difference besides looks.). The cost of obtaining a weapon should be reflected in its strength after all. Effort = reward, and all that.

But sucks to hear there is so little wiggle room.

**Comment by CVSthePharmacy** [comment]
then do 36 damage and 70 pen, if it takes 12 strength to use one handed then it SHOULD be a good weapon

**Comment by YosemiteYam** [comment]
CVS shitting his pants and screaming when  an OP piece of code he abuses gets balanced moment

You don't need to make an axe that already does more damaged than two handed swords stronger don't worry, strength requirement of 12 is there to add more damage and balance out the skill requirement versus other weapons, since you need proficiency to properly use a sword but a buff class with minimal axe training can still utilize a str 12 axe since a single hit will do enough damage

**Comment by CVSthePharmacy** [comment]
> CVS shitting his pants and screaming when an OP piece of code he abuses gets balanced moment
> 
> You don't need to make an axe that already does more damage than two handed swords stronger don't worry, strength requirement of 12 is there to add more damage and balance out the skill requirement versus other weapons, since you need proficiency to properly use a sword but a buff class with minimal axe training can still utilize a str 12 axe since a single hit will do enough damage

If I talk about literally anything then I must clearly abuse it right

**Pull request merged**
