### PR TITLE
Misogyny lore v2

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Females are barred from the following roles which they previously could play for some reason:
-Sheriff
-Bailiff
-Gatemaster
-Castle guard
-Town guard
-Veteran

Does several code improvements such as using gender string defines on allowed_sexes.

## Why It's Good For The Game

This server is dark fantasy and racism and misogyny are both integral to the setting Zeth tried to build. 
Straying from either of these means straying from the soul of the server, which is something I am not comfortable with by any means. I have no idea how these roles ended up being able to be played by both genders, as it sincerely does not align with the previous vision, or my own one, for the setting.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
approved by magnum after these changes were done
image

**Comment by Wozzy09** [comment]
#681 you should have idea why they allowed, idk whose job to merge pr's

**Comment by ChungusGamer666** [comment]
> #681 you should have idea why they allowed, idk whose job to merge pr's

Not what that PR does, check files changed

**Comment by Real-MAGNUM** [comment]
> #681 you should have idea why they allowed, idk whose job to merge pr's

That PR changes(removes) the hidden priority system that would pick males over females if both were rolling for a limited slot. Said mechanic obviously doesnt exist anymore cause it was dumb and got removed in that pr.

**Comment by Real-MAGNUM** [comment]
testmerging

**Review by NGGJamie — CHANGES_REQUESTED** [review]
Emoney wants to add town guards to the misogyny list, while we already have this PR open to address it.

**Comment by EnzoSeptum** [comment]
Female town guards shouldn't be a thing, I cringe so hard.

**Comment by CVSthePharmacy** [comment]
> This server is dark fantasy and racism and misogyny are both integral to the setting Zeth tried to build. Straying from either of these means straying from the soul of the server, which is something I am not comfortable with by any means. I have no idea how these roles ended up being able to be played by both genders, as it sincerely does not align with the previous vision, or my own one, for the setting.

"straying from the soul of the server" that's so fucking ironic considering the last pr you made cutting adventurer slots in half

**Comment by Real-MAGNUM** [comment]
> Emoney wants to add town guards to the misogyny list, while we already have this PR open to address it.

Fine with removing castle guard, leave town guard. I'll talk to emoney and abraxis and come to a conclusion off of github.

**Comment by BlueMemesauce** [comment]
> > This server is dark fantasy and racism and misogyny are both integral to the setting Zeth tried to build. Straying from either of these means straying from the soul of the server, which is something I am not comfortable with by any means. I have no idea how these roles ended up being able to be played by both genders, as it sincerely does not align with the previous vision, or my own one, for the setting.
> 
> "straying from the soul of the server" that's so fucking ironic considering the last pr you made cutting adventurer slots in half

sir adventurers started with 6 slots

**Comment by ChungusGamer666** [comment]
Merging with host approval, further changes can be done in a misogyny v3 pr

**Comment by ophaq** [comment]
I don't mind this but I think they should be at the very least, guards.

**Pull request merged**
