### PR TITLE
Listenstone/Hearingstone

### PR DESCRIPTION
**Pull request by Viviridia**
Listenstone (name pending) essentially a SCOMstone without a mic
## About The Pull Request

-adds the listenstone in the scomm file (frankensteined it don't know how to code)

https://github.com/Blackstone-SS13/BLACKSTONE/assets/169249975/d4699aae-691d-4e69-8935-17a7f2d1076a

-adds the listenstone in merchant luxury shop
Screenshot 2024-05-24 160406

-adds listenstone icon (active and mute(RED)) in neck and on mob icon
Screenshot 2024-05-24 161205
Screenshot 2024-05-24 143237
Screenshot 2024-05-24 160334

## Why It's Good For The Game

more things to buy from the merchant, allows less use of announcements for orders, allows the isolated people to be informed of some news

### CODE REVIEW

**Comment by YosemiteYam** [comment]
The amount of pr's adding emerald radio rings and now portable scom is making me uneasy. This is turning communication into a much easier and prevalent thing in a medieval fantasy setting, the scom is meant to be clunky and situational. If anything instead of a choker this should be more of a heavy item/scom radio that you need to plop down somewhere to listen in, maybe at your home. And should be expensive af, even if you keep it as a choker

**Comment by Viviridia** [comment]
I kinda wanted it to be still a chokersince its a scom that's choked out the voice tool, but regarding pricing what would be better? maybe 250+?

**Comment by YosemiteYam** [comment]
Yeah 250 would be much better, making money has been easy af anyway with the updates to submission holes

**Comment by Real-MAGNUM** [comment]
This def needs to be expensive, yeah. 250 doesnt sound so bad.

**Comment by JTGSZ** [comment]
Eh, I be fr. I don't like the addition of anything related to radios.

**Comment by ChungusGamer666** [comment]
looks ok

**Pull request merged**
