### PR TITLE
Hasta la Vista

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

* Removes spanish from Tieflings
* Adds hissing tongue to keep them distinct (lizardman serpent tongue whatever)

## Why It's Good For The Game

Fits with the description of them as hellspawn better.

Tested locally, worked.

### CODE REVIEW

**Comment by JTGSZ** [comment]
Yeah, ur going to talk to the chungus about this one.

**Comment by TheManWithNoHands** [comment]
They arent hellspawn/Infernalspawn my guy. Thats just a racial slur people (espacially dwarfs) use and it was an excuse to go full genocide on them.

**Comment by NPC1314** [comment]
> They arent hellspawn/Infernalspawn my guy. Thats just a racial slur people (espacially dwarfs) use and it was an excuse to go full genocide on them.

They look like satan. The (poorly spelled) lore blurb you get when you select them starts with the hellspawn slur and further mentions succubus etc. They get Hellspeak from spawn. But this means they are in fact, not related at all to demonic tropes. Ok.

I don't care at the end of the day, l´spanish for them is el dumb and je´awful honhon.

**Comment by TheManWithNoHands** [comment]
> The (poorly spelled) lore blurb you get when you select them starts with the hellspawn slur and further mentions succubus etc.

Yeah, it mentions succubus and incubus as being something people assume they come from, wich is the mentioned genocide reason. 

> l´spanish for them is el dumb and je´awful honhon.

And? The german accent is also increibly racist. But i wouldnt want it any other way. Having poor accents is hilarious.

**Comment by ChungusGamer666** [comment]
No.

**Pull request closed without merging**
