### PR TITLE
Ghosts move up and down

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

it lets ghosts move up and down

## Why It's Good For The Game

they're ghosts they don't have to abide by the rules of physics

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
is this tested and ready for testmerge?

**Comment by BlueMemesauce** [comment]
Yes I tested it

**Comment by Real-MAGNUM** [comment]
testmerged

**Comment by Real-MAGNUM** [comment]
This is broken. Cant ghost up, only down.

**Comment by Real-MAGNUM** [comment]
untestmerged till fixed.

**Comment by BlueMemesauce** [comment]
Worked on my machine, cn you explain in more detail? Button is missing or just not do anything when you press it

**Comment by Real-MAGNUM** [comment]
> Worked on my machine, cn you explain in more detail? Button is missing or just not do anything when you press it

just updated my comment. It's for admins I think, and the button is missing alltogether.

**Comment by BlueMemesauce** [comment]
Ah I see it's probably because you're an admin

**Comment by Real-MAGNUM** [comment]
Lemme know when aghosting is fixed.

**Comment by BlueMemesauce** [comment]
oh that's the opposite fix, I guess admin ghosts aren't technically ghosts or something

**Comment by BlueMemesauce** [comment]
alright it works but why the fuck is aghost atmospheric lmap
image

**Comment by Real-MAGNUM** [comment]
retestmerging

**Comment by Real-MAGNUM** [comment]
seems to work fine now.

**Pull request merged**
