### PR TITLE
Pickpocket conening

### PR DESCRIPTION
**Pull request by maaacha**
Makes it so you can only pickpocket someone if you're in a 180 degree area behind them.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
don't like this at all. A big strat with pickpocketing is letting someone walk past you and pick pocket them as they walk by, maybe you could give this to people without journeyman + pickpocket skill. but thats poitnless. -1 from me, unless you give better reasoning

**Comment by Hmeister-real** [comment]
> > don't like this at all. A big strat with pickpocketing is letting someone walk past you and pick pocket them as they walk by, maybe you could give this to people without journeyman + pickpocket skill. but thats poitnless. -1 from me, unless you give better reasoning
> 
> you can combat pickpocket people of their neck armor instantly

so? skill issue, break peoples hands before they can pull out their weapons. This is just a cope PR then

**Comment by Hmeister-real** [comment]
> > > > don't like this at all. A big strat with pickpocketing is letting someone walk past you and pick pocket them as they walk by, maybe you could give this to people without journeyman + pickpocket skill. but thats poitnless. -1 from me, unless you give better reasoning
> > > 
> > > 
> > > you can combat pickpocket people of their neck armor instantly
> > 
> > 
> > so? skill issue, break peoples hands before they can pull out their weapons. This is just a cope PR then
> 
> seethe over your cheese strat getting nuked

cheese strat? just dodge and parry. keep coping

**Comment by monad76** [comment]
> > don't like this at all. A big strat with pickpocketing is letting someone walk past you and pick pocket them as they walk by, maybe you could give this to people without journeyman + pickpocket skill. but thats poitnless. -1 from me, unless you give better reasoning
> 
> you can combat pickpocket people of their neck armor instantly

This is retarded and really should be changed but there has to be a way to make an exception for armor specifically rather than just changing how all pickpocketing works

**Comment by ChungusGamer666** [comment]
might as well remove pickpocketing, not a fan at all

however pickpocketing should only be used if you are BEHIND the target. say the target faces north- pickpocket should only work if you are to their southwest, south or southeast.

**Comment by ChungusGamer666** [comment]
keeping it open if you want to work on my own version of this

**Comment by WindowTalents** [comment]
Hey, can we just... exclude neck armor from being pickpocketable?

I genuinely think that alone is the one thing that makes steal a "bad mechanic" and its otherwise pretty fun to have to always glance over at my gear to make sure that guy who ran by me did not just steal my shit.

I THINK NECK ARMOR STEAL IS SO BAD, I PLAY ROGUE AND I *REFUSE TO DO IT.*

I would rather lose 'fairly' by not doing that, then win by doing it - that shit is terribly stupid and needs to go.

PLEASE DO NOT RUIN STEAL

**Comment by Coastfront** [comment]
Uprooting every flower in the hunt for weeds is a fools way to keep a garden clean; Steal has an actual place in both roleplay & conflict generation, and this will just effectively kill it.



In my opinion, a better change is either to make it so that

A.: 
Those in combat mode are immune to steal, or incur a windup on steal attempts against them.
B.
Armor is immune to steal attempts.

Either change, as others have stated, are more reasonable than simply soft-removing steal from standard gameplay.

**Comment by WindowTalents** [comment]
Ok, we *need* to remove armor stealing. (YOU CAN STEAL AS A ZOMBIE TO REMOVE THEIR NECK ARMOR DOODS)
I was able to steal my own gorget off myself as a totally paralyzed zombie in order to be able to eat the head that I was on top of (in the river) and fully heal myself.

This let me get more kills lol.

I had NO ABILITY to interact in any other way, except steal - and it just dropped the bervor on the floor so I could then use bite on the head I was on.

This gotta stop yo - steal is great, not this shit, somebody needs to throw a flag on neck armor to prevent it from being stolen PERIOD.

**Comment by YosemiteYam** [comment]
Just make it so that combat mode prevents pickpocketing to prevent funny armor theft in the middle of a fight, and maybe adjust normal pickpocketing so it doesn't work when someone is facing you.

**Comment by WindowTalents** [comment]
I play rogue, I literally *choose* not to pickpocket neck armor and gimp myself BECAUSE it is stupid as fuck - and completely broken.

Pretty much, Rogue 99% dodge *was not* that overpowered in the sense that *you can throw shit and they cannot dodge it* but I do agree that the nerf to max 90% is a MUCH BETTER decision than allowing 99% to begin with.

IN COMPARISON, the ability to remove a person's fucking neck armor under their full plate mail while running past them IS BULLSHIT EVEN OUT OF COMBAT - literally, make the neck armor IMPOSSIBLE TO STEAL.

STEAL SHOULD BE FOR SWIPING BAGS AND POUCHES AND WEAPONS IN SHEATHES.
I can't fucking steal HATS off people, bervor/gorget/coif/chainmail theft off neck is stupid, AND bad.

**Comment by WindowTalents** [comment]
> however pickpocketing should only be used if you are BEHIND the target. say the target faces north- pickpocket should only work if you are to their southwest, south or southeast.

I would be okay with this, but it is actually quite fun to be talking to players in an RP situation and be able to take - pull their shit off them to make a joke outta it lol.

I love using steal to immediately throw items back at people who "trust me" in RP, usually to make a "in roleplay watch out for pickpockets you unobservant goof" type joke but I wouldn't cry over losing this and behind player steal might be more robust/fun to deal with lol.

I am VERY much leaning towards "flag neck armor no steal" if steal is causing this much of an issue in the combat.
(And, yes, it should not be do-able AT ALL in combat mode. That is dumb.)

**Comment by Coastfront** [comment]
Disturbingly as-well: Even with this, it'd still theoretically be possible to steal-neck armor off via grabfu'ing people into motionlessness for several seconds, unless if resisting interrupting pickpocketing.

**Comment by Hmeister-real** [comment]
i dont think removing steal in combat mode is the way to go. i steal from people who are in combat as a third party all the time and its a great way of doing it. just make it directional like parrys if you do go with it

**Comment by WindowTalents** [comment]
> i dont think removing steal in combat mode is the way to go. i steal from people who are in combat as a third party all the time and its a great way of doing it. just make it directional like parrys if you do go with it

yeah no, i never considered this, and now want it removed from combat mode whether or not you are in it
NO COMBAT MODE STEALING ITS SHIT.
STEAL SHOULD BE **SNEAK ONLY** IF WE WANNA BE REAL

**Comment by Hmeister-real** [comment]
> STEAL SHOULD BE **SNEAK ONLY** IF WE WANNA BE REAL

Bro is not a thief irl. The way you want to steal is by being as inconspicuous as possible, irl and ingame. A rogue sneaking and going up to you is a million times more obvious than a Rogue quickly walking past you, quit coping about thieves and just get good. At most just stop stealing if the persons infront of you and your facing them

**Comment by WindowTalents** [comment]
> > STEAL SHOULD BE **SNEAK ONLY** IF WE WANNA BE REAL
> 
> Bro is not a thief irl. The way you want to steal is by being as inconspicuous as possible, irl and ingame. A rogue sneaking and going up to you is a million times more obvious than a Rogue quickly walking past you, quit coping about thieves and just get good. At most just stop stealing if the persons infront of you and you're facing them

This is literally a DND based thing, and if you wanna get technical on me - steal should be a fucking action, like an attack, which takes actual fucking time.

BUT FOR THE SAKE OF CODE SIMPLICITY
AND GAME EXPERIENCE OVERALL

Let's *just* block armor theft, that is fucking stupid.

Why is this even remotely a discussion - you can't fucking take a CHAIN COIF off a man IN AN INSTANT!
Dumbest, COPEST, shit ever - remove ALL THIS CODE and INSTEAD flag the fucking neck armor AS STEAL PROOF.

FUCK.
Yall tripping lol.

**Comment by Coastfront** [comment]
> > STEAL SHOULD BE **SNEAK ONLY** IF WE WANNA BE REAL
> 
> Bro is not a thief irl. The way you want to steal is by being as inconspicuous as possible, irl and ingame. A rogue sneaking and going up to you is a million times more obvious than a Rogue quickly walking past you, quit coping about thieves and just get good. At most just stop stealing if the persons infront of you and you're facing them

"Being as sneaky as possible"
>2 people currently locked in an intense fight to the death, & both fighters are on high-alert
>>one of them somehow doesn't notice someone LIFT HIS SATCHEL STRAP over his head & carry it away.
Objectively, fucking stealing on blackstone is quite divorced from any normal logic, given that most things that are stealable are already the utter least subtle fucking things, let alone robbing someone in combat/"High alert I'm in a fight" mode where they'd be paying a massive amount of attention to themself & their surroundings.

**Comment by dunsel-hordon** [comment]
Should be a .5 second delay at least on steal and needing to be behind someone while on sneak you are literally stealing their shit

**Comment by BlueMemesauce** [comment]
do you even know how pickpocketing works it works by being fast not sitting still next to someone for 2 seconds that would be extremely obvious and would never work

**Comment by WindowTalents** [comment]
> do you even know how pickpocketing works it works by being fast not sitting still next to someone for 2 seconds that would be extremely obvious and would never work

This. Lol.

**Pull request merged**
