### PR TITLE
Idea for Pestra acolyte look very snake themed

### PR DESCRIPTION
**Pull request by Viviridia**
## About The Pull Request
- adds snakerobe
Screenshot 2024-06-03 014052
Screenshot 2024-06-02 164538
Screenshot 2024-06-03 014843
Screenshot 2024-06-03 014753
Screenshot 2024-06-03 014735

- adds snakehood
hooded:
Screenshot 2024-06-03 014128
Screenshot 2024-06-03 012725
Screenshot 2024-06-03 012706

unhooded:
Screenshot 2024-06-03 014111
yes..it is recolored headdress, it just fits y'know

- adds pestra amulet
Screenshot 2024-06-03 014222

## Why It's Good For The Game
makes it so pestra acolytes don't look like necra acolytes

might aswell share this before the gods rework

### CODE REVIEW

**Comment by SpaceSlug2** [comment]
ugly, and head-dress is just recolored egyptian one.

**Comment by Takyon69** [comment]
Sprites are technically sound but aesthetically ugly. I don't think they fit into the theme of rockhill at the moment. Also consider that religion will be reworked in a major way soon enough.

**Comment by TheManWithNoHands** [comment]
Amulete is amazing. But i agree, the robes and headress are not that good. I think they need something more uniqe to work.

**Comment by Viviridia** [comment]
Yeah kinda did make them too faded and yellow

**Comment by Viviridia** [comment]
Aight closing cuz i got the feedback i wanted 🫡🫡

**Pull request closed without merging**
