### PR TITLE
TOTAL OP CLASS DEATH

### PR DESCRIPTION
**Pull request by bobjension**
necros get one slot, elf ranga two slots

5% chance to pick them

### CODE REVIEW

**Comment by Ambrose997** [comment]
necro seems excessive. It isn't as OP since skeleton nerfs.

**Comment by bobjension** [comment]
guy who made these roles told me to make necro 1

**Comment by Real-MAGNUM** [comment]
Pretty excessive.

Limit necro to 5 max, 30% chance. 
Leave sentinel unchanged.

**Comment by bobjension** [comment]
there shouldn't be necros or elf rangers every round. And if there is it should ONLY be one or two.

**Comment by bobjension** [comment]
yeah no, looked over the stats again, I either nerf em or I make them extremely hard to get and I prefer the latter.

**Comment by Ambrose997** [comment]
> yeah no, looked over the stats again, I either nerf em or I make them extremely hard to get and I prefer the latter.

Necromancer have nothing but debuffs except the 3 INT. Are you high? They'd also need someone with high combat skills to cooperate in training. 

Lmfao.

**Comment by Ambrose997** [comment]
> guy who made these roles told me to make necro 1

Guy who made these classes in the first place is shit at balance.

**Comment by ChungusGamer666** [comment]
Necro is on the chopping block, this Pr is apprpved

**Comment by YosemiteYam** [comment]
Good pr, the pr that added necros/elf sentinels/assassins was done with very little thought put into balance and had to be reworked, it's good to limit them

**Comment by SELFHELL** [comment]
As the guy who did necro, I realize in hindsight its uh.. retarded.

**Comment by corgi1fanclub** [comment]
You should probably just nerf Elf Sentinel instead of just making it a flat 5 percent chance and decreasing the slots

that is rarely gonna hit at all, and they start only with skilled. And thats even if they survive the Boggos

**Comment by Gysilian** [comment]
First time commenting here because it affects my way of playing on Blackstone, been playing for a few weeks now also and almost exclusively sentinel. I totally dig the elven ranger vibes of sentinels and their snowflakey flavorful weapons.
The current 50% chance not to be able to roll for the slot even if it's not taken already sucks, I couldn't imagine it lowered to 5% only with only two slots. That would basically guarantee that there wouldn't be any sentinel on most rounds, nevermind sentinels actually interacting with people in the town, or between each other.
I don't understand why there shouldn't be elven sentinels every round, seems like a personel preference of yours. There's a Lord of Heartfelt almost always so, why not sentinels. If their skills are the issue, nerf their master archery or expert healing, or poison arrows, but don't remove a role people enjoy just because.

**Comment by corgi1fanclub** [comment]
and if im being real, nothing is gonna stop people from rolling Elf Ranger too once Sentinel is gone lol im very curious to see whats making Sentinel OP in your eyes when I see people complain about rogue much more often

**Comment by Xkallubar** [comment]
No. Just no. There can't be a necromancer cult with only ONE necromancer.

**Comment by EnzoSeptum** [comment]
It is already hard to get any of these rolls even with high PQ. Necromancer isn't even that op, I don't see anyone complaining, this kind of changes are ruining the game. I remember one of you guys triying to add a 40 adventurer cap, I wanna see what happens when you guys do it, server is gonna slowly die. Stop nerfing everything jesus

**Comment by ChungusGamer666** [comment]
necromancer will be disabled latee

**Comment by skycrafterf** [comment]
Waay too much nerfing as others have said above.

**Comment by CVSthePharmacy** [comment]
> First time commenting here because it affects my way of playing on Blackstone, been playing for a few weeks now also and almost exclusively sentinel. I totally dig the elven ranger vibes of sentinels and their snowflakey flavorful weapons. The current 50% chance not to be able to roll for the slot even if it's not taken already sucks, I couldn't imagine it lowered to 5% only with only two slots. That would basically guarantee that there wouldn't be any sentinel on most rounds, nevermind sentinels actually interacting with people in the town, or with each other. I don't understand why there shouldn't be elven sentinels every round, seems like a personal preference of yours (you got a head crit from a sentinel's poisoned arrow). There's a Lord of Heartfelt almost always so, why not sentinels. Diversity makes for interesting roleplay and this is an MRP server. If their skills are the issue, nerf their master archery or expert healing, or poison arrows, but don't remove a role people enjoy just because. I really don't get what's the issue about sentinels because nothing's explained in this PR.

all ranger roles have master archery lol, it's not op in that aspect at all

**Pull request closed without merging**
