### PR TITLE
Small stuff

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
Changes forest rocks to be mineable, except for the very border.
gives the shitty dragon a faction other than neutral by default
fixes a capitalization error someone else missed in their PR

### CODE REVIEW

**Comment by Autisem** [comment]
does the space dragon actuely spawn?

**Comment by Real-MAGNUM** [comment]
Manual spawn only, but it's been used a few times.

**Comment by CVSthePharmacy** [comment]
> Manual spawn only, but it's been used a few times.

can we not steal rougetown dragon cave

**Comment by Real-MAGNUM** [comment]
Havent heard of it

**Pull request closed without merging**
