### PR TITLE
Expands filter.

### PR DESCRIPTION
**Pull request by Stagrawl**
These are all just pet peeves.

		"wolf": "volf"
		"drow": "dark elf"
		"werewolf": "werevolf"
		"lolth": "graggar"
		"wolfpit": "volfpit"
		"PQ": "reputation"

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
lemme talk about my 76 pq smh smh

**Comment by ChungusGamer666** [comment]
>not verevolf

**Comment by BlueMemesauce** [comment]
drow is a cool name though it should be the opposite

**Comment by BlueMemesauce** [comment]
THERES LITERALLY AN ITEM CALLED DROW DAGER

**Pull request merged**
