### PR TITLE
Removal of very questionable elements from the game

### PR DESCRIPTION
**Pull request by Useroth**
Hey, there's underage character options in your codebase, and to my knowledge you're really firmly against such things.
To be fair they don't have much place in a game like this.

Does anyone really want to kill children or watch them die?
Does anyone really like looking at children while playing their dark medieval fantasy?
Does anyone really really _need_ naked children sprites in the codebase?

+ Disables the "orphan" role (you should likely rework it)
+ Removals of suggestive descriptions of some things as "young"
+ Sanitization of savefiles to make sure nothing breaks
+ Removal of no longer used assets (sprites, sounds)

### CODE REVIEW

**Comment by emoats18** [comment]
Sure why didn't you do this on your codebase at the start little bro

**Comment by Useroth** [comment]
Honestly, it wasn't quite our business, but in this difficult time, I feel like I should reach out a helping hand, since you seem to have some real issues with the topic as of recent, and your headcoder has left.
We removed young ages on our end and plan to rework them into a height system with the teenager sprites removed and new ones being made.

**Comment by Real-MAGNUM** [comment]
This shit is a buggy mess. Reverted from its speedmerge in #1382. Please remake the PR for testmerging/proper review.

**Comment by Tipy1802** [comment]
What's the problem with having teens? We are not an ERP server

**Pull request merged**
