### PR TITLE
Bandit goal/reward overhaul

### PR DESCRIPTION
**Pull request by MickDick1**
## About The Pull Request

This changes the bandit rewards and adds some more item types to feed to the MATTHIOS idol. It adds ingots, psicrosses, and rings to the things you can feed to him and gives a reward for every 100 value you give instead of only every 2. It also adds rewards past 6 and tries to make all the rewards universally useful for the bandit antag. I also added a "hint" to the start text.

## Why It's Good For The Game

The rewards and better loot selection that counts toward the goal will hopefully, finally incentivize bandits to follow their goal. It will also presumably make them a mainstay threat that increases in lethality on an individual level as they reach their goals instead of being the current suicidal dummies they are now. I avoided adding any weapons to the rewards because it is very likely the weapon will not even be useful to their skillset. The "hint" should at least give people who pay attention a clue how the mechanic/idol works.
I recognize the potential for bandits to set up a smelter in their base to convert equipment into sellable loot. I don't see it as an issue. They need coal to build one which will require catching a blacksmith that hasn't used theirs yet. Good on them if they do.

Bandit proof of working

### CODE REVIEW

**Comment by MickDick1** [comment]
BTW I have never done this before so go ahead and yell if I fucked something up.

**Comment by Real-MAGNUM** [comment]
Careful with spamming triumphs too much. They get a triumph on kill I believe, and if this gives them triumphs on loot depos, bandits might be leaving the round with 20+ triumphs, right? Or am I misunderstanding.

**Comment by MickDick1** [comment]
You only get triumphs as a bandit as currently implemented by deposited mammons to the idol. You don't get triumphs on kill to my knowledge. This doesn't change triumphs in anyway. You can get a max of 10 by feeding the idol as normal.

**Comment by YosemiteYam** [comment]
Sure seems like alot of triumphs being rewarded for basically killing people and taking their stuff. This will create problems since triumps will be used with future pr's in determining who gets to choose stronger classes as adventurers/pilgrims. This effectively rewards the best fraggers with better frag roles, basically cycling in the same people who roll bandit into the same "rare" adventurer classes and back again.

**Comment by MickDick1** [comment]
> Sure seems like alot of triumphs being rewarded for basically killing people and taking their stuff. This will create problems since triumphs will be used with future pr's in determining who gets to choose stronger classes as adventurers/pilgrims. This effectively rewards the best fraggers with better frag roles, basically cycling in the same people who roll bandit into the same "rare" adventurer classes and back again.

They're antags. They're supposed to be rewarded for achieving their goal at the expense of the regular town inhabitants. I really cannot comprehend where you're going with this. Regular players already can just play as normal, sleep each night and rack up triumphs even if they're just AFK in a corner of the map and you're worried about bandits getting triumphs for being bandits, an antag that has a 99% casualty rate every round? Do you have a similar issue against maniac, rebels, or vampires receiving triumphs for achieving their goals? The max number of triumphs you can receive is 10 anyways and always has been. 

Just between a crew of 5 bandits, it requires looting 5,000 mammons worth of **coin** for all of them to reach their quota for the round right now. That is an absolutely astronomical number to the point most bandits don't even bother with the shit. It's a waste of time that barely even rewards you during the round. AND people's coin purses got nerfed into the ground since launch. That's all on top of bandits getting nerfed individually so it's harder to fight the adventurer waves that just keep coming.

**Comment by Real-MAGNUM** [comment]
The difference between bandit and other antag roles is their freedom. We dont want to encourage 100% murder with the role that's supposed to be played creatively at least sometimes. Just because you *can* kill everyone every round, doesnt mean it should be the only method that's encouraged. Consider giving them a few chains to start off with, enslaving a smith or something to make them rings is better than killing 20 people to get the rings, both in round quality and in efficiency for the bandits.

**Comment by JTGSZ** [comment]
Better than before honestly.

**Pull request merged**
