### PR TITLE
Additions to the Keep

### PR DESCRIPTION
**Pull request by Deroh-Ra**
Add's a guest room and a Workshop room to the third floor of the keep with some gems, a loom, metals, copper (Which has no in-game craftables yet from what I've heard), and some cogs

The Keep feels empty as hell and this just adds some flavor for the sake of flavor
10d942bc577098350ebac9af11ca8931
f729102fd51d789938e4779e1aff993a
fc92bc222126a99aea330c57f007d2b1

### CODE REVIEW

**Comment by Deroh-Ra** [comment]
@Real-MAGNUM Idk how to ask for reviews so

**Comment by Tipy1802** [comment]
I like this a lot, the king really needs a guest room to house all the wandering nobles that tend to come

**Comment by TheManWithNoHands** [comment]
The pink squares means textures are fucked up. You need to fix that.

**Comment by Deroh-Ra** [comment]
> The pink squares means textures are fucked up. You need to fix that.

That's the random gem item /roguegemrandom

**Comment by TheManWithNoHands** [comment]
Ahh, go it. So just no sprite for the map editor.
But still. Some concerns. 
Mainly its position. The workplaces need to be near decent foot traffic to work properly. Up on the third floor nobody will find it. To be fair, there isnt any other room then on the third floor. But it will sit empty most of the time up there and gather dust.

**Comment by Deroh-Ra** [comment]
added some lights to the hallway and fixed some of my mistakes
7f55334d9711e4be6e18a3794b69bf45

**Comment by McRiP28** [comment]
We have to watch out for too many valuables, the stewards routine will be to rob the keep for the vault which is kinda shitty if it gets meta

**Comment by Real-MAGNUM** [comment]
@Deroh-Ra That looks like a lot of ingots. Shouldnt be more than one or two of each, if even that.


> Ahh, go it. So just no sprite for the map editor.
Yeah.

**Comment by Real-MAGNUM** [comment]
> Idk how to ask for reviews so

Top of the right panel of the page, says reviewers. Click it, select my name. What you did was fine though, it still notifies me.

**Comment by Deroh-Ra** [comment]
49208ee4b66cc8f4fc3a8bb0233fe370
Steel is gone, Wood arrives

**Comment by Deroh-Ra** [comment]
oh, i fucked my own pr..I'll make it again later, better

**Pull request closed without merging**
