### PR TITLE
 Gives admins the TG ghost menu (reopened to fix files changed)

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

Reopened #698 

## Why It's Good For The Game

easier for admins to tell what is going on and orbit people

329414905-9955a65c-4594-4858-9ca8-5371bb2c6a5e

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
testmerging.

**Comment by Real-MAGNUM** [comment]
This has been working fine, ready for merge?

**Comment by BlueMemesauce** [comment]
unless admins want any changes its ready

**Review by NGGJamie — CHANGES_REQUESTED** [review]
Some staff are really bothered that GhostUp and GhostDown are missing. Perhaps add buttons to let observers freely move up/down Z levels?

**Comment by Real-MAGNUM** [comment]
This menu removes the overlay, which isnt that bad if it didnt shift the entire screen to the left by ~3 tiles. Some sort of framing issue when the skull on the left is removed. Is it possible to fix the framing?

**Comment by BlueMemesauce** [comment]
uh you want me to leave that useless big ass button?

**Comment by BlueMemesauce** [comment]
Dont really see the issue though, pretty sure it would be better if admins get more space to read chat

**Pull request merged**
