### PR TITLE
Medical "Rework" Part 1: Unretardifying /datum/wound

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

OOOOHOHOOOOHOHO BOY

Documents the shit out of bodypart wound procs, severely reworks /datum/wound in several ways to make the code gooder

### GAMEPLAY CHANGES
- Court physician and priest get a NEEDLE OF PESTRA, which has infinite uses for healing but cannot repair any item
- Most wounds can now clot, which reduces their bleeding rate over time
- Healing spells and other wound healing sources do not heal all wounds at once, they heal wounds SEQUENTIALLY
- Bandages are more effective overall
- Grabbing HALVES limb bleeding rate, instead of applying a flat -2 modifier - This effectively makes grabs MUCH better for saving someone with a torn artery and other gruesome wounds.
- Added testicular torsion as a smite wound that cannot be healed normally, and effectively works as a bone fracture otherwise
- Added GROIN FRACTURES for when you cause a fracture but are aiming for the groin - GROIN FRACTURES DISABLE YOUR LEGS!
- Neck fractures PARALYSE YOUR ENTIRE BODY, if you somehow survive getting one

## Why It's Good For The Game

Wounds in this game are ABSOLUTELY RETARDED and need to be made less retarded ASAP, otherwise expanding the medical system is A FUCKING IMPOSSIBILITY.

### CODE REVIEW

**Comment by Stagrawl** [comment]
Fuck Brainmed, it's Ballsmed time!

**Comment by pilotmans** [comment]
this is great!

**Comment by TheManWithNoHands** [comment]
> Neck fractures PARALYSE YOUR ENTIRE BODY, if you somehow survive getting one

I can finally rp as the disabled fantasy person of my dreams.

**Comment by pilotmans** [comment]
it would be funny if there was a percentage chance to get your groin fractured if you fell onto a fence

**Comment by Hmeister-real** [comment]
would be cool if there was a spell like, "Thicken Blood", that just clots all targeted bleeding wounds for Pestra acyolytes, so one non-pestra acolyte can prioritise big bruises, while the pestra acolyte can focus on bleeds and cuts or whatever. just ideasguy

**Comment by dunsel-hordon** [comment]
why doesn't this have the test merge tag next to it???? Fix this shit.

**Comment by Sevaaas1** [comment]
Weapons embed in all simple mobs

**Comment by Yellows91** [comment]
> Court physician and priest get a NEEDLE OF PESTRA, which has infinite uses for healing but cannot repair any item

In my round of priest I had to request to admins to give me more. They are limited. They are up to like 10 charges?

**Comment by Yellows91** [comment]
Also you cannot see if a victim is bleeding or not making it impossible to tell who is to be treated first.

**Comment by TheManWithNoHands** [comment]
> In my round of priest I had to request to admins to give me more. They are limited. They are up to like 10 charges?

That sounds like just a metal needle.

**Pull request merged**
