### PR TITLE
Nerfs Necromancer Skelebones Further

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Just makes the lads have less stats

## Why It's Good For The Game

Skeletons are meant to be expendable and easily killed goons; this helps achieve that better

### CODE REVIEW

**Comment by bobjension** [comment]
6 strength, 1 speed and 2 con, truly the nerf of our time

**Comment by Gyrandola** [comment]
i think necros are already in a very vulnerable position rn, since their skeletons spawn completely naked and don't even follow the necromancer.

**Comment by Wintermote** [comment]
>Skeletons are meant to be expendable and easily killed goons
Who said that?

I don't see why they can't be powerful, difficult to kill goons.

**Comment by SELFHELL** [comment]
> > Skeletons are meant to be expendable and easily killed goons
> 
> Who said that? I don't see why they can't be powerful, difficult to kill goons.

me, I made it.

**Comment by SELFHELL** [comment]
Also theres the fact you can stack infinite of them, I love hordes and all; but making them individually weaker is a good thing

**Comment by JTGSZ** [comment]
You have conflicts, and you should probably give them more speed so they don't flop as ai mobs.

**Comment by Osmos123** [comment]
I think if you are nerfing the skeletons could you also lower the cooldown for summoning them in consideration?

**Comment by CVSthePharmacy** [comment]
> > > Skeletons are meant to be expendable and easily killed goons
> > 
> > 
> > Who said that? I don't see why they can't be powerful, difficult to kill goons.
> 
> me, I made it.

so basically if you magically get banned then we wouldn't have to worry about the skelebone lore

**Comment by Real-MAGNUM** [comment]
This makes all skeletons ever shitty, right? Not a fan. I think they're fine as they are. Exceptionally weak at anything other than defending a location, which is a good thing.

We use skeletons for other purposes too, I'd like them to be able to exist outside of necromancer spawns.

Suggesting a close @JTGSZ @ChungusGamer666

**Comment by SELFHELL** [comment]
Yeah fair enough, should have actually spent a little effort on this.

**Pull request closed without merging**
