### PR TITLE
Un-shadow bans female characters from every job in the game

### PR DESCRIPTION
**Pull request by Dezupher**
## About The Pull Request
Removes one line that assigns male characters jobs before assigning female characters in the remaining jobs. Tested locally.

## Why It's Good For The Game
Currently if a male character and a female character ready up for the same job, the male character wins every single roll for the job without fail. If you ever wanted to play as a female character in a highly contested job, your only options are to hope the stars align and no male characters roll for it, or just give up.

This should add more potential variety to the characters you'll come across in game and actually allow female characters a chance into the jobs they are not restricted from.

### CODE REVIEW

**Comment by BigBigga** [comment]
sloppy

**Comment by dunsel-hordon** [comment]
Male supremacy in our medieval rp gtfo

**Comment by OrbitalParadise** [comment]
same vibe as we need more women soldiers in our ww2 games

**Comment by CVSthePharmacy** [comment]
close this pr, slopcode

**Comment by Dezupher** [comment]
If you don't think a female character should be able to take a roll then try to make it so they shouldn't be able to roll for it in the first place.

This effects more than just roles like Court Magician and Hand (to be honest I'm not sure why female characters can be hand, not that I've ever seen one). Smaller roles which have absolutely no reason for male bias like Prince/Princess, butcher, cook, barkeep, etc, are all subject to the male character gets rolled first, then female character gets rolled but oh wait the job was filled before I got a chance, I could not find a job to be. It is literally impossible to play certain characters during high pop with so many people rolling.

Players already do a good job of providing the existing male dominated flavor of the setting in game, I see and experience sexism while playing and that's fine, it makes for more conflict.
I don't believe more role bloat isn't the solution to this issue.

**Comment by Alibouk1** [comment]
Merge it and deal with it IC, scrubs.

**Comment by Real-MAGNUM** [comment]
Merging. Cope.

**Comment by BigBigga** [comment]
slopmerge

**Comment by TheManWithNoHands** [comment]
Y'all are hilarious.

"No, i dont want woman in my 2d specegame, medival editon. Let me give you a ted talk why woman suck."

**Comment by CVSthePharmacy** [comment]
> Y'all are hilarious.
> 
> "No, i dont want woman in my 2d specegame, medival editon. Let me give you a ted talk why woman suck."

Fuck off, you're dumbing it down without taking actual context into account. Either read correctly or shut up

**Comment by Wintermote** [comment]
Male only roles: I'm ok with that
Male characters always getting to preferentially play a role available to both sexes rather than being a fair chance: ehhhhhh

Feels more like something done out of spite than to keep the setting self consistent and interesting.

**Pull request merged**
