### PR TITLE
dodging n shiet

### PR DESCRIPTION
**Pull request by bobjension**
uncomments some dodge shit, look at the commit to see what they do, might be broken

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
bad pr I think

**Comment by CVSthePharmacy** [comment]
wait are you removing the dodging fall while off balance, if so fak u

**Comment by Gyrandola** [comment]
> wait are you removing the dodging fall while off balance, if so fak u

pretty sure he's adding it

**Comment by ChungusGamer666** [comment]
looks retarded

**Pull request closed without merging**
