### PR TITLE
now there is alert for commend and also you can commend midround too

### LINKED ISSUE #607: [BUG] Commend Yes button not existing
Issue reported from  Round ID: 213 (Blackstone (Rougetown on a Dedicated Server))

Reporting client version: 515.1637

I thought i was crazy but the YES button is not clickable and only the NO one.

image

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

alert appears at the end of the round

fixes #607

## Why It's Good For The Game

easier commend

### CODE REVIEW

**Comment by Osmos123** [comment]
image

**Comment by BlueMemesauce** [comment]
genshin-impact-genshin-meme

**Comment by BlueMemesauce** [comment]
tested it this time
image

**Comment by Real-MAGNUM** [comment]
testmerge updated.

**Comment by Real-MAGNUM** [comment]
doesnt compile(?)

**Comment by BlueMemesauce** [comment]
it for real worked when i tested it

**Comment by BlueMemesauce** [comment]
i guess the code thing i changed fucked it

**Comment by JTGSZ** [comment]
Did you intend for people to be able to commend mid-round?

**Comment by BlueMemesauce** [comment]
Yes

**Pull request merged**
