### PR TITLE
Mercenary Rework: Introducing Grenzelhoft

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

This is the first step towards a major rework of mercenary gameplay.

**Technical details:**
- Tweaks mercenary stats to be more or less on par with adventurers, with particular attention to their specialization.
- Makes "Mercenaries" its own late join category.
- Restructures merc code to better allow the introduction of more merc jobs.

<h2>The Emperiate Grenzelhoft mercenary company</h2>

A landsknecht-themed guild with the imperial city of Grenzelhoft as its main center of operations, the "grenzelhofts" are known for their expertise, professionalism and loyalty to the company. Its members are trained in the use of pole arms and pike formation warfare.
Billhook           |  Halberd
:-------------------------:|:-------------------------:
Screenshot 2024-04-24 200427 |  Screenshot 2024-04-24 204307
Screenshot 2024-04-24 205023 | Screenshot 2024-04-24 204845

**Spawn location:** edge of the forest road. This means they'll have to walk through the bog gate to reach the city.
**Spawn slots:** 5, just like the desert riders.

## Why It's Good For The Game

Mercenaries are something that can greatly be expanded upon on this server AND for the benefit of this server. Along adventurers they are one of the few real third parties in what seems to be a constant atmosphere of King vs Rebels, and given the chance they will start influencing the many peoples of Roguetown for better or for worse.

### CODE REVIEW

**Comment by YosemiteYam** [comment]
Good pr, grenzelhoft as an adventurer subclass was weird, this will help the people that want to spawn as them and meet eachother to rp being comrades easier. Uniforms look nice too

**Comment by Osmos123** [comment]
Damn... the mercenaries are no longer walking lootboxes 😿

**Comment by NGGJamie** [comment]
Had one of them spawn naked this round.

**Comment by Gyrandola** [comment]
> Had one of them spawn naked this round
Completely? Weird.

**Comment by NGGJamie** [comment]
> > Had one of them spawn naked this round.
> 
> Completely? Weird.

Yeah, been seeing it the next two rounds as well. The Grenzelhoft ones are needing to get admin-equipped.

**Comment by Gyrandola** [comment]
Removed some unused generic mercenary spawns in the tavern that might have been causing that issue.

**Comment by NGGJamie** [comment]
> Removed some unused generic mercenary spawns in the tavern that might have been causing that issue.

That'll probably be it because that's where they were naked. I'll update the TM when I'm home. If that's fixed, we should be good to merge.

**Comment by Gyrandola** [comment]
How can I resolve this conflict? The donator/grenzelhoft.dm is supposed to have been removed.

**Comment by Osmos123** [comment]
> How can I resolve this conflict? The donator/grenzelhoft.dm is supposed to have been removed.

would recommend reopening a new pr, seems many pr's got merge conflicts now.

**Comment by NGGJamie** [comment]
> How can I resolve this conflict? The donator/grenzelhoft.dm is supposed to have been removed.

Either a new PR or rebase off of current code.

**Comment by Gyrandola** [comment]
Rebased. Should be good to merge now.

**Comment by NGGJamie** [comment]
It will most likely be good, I'll add it to TM until we verify that nothign was effected during rebase.

**Comment by NGGJamie** [comment]
@ChungusGamer666 okay, after this PR's map conflict gets resolved, we need to speedmerge this in because this poor guy's had to do this like 3 times now lol.

**Pull request merged**
