### PR TITLE
Racism lore: (Almost) Every nobility position is humen-locked, (almost) every other job has no race locks

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Rockhill has fallen...
image

What the title says. Every noble position is now humen only, EXCEPT for...
-Prince who can also be half elf because bastard children are hilarious
-Court mage because elves are magic and this is a classic fantasy trope
-Merchant, who can also be a half elf because again bastard children are hilarious

## Why It's Good For The Game

Better racism experience

### CODE REVIEW

**Comment by YosemiteYam** [comment]
Finally an end to shitter dwarves who take noble roles and suicide as them

**Comment by Ambrose997** [comment]
This is dumb, why are you taking autonomy away from the king?

**Comment by BlueMemesauce** [comment]
Why removed it for lady? it literally says in the role description that the queen was chosen for political reasons. and elf queens are based

**Comment by BlueMemesauce** [comment]
and why did you add dark elf to everything the whole point of the dark elf is that they are shunned from society and can only be gravediggers and stuff, you literally get a bad moodlet if you look at them

**Comment by wow50000** [comment]
idk i find tiefling merchants to be funny

**Comment by BlueMemesauce** [comment]
Yea I don't see why merchants would be restricted, I guess tieflings would be less likely to have money but it makes no sense to restrict the other roles. Merchants aren't nobility

**Comment by Ambrose997** [comment]
Yeah why the fuck would you restrict merchant? Merchants aren't nobility??

**Pull request merged**
