### PR TITLE
The Sarkness Extravaganza: QOL Changes, Noc T3 Spell, Dwarf Armor

### PR DESCRIPTION
**Pull request by Sarkness**
## About The Pull Request

Greetings you incredible people, today I'm presenting you a HUGEEEEE Array of QOLs changes and new additions, so that Blackstone keeps rolling like the good medieval adventure it is! Below you'll find the changelog
**_The new additions:_**
- Dwarf Knight Armor
- Dwarf Punisher Armor
- Dwarf Engineer, Overseer Helmets
- Wizard Iron Cap
- The remaining Gem rings (Steel/Gold Variant)
- Secret Valuable
- Noc Tier 3 Spell: Moonbeam. Concentrate the moon power on someone to incapacitate them highly, or to completely annihilate any undead being too dangerous for the Church.
**_The QOL Changes:_**
- Steward, Bailiff, Bogmaster and Queen now have a SCOMStone (Emerald Ring) to communicate and be able to hear whenever they're requested through SCOMs at any times, this should hopefully lower the amount of King Announcements for such.
- Desert Mercenaries welcome back some companions in the guild: Dark Elves, Elves, and Tieflings
- Nerfed Male Blacksmith Pilgrim, Buffed Female Blacksmith Pilgrim so they're on par together and gives a breather/importance to the Weaponsmith/Armorer
- Lightly buffed Armorers/Weaponsmiths in terms of their craftings
**_Coming Soon:_**
- Humen Racial Armor
- Elf Racial Armor
- Wizard Spells (Code already present in my commit, please fix them if you can!)
- Heartfelt Soldiers: Only for Siege Events.
- Faes: Pixies that'll be friendly in the Bog and will heal players before fleeing and having a 50% of fading away after that.
- Black Knights: You better pray to not meet these mini-bosses of the Bog. Very strong and very agile, these AIs are like the King's Knights, and will slice you up with their bastard swords and heavy-duty armors.

## Why It's Good For The Game

Additions:
- Dwarf Armors, were requested since a while, and are the first of a three-parts series, in which each race will have to get specific armor tailored and smithed only for them. The following is a work from Takyon, and fixes were done by Karl. Approved by MAGNUM and Sangheili since a moment.
- Noc T3 Spell: Largely followed and appreciated for it's D&D ressemblance, this V1 should give a preview of the ray of light that'll soon gives heavy sunburn to those unfortunate into walking into the pillar of divine justice.
- Wizard Iron Cap: Helmet, for wizards, no need to say more. Their only headpiece that'll aid them I won't lie without losing Endurance/Stamina.
- Gem rings: Self-Explanatory.
- Secret: Secret.
QOL Changes:
Emerald Rings/SCOMStones:
- Many players sees that the Steward and Bailiff are often having troubles managing troops or being present when needed in the Court and in the Town, this change should hopefully aid them counter this issue.
- This also gives the lady the possibility to warn her lord from any potential threats and be more active alongside him.
- Finally, the Bog Master only having one SCOM and often found gone/lost in the few minutes of the game, can have this as a way to be assisted by the Court/Town Guards, communicating with Bailiff/Sheriff or requesting equipment to the Steward.
Desert Mercenaries:
- They were just gone at this point, no real popularity due to like 60/70% of the playerbase playing outsiders races from a desert company. This change should hopefully bring them back on the table and make them useful once again, hopefully. Grenzelhofts I'm scratching my head (literally) on how to make them interesting again.
Blacksmith:
- A huge disparity between both blacksmithes (credits to @wow5000) which made female blacksmithes unable to forge properly with the new Smithes PR while Male Smithes Pilgrims outclassed Armorer/Weaponsmiths, making these normally crucial role very much useless. This should offset the balance and make it an equal ground for the smithes pilgrims, and the armorer/weaponsmith while keeping advantage to males without being detrimental to females smithes players.

PR TESTED AND REVIEWED PERSONALLY; PLAYTEST/VIEW AT YOUR OWN RISK BEFORE **FUCKING MERGING IT INTO THE OFFICIAL BLACKSTONE.**

### CODE REVIEW

**Comment by Gyrandola** [comment]
I think this PR should be split in multiple. Some of these changes arent QOL, they are outright features.

**Comment by CVSthePharmacy** [comment]
found the secret

**Comment by Sarkness** [comment]
> found the secret

DO NOT TALK ABOUT IT.

**Comment by ChungusGamer666** [comment]
atomize these changes for the love of god, this is all unrelated stuff that should be in different prs

**Comment by Sarkness** [comment]
> atomize these changes for the love of god, this is all unrelated stuff that should be in different prs

Issue being if I close PR all my commitss get discarded due to head.dmi having conflicting files.
I am fine with subdivising next time but I guess this time It's a bit late.

**Comment by CVSthePharmacy** [comment]
> > found the secret
> 
> DO NOT TALK ABOUT IT.

but why :(

**Comment by dunsel-hordon** [comment]
I mean the secret won't be secret as soon as you go to smith dragon ring

**Comment by CVSthePharmacy** [comment]
> I mean the secret won't be secret as soon as you go to smith dragon ring

shut

**Comment by YosemiteYam** [comment]
Dwarf Knight Armor
    Dwarf Punisher Armor
    Dwarf Engineer, Overseer Helmets 
**I can see some problems stemming from race-only armors but meh we'll see ingame**

    Wizard Iron Cap
**Unsure why a wizard iron cap would exist when they do not have armor training and thus having class specific iron/steel armor for them would be odd**

    The remaining Gem rings (Steel/Gold Variant)
    Secret Valuable
**Fine**

    Noc Tier 3 Spell: Moonbeam. Concentrate the moon power on someone to incapacitate them highly, or to completely annihilate any undead being too dangerous for the Church.
**Stun combat is fucking tedious and complained about constantly, one of the reasons people hated the necromancer stuns. We already have lightning bolt that stuns you and firebolt that incapacitates you and burns your limbs in seconds if youre not quick enough to put it out, I do not think mages need ANOTHER single target stun spell, this should be re-thought as a different sort of spell. IMO mages need more utility spells than just giving them more and more combat spells.**

    The QOL Changes:
    Steward, Bailiff, Bogmaster and Queen now have a SCOMStone (Emerald Ring) to communicate and be able to hear whenever they're requested through SCOMs at any times, this should hopefully lower the amount of King Announcements for such.
**Eh, I don't see these as being useful, If people ignore SCOM its not due to scoms not being available, nearly every location ingame will have you in a SCOM's radius, and emerald rings are frequently discarded or not used due to being annoying to get hit by scom text on your person and also because they hear your conversations. I forsee alot of scom spam due to people having their emerald rings on like radios. Also on that point, people shouldnt just have magic radio rings, if a king has to call a courtier to him himself then tough shit, or just send a courier. This is very handholdy**

    Desert Mercenaries welcome back some companions in the guild: Dark Elves, Elves, and Tieflings
**Non desert humen races were removed for a reason to keep the mercenary guilds lore accurate to their kingdoms.**

    Nerfed Male Blacksmith Pilgrim, Buffed Female Blacksmith Pilgrim so they're on par together and gives a breather/importance to the Weaponsmith/Armorer
    Lightly buffed Armorers/Weaponsmiths in terms of their craftings
**whatever sure**


All in all some of these pr's (mostly the armorsmith/craftsmen changes) are fine but the rest is not good, I do not see much QOL here, giving half the court the radio rings, giving mages another stun-cancer spell and reverting the desert merc humen supremacy is not a boon to the server

**Comment by Sarkness** [comment]
THIS NOW HAS ONLY THE RACIAL DWARF STUFF. 
EVERYTHING ELSE HAS BEEEN MOVED TO DIFFERENT BRANCHES.

**Comment by Sarkness** [comment]
Reopening PR without all the other code

**Pull request closed without merging**
