### PR TITLE
Banditbuffs, changes some music

### PR DESCRIPTION
**Pull request by bobjension**
considering the server has over 100+ playing, I think bandits need a bit of love, maniac is also a solo antag, (can't play as him tho, broken code)

### CODE REVIEW

**Comment by Osmos123** [comment]
Good change, bandits usually get rolled at the start by adventurers. Maybe this time it will require the intervention of the crown to stop these banditos.

**Comment by bobjension** [comment]
bandits lost their cult drip and have been replaced with just a facemask

**Comment by Osmos123** [comment]
Good changes, bandits will have expert skill level for whichever weapon they spawn with. Should be able to beat any adventurer in 1v1 (most adventurers are only skilled in their main weapon)

**Comment by Henri9576** [comment]
can't wait for bandits to use this to just RDM harder

**Comment by ChungusGamer666** [comment]
byeah

**Pull request merged**
