### PR TITLE
Buffs Soilson. Rebrands Councilor & Bailliff [FIX THIS] 

### PR DESCRIPTION
**Pull request by asskek**
I completely FUCKED this somehow while experimenting with a bigger change (adding a role). I reverted the bigger change and it somehow fucked it and now it won't compile at all. I'm 999% sure it's the 3000 deletions you see in roguetown.dme, but every time I fix roguetown.dme and try to compile, it deletes almost all of roguetown.dme

## About The Pull Request

Gives soilson sewing skill + increased wrestling as he has literally 0 self defense

Makes councilor less of a wrestling god; makes him a CHANCELLOR instead of a councilor, because "councilor"=advisor and I'm sick of seeing these guys somehow have more power in the court than the fucking Hand

## Why It's Good For The Game

Soilsons have to spend 20+ minutes grinding sewing skill just to get sacks, and their job fucking SUCKS without sacks. They also have 0 defense against the rando bandits that pull up to wipe them; I don't want them to be warriors, but being able to grab is always handy. They're a role that contributes to the setting immensely, they should get a little something

Councilors have consistently been annoying fucks & the fact they're wrestling champs has been awful
This slots them into a more specific RP position that's not tied to the underplayed bailiff role and doesn't give them room to be "the king's #1 advisor", which they've been default by the title "councilor", unless they really try for it

### CODE REVIEW

**Comment by thefirstjeb** [comment]
Everytime i'm playing as bogmaster i always set atleast two bogmen soldiers to be soilsons bodyguards, i see this as an IC/RP issue as the people in power need to care enough about their citzen and send guards to work.

I totally agree with sewing too, atleast until we get a tailor role that would make soilsons have to buy sacks from him which increase in RP/interactions.

**Comment by NGGJamie** [comment]
Unless you actively made changes to it, just copy the roguetown.dme off the current main branch and use that over whatever happened to the one you have in this branch. Should resolve your issue.

**Comment by BadAtThisGame302** [comment]
Isn't Chancellor a more prudent job name than Councillor? It seems to me like they might excert authority more by that, though I am not sure. Advisor or Courtisan might be better, not sure.

**Comment by asskek** [comment]
> Everytime i'm playing as bogmaster i always set atleast two bogmen soldiers to be soilsons bodyguards, i see this as an IC/RP issue as the people in power need to care enough about their citzen and send guards to work.
> 
> I totally agree with sewing too, atleast until we get a tailor role that would make soilsons have to buy sacks from him which increase in RP/interactions.

Well, bear in mind that the soilfolk are the most reliable & efficient source of fibers on the server (wheat threshing). It makes more sense for the soilfolk to also function as tailors; especially since if they know what they're doing, they can make enough flour for the entire server to have fat bellies in the first 20ish minutes of the round. They usually end up pretty out of shit to do after that if they don't care to pursue alcohol brewing. Adding a tailor role when soilfolk are not only the resource producers _for tailoring_ but have ample time to specialize in it, seems redundant.



> Isn't Chancellor a more prudent job name than Councillor? It seems to me like they might excert authority more by that, though I am not sure. Advisor or Courtisan might be better, not sure.

I don't think you know what a courtesan is brother. They uhh might be involved in court politics but.... They have _other_ duties to the King 

A chancellor simply implies a politician of some office. Councillor, Advisor, both imply they're up there whispering directly in the King's ear like they're the fucking Hand or Bailiff, and yep thats exactly how theyve been played. Barely see Bailiffs get to accomplish anything on the other hand, which I'd like to fix, hence the big flavor text change

**Comment by BadAtThisGame302** [comment]
> > Everytime i'm playing as bogmaster i always set atleast two bogmen soldiers to be soilsons bodyguards, i see this as an IC/RP issue as the people in power need to care enough about their citzen and send guards to work.
> > I totally agree with sewing too, atleast until we get a tailor role that would make soilsons have to buy sacks from him which increase in RP/interactions.
> 
> Well, bear in mind that the soilfolk are the most reliable & efficient source of fibers on the server (wheat threshing). It makes more sense for the soilfolk to also function as tailors; especially since if they know what they're doing, they can make enough flour for the entire server to have fat bellies in the first 20ish minutes of the round. They usually end up pretty out of shit to do after that if they don't care to pursue alcohol brewing. Adding a tailor role when soilfolk are not only the resource producers _for tailoring_ but have ample time to specialize in it, seems redundant.
> 
> > Isn't Chancellor a more prudent job name than Councillor? It seems to me like they might excert authority more by that, though I am not sure. Advisor or Courtisan might be better, not sure.
> 
> I don't think you know what a courtesan is brother. They uhh might be involved in court politics but.... They have _other_ duties to the King
> 
> A chancellor simply implies a politician of some office. Councillor, Advisor, both imply they're up there whispering directly in the King's ear like they're the fucking Hand or Bailiff, and yep thats exactly how theyve been played. Barely see Bailiffs get to accomplish anything on the other hand, which I'd like to fix, hence the big flavor text change

I meant Courtier.

**Comment by JTGSZ** [comment]
i suggest splitting this, and probably making sure the next attempt isn't fucked

**Comment by thefirstjeb** [comment]
> 
> Well, bear in mind that the soilfolk are the most reliable & efficient source of fibers on the server (wheat threshing). It makes more sense for the soilfolk to also function as tailors; especially since if they know what they're doing, they can make enough flour for the entire server to have fat bellies in the first 20ish minutes of the round. They usually end up pretty out of shit to do after that if they don't care to pursue alcohol brewing. Adding a tailor role when soilfolk are not only the resource producers _for tailoring_ but have ample time to specialize in it, seems redundant.
> 

Well what you see as a redudancy i see an opportunity for people to interact, trade and RP. aka tailor move to soilsons to buy his fiber and sell his stuff for other townies. Also having a tailor opens up space for creating many recipes for clothes and armor/equipment.

**Pull request closed without merging**
