### PR TITLE
SEVERS THE DIVINE LIGHT

### PR DESCRIPTION
**Pull request by SELFHELL**
DIVINELIGHT

THE SNOWFLAKE ANGEL RACE HAS BEEN RECALLED BY PSYDON.
THIS UNBLESSED LAND IS DOOMED TO CONFLICT AND FAMINE
HALF ORCS HAVE RE-ENTERED PUBLIC NANOTRANSMITTERS AS A RESULT
GLORY TO ZIZO

### CODE REVIEW

**Comment by assortedbeads** [comment]
No night vision?

**Comment by ChungusGamer666** [comment]
godlike PR

**Comment by SELFHELL** [comment]
ok pr ready

**Comment by Real-MAGNUM** [comment]
testmerging

**Comment by Osmos123** [comment]
My only gripe is that is seems they are better dwarfs in terms of stats (dwarves for comparison below)
image

Would like to see maybe a one more point decrease in perception and intelligence.

**Comment by Ambrose997** [comment]
bruh all we did was play the fuckin game why did you have to delete the race for T_T. 

More snowflakes on drow, delete their ass.

**Comment by wow50000** [comment]
why are half orks smarter than humen male ?

**Comment by Real-MAGNUM** [comment]
Return aasimar to roundstart roles. Not selectable regardless of server config.

If it's unintentional, please bugfix it.

**Comment by Osmos123** [comment]
> THE SNOWFLAKE ANGEL RACE HAS BEEN RECALLED BY PSYDON.

1000% intentional "THE SNOWFLAKE ANGEL RACE HAS BEEN RECALLED BY PSYDON."

**Comment by Osmos123** [comment]
> Return aasimar to roundstart roles. Not selectable regardless of server config.
> 
> If it's unintentional, please bugfix it.

Seems it was intentional interestingly "THE SNOWFLAKE ANGEL RACE HAS BEEN RECALLED BY PSYDON."

**Comment by Ambrose997** [comment]
> > Return aasimar to roundstart roles. Not selectable regardless of server config.
> > If it's unintentional, please bugfix it.
> 
> Seems it was intentional interestingly "THE SNOWFLAKE ANGEL RACE HAS BEEN RECALLED BY PSYDON."

Fucking why? Way more snowflakes on drow AND they're stronger.

**Comment by SELFHELL** [comment]
Int/fortune will be nerfed

**Comment by assortedbeads** [comment]
Would it be possible to give them darkvision? They are greenskins afterall

**Comment by assortedbeads** [comment]
Also maybe give fem orcs the barbarian hair

**Comment by OrbitalParadise** [comment]
No string replacements?

**Comment by pilotmans** [comment]
Nice to have half orks but the removal of Aasimars seems to be an entirely pointless endeavor that removes choice from the players

**Comment by Ambrose997** [comment]
> Nice to have half orks but the removal of Aasimars seems to be an entirely pointless endeavor that removes choice from the players

Yeaah thats my issue with some dev decisions on testmerges and stuff. Abraxas will legit see a cool picture with a meme controversial title about getting rid of "le snowflake class" (that no one really complains about existing) and he'll go "BASED BASED BASED HALF ORC GAMING" and approve it without much thought lol.

Dw hes coming around to the idea of allowing Aasimar to exist in a more grimdark way i.e instead of their shitty lore from before they're gonna be more considered like the nephilim mentioned in Christianity that are considered abominations of nature (racism instead of awe).

**Comment by Real-MAGNUM** [comment]
updated TM

**Comment by assortedbeads** [comment]
I mentioned this earlier but give horcs something to make them unique so they arent just a green human people want to be racist towards. (All races should have something).

Currently dwarves have booze healing, delfs have darkvision. 
Personally I would prefer horcs have darkvision (goblins are greenskins and have nightmare vision) as well but if you want them to have something else, maybe something to resist pain or something.
I would say give darkvision anyway since unlike delfs they can only choose 3 classes from adventurer, all close range with no spells or magic which means they are inherently more limited.

They're also unable to have burns or scars which is weird, they're horcs and warriors why are their faces unable to be unmarked.

The women horcs (horcs in general) need a better selection of hair, give the woman berserker hair and shaved head options. Why do they have twin tails when they're mainly warriors?

**Comment by Ambrose997** [comment]
> updated TM

Still isn't available ingame even after a new round has started.

**Comment by Wintermote** [comment]
> Dw hes coming around to the idea of allowing Aasimar to exist in a more grimdark way i.e instead of their shitty lore from before they're gonna be more considered like the nephilim mentioned in Christianity that are considered abominations of nature (racism instead of awe).

A big problem here is a lack of anything informing people: This is the racial background, the general behaviour, the culture, etc.
So players are just pulling from what they like and are familiar with.

**Comment by Real-MAGNUM** [comment]
testmerge updated

**Comment by Real-MAGNUM** [comment]
Half orcs can be armorers but they cant be weaponsmiths.

**Comment by ChungusGamer666** [comment]
To be expanded upon, but seems safe to merge

**Comment by Real-MAGNUM** [comment]
Add shaved hairstyle to beards for orcs.

**Pull request merged**
