### PR TITLE
Fixes my Mistakes + Walence

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Removes some stuff from being snowflake adventurer locked + adjusts castle guard sword skill

## Why It's Good For The Game

Fixes some of my earlier mistakes; also castle guards sadly shouldn't have the CHANCE to have the same skill as knights with the skill leveling changes

### CODE REVIEW

**Comment by Wintermote** [comment]
I wouldn't call giving rogues poison bolts and arrows just "fixing some mistakes", that's a huge balance change.

**Comment by Real-MAGNUM** [comment]
> I wouldn't call giving rogues poison bolts and arrows just "fixing some mistakes", that's a huge balance change.

He's right you know.

**Comment by Real-MAGNUM** [comment]
Nvm those look like they're for supply packs, not on spawn.

**Comment by BlueMemesauce** [comment]
He's wrong, rogue refers to roguetown

**Comment by Real-MAGNUM** [comment]
merging

**Comment by Yellows91** [comment]
>also castle guards sadly shouldn't have the CHANCE to have the same skill as knights with the skill leveling changes

If you pick "Middle-Aged" and sacrifice stats for skills. Shouldn't a castle guard be a master at swordsmanship instead of expert (since they start expert) or is this completely unrelated to the age stat/skill thing.

**Comment by BlueMemesauce** [comment]
No, it was a random chance where they got 1/3 chance of +1 swordmanship didnt have anything to do with age

**Pull request merged**
