### PR TITLE
515 Compatibility (Part 1?)

### PR DESCRIPTION
**Pull request by Contrabang**
This introduces PROC REF defines, and transfers all of our references of procs over to it. This also makes runechat INSTANT AGAIN, along with unbreaking a shit load of stuff. Probably also breaks some stuff too, but all the main game features seem to be working.

image

### CODE REVIEW

**Review by LudwigVonChesterfield — APPROVED** [review]
files changed 666 nice

**Review by Henri215 — APPROVED** [review]
Lewcs good to me, buy me a new mouse scroll after this

**Comment by JTGSZ** [comment]
here hopin

**Comment by panvxv** [comment]
I think it broke wealth hordes in treasury file.
Lord and Queen aren't getting the message about receiving wealth. So probably whole part of code doesn't work.

**Pull request merged**
