### PR TITLE
Comments out stealing from back slots

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
This does exactly what it says on the tin. Something that is on your back slot is strapped onto your torso, and there is no way on Psydon's green earth that this should be doable instantly, let alone have the same difficulty (none) as stealing a coinpouch.

## Why It's Good For The Game
It is exactly zero fun having your shield, weapon, or backpack instantly stolen right off your back. If the commie worshippers want it that bad, they can go through the inventory menu to do it.

### CODE REVIEW

**Comment by Hmeister-real** [comment]
Major, Major cope PR. If anything add in Bag cutting stealing, where you need to hold a knife in the offhand, and cut the band on the bag to steal it, but stealing weapons is literally fine with the Stealing from behind PR. -1 unless you make it what i suggested and just that

**Comment by WindowTalents** [comment]
Yeah unless this adds no neck armor steal this is pretty silly, come on dood.

I like to actually wear empty bags... so I can KILL thieves haha...

**Comment by DerFlammenwerfer** [comment]
> Major, Major cope PR. If anything add in Bag cutting stealing, where you need to hold a knife in the offhand, and cut the band on the bag to steal it, but stealing weapons is literally fine with the Stealing from behind PR. -1 unless you make it what i suggested and just that

Until such a time as the difficulty of thieving is balanced around the item attempting to be stolen, this is how it will have to be.

**Comment by WindowTalents** [comment]
> Until such a time as the difficulty of thieving is balanced around the item attempting to be stolen, this is how it will have to be.

No it does not.
I'm literally arguing on the side of the victim here, that this is so infrequent - that you should really reconsider this.

**Comment by DerFlammenwerfer** [comment]
No longer needed + it was a bad PR

**Pull request closed without merging**
