### PR TITLE
removes stat differences between genders

### PR DESCRIPTION
**Pull request by Yarinoi**
if you're upset about it being unrealistic: why arent you upset about
- all the nonhuman races (elves, dark elves, half-elves, dwarves, tieflings, aasimars)
- goblins
- skeletons
- zombies
- scom and shylock
- magic
- gods
if you're upset about the actual stats themselves (balance, minmaxxing, whatever): fair enough, i would fix that but i'm not a good enough coder to do so

### CODE REVIEW

**Comment by Wintermote** [comment]
I actually like playing unequal characters in my videogames, it makes things more interesting and flavorful instead of everyone being exactly the same.

**Comment by Yarinoi** [comment]
> I actually like playing unequal characters in my videogames, it makes things more interesting and flavorful instead of everyone being exactly the same.

true, but separating it by genders aint it, besides i'm sure jobs & species do a well enough job of making people varied stat-wise
though it'd be cool if we could modify the stats of our characters in the character setup menu...

**Comment by hollyhocc** [comment]
good change

**Comment by ChungusGamer666** [comment]
No, I'm not gonna even entertain this.

**Comment by hollyhocc** [comment]
why

**Comment by Yarinoi** [comment]
> No, I'm not gonna even entertain this.

explain why not

**Comment by ChungusGamer666** [comment]
It goes against the original vision of the game. I just think the game being founded upon misogyny as the setting is low fantasy *makes sense*. 
Disagree? Make your own fucking fork, call it Wholesome Redditown 13 or whatever and put it on the hub.

**Comment by ChungusGamer666** [comment]
My next BLACKEDstone update:
-Adds pride pins
-Removes all gender limits on roles
-Removes stat difference between sexes (sexual dimorphism is not real)
-Adds pride flags to the keep (indestructible)
-Adds pronouns to the character setup (including neopronouns)

I'm trans BTW

**Comment by Yarinoi** [comment]
> It goes against the original vision of the game. I just think the game being founded upon misogyny as the setting is low fantasy _makes sense_. Disagree? Make your own fucking fork, call it Wholesome Redditown 13 or whatever and put it on the hub.

fair enough i guess but meh, it would be cool if there was a way to boost stats otherwise at least rather then through careful picking of species and jobs instead of just being worse cuz you picked a female character lmao

> I'm trans BTW

same 🏳️‍⚧️

**Pull request closed without merging**
