### PR TITLE
Moves bog gate closer to town, merges bog with town map

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Combined two maps together, moves the bog village outside of the bog gates protection, but also places the bog garrison building inside the village, meaning the bog gate is de facto the town guard of the bog village, bog gate and garrison have a connecting hallway through the gatehouse

Moves most of the old bog village houses into the new area, does not touch the actual town part of the map just moves it into this new map, relocates the bog dwarf camp to the east of bog village, also gives them a 2Z down mining cave

## Why It's Good For The Game

Let's the bog guard be the first line of defense but also gives them a pacifying role on the village, tested locally and working without problems, stairs gates and doors/windows all seem to be working as they should

Z3
Z3

Z4
Z4

Me testing the bog gates

Me testing the dwarf stairs
2 - Copy

### CODE REVIEW

**Comment by zakanater19** [comment]
Also unclear from the pictures but the red wall goes up from Z3 to Z5 all the way around town, apart from the bog gate

**Comment by NGGJamie** [comment]
@Real-MAGNUM

**Comment by bobjension** [comment]
"follow me, I'll lead you to town"

"just go north"

how much have we fallen....

**Comment by bobjension** [comment]
anyway yeah, this doesn't work with how the map generators are set, so unless you tweak it or do something like that, it's just gonna be a empty map with no ambushes, no naturally spawning rocks or bushes, etc etc

**Comment by zakanater19** [comment]
> anyway yeah, this doesn't work with how the map generators are set, so unless you tweak it or do something like that, it's just gonna be a empty map with no ambushes, no naturally spawning rocks or bushes, etc etc

You're right there isn't any grass spawning, not sure what is causing that

**Comment by zakanater19** [comment]
That should fix it

**Comment by zakanater19** [comment]
did not fix it, ill have to keep looking into it, or is there a fix?

**Comment by zakanater19** [comment]
Went ahead and just added grass and bushes around the bog area for now as a quick fix

**Comment by Real-MAGNUM** [comment]
> did not fix it, ill have to keep looking into it, or is there a fix?

There is an announcement in dev announcements about it. You must delete all hooks manually.

**Comment by zakanater19** [comment]
> > did not fix it, ill have to keep looking into it, or is there a fix?
> 
> There is an announcement in dev announcements about it. You must delete all hooks manually.

ill have a look at that now

**Comment by Real-MAGNUM** [comment]
This map looks like copypaste hell. It's like you frankensteined the entire thing and forgot you were pasting over half the content. You didnt even try to smooth the edges, it's just sharp ass boxes everywhere. The gate has a 1x1 line of rocks just slung from the wall to the mountain.

I'm already planning out a merge of the main map into the new bog map in a way that involves more than just copy pasting the entire thing in, and cutting half the map off.

I appreciate the attempt, though this looks like a massive downgrade compared to both the existing setup, and the changes I plan to make to the current bog.

Suggesting a close.

**Comment by zakanater19** [comment]
> This map looks like copypaste hell. It's like you frankensteined the entire thing and forgot you were pasting over half the content. You didnt even try to smooth the edges, it's just sharp ass boxes everywhere. The gate has a 1x1 line of rocks just slung from the wall to the mountain.
> 
> I'm already planning out a merge of the main map into the new bog map in a way that involves more than just copy pasting the entire thing in, and cutting half the map off.
> 
> I appreciate the attempt, though this looks like a massive downgrade compared to both the existing setup, and the changes I plan to make to the current bog.
> 
> Suggesting a close.

Fair enough, how about moving the bog village outside it's gates though?

**Comment by Real-MAGNUM** [comment]
> Fair enough, how about moving the bog village outside it's gates though?

I'm still looking over the map, but it's possible it'll be done.

**Pull request closed without merging**
