### PR TITLE
Light armor v2

### PR DESCRIPTION
**Pull request by LucaNotLucas**
## About The Pull Request

**Light armor dodging**
Adds a trait called "Fast reflexes" for rogues, rangers, and generally fast characters, makes it so dodging is easier and takes less stamina while only wearing light armor.

**New armor and crafting**
Adds a new light armor (since there isn't that many other than gamberson and leather), heavy leather armor! Takes 2 furs and 1 hide to make, protects arms, chest, groin and vitals, has some decent durability, and looks perfect on a rogue. Also added the ability to craft heavy leather gloves for 1 fur.

## Why It's Good For The Game

First, adds more variety when it comes to light armors, gives more uses for furs and hides, gives better light armors, and makes dodging actually an option, making it maybe easier to dodge than to parry, at the cost of not being able to wear medium/heavy armors.

Also, you might be wondering, "huh, i swear to god i saw this PR before" well, it's because it's the pr https://github.com/Blackstone-SS13/BLACKSTONE/pull/871
it had merge conflicts, i accidentally closed it, but now there's this new one, and it hopefully also fixes the conflicts now

### CODE REVIEW

**Comment by JTGSZ** [comment]
This comes out to 50% stam use reduction and +50% boost of the current values ran through to dodge with the trait?

**Comment by Takyon69** [comment]
Can you post screenshots of the new sprites here?

**Comment by CVSthePharmacy** [comment]
bro gave him the rust parka jacket

**Comment by CVSthePharmacy** [comment]
> Can you post screenshots of the new sprites here?

go to the icondiffbot thing at the bottom of this PR and go to details, then press the play button to see the sprites

**Comment by LucaNotLucas** [comment]
> This comes out to 50% stam use reduction and +50% boost of the current values ran through to dodge with the trait?

Yes, i mostly decided to reduce the stam use since parrying uses 5 stamina and dodging uses 10, with the trait both of them use the same amount.

**Comment by wow50000** [comment]
i would like padded dresses to be craftable as well preferably out of cloth instead of fibers like the gambeson

**Comment by LucaNotLucas** [comment]
> i would like padded dresses to be craftable as well preferably out of cloth instead of fibers like the gambeson

eh, why not, i'll also change the gambeson recipe so you can buy the cloth from the stockpile instead of having to go around searching for fibers

**Comment by assortedbeads** [comment]
Maybe increase the crafting costs of these items?

Heavy Leather Armor
- 2 Fur 4 - 6 Hide

Heavy Leather Gloves
- 1 Fur 2 Hide

Basing these new numbers over the fact that hunting is very easy to rack up hide from, and bait is easily craftable

Hunting gives
- Saiga - 4 steak, 2 fat, 4 hide
- Goat- 4 steak, 2 fat, 2 hide, 1 fur
- Volf - 2 steak, 2 hide, 1 fur
- Rous - 1 steak, 1 hide

So the chest armor would need 1-2 Saiga and 1 Goat/Volf which seems hard enough to prevent seeing it everywhere but easy enough to not be overly restrictive.

**Comment by assortedbeads** [comment]
> > Can you post screenshots of the new sprites here?
> 
> go to the icondiffbot thing at the bottom of this PR and go to details, then press the play button to see the sprites

Snipping the spirites and posting them in a edit isnt like, hard though
Some people viewing are on mobile

**Comment by CVSthePharmacy** [comment]
> Maybe increase the crafting costs of these items?
> 
> Heavy Leather Armor
> 
> * 2 Fur 4 - 6 Hide
> 
> Heavy Leather Gloves
> 
> * 1 Fur 2 Hide
> 
> Basing these new numbers over the fact that hunting is very easy to rack up hide from, and bait is easily craftable
> 
> Hunting gives
> 
> * Saiga - 4 steak, 2 fat, 4 hide
> * Goat- 4 steak, 2 fat, 2 hide, 1 fur
> * Volf - 2 steak, 2 hide, 1 fur
> * Rous - 1 steak, 1 hide
> 
> So the chest armor would need 1-2 Saiga and 1 Goat/Volf which seems hard enough to prevent seeing it everywhere but easy enough to not be overly restrictive.

if you do this nobody will make it, ever, I mean it. Nobody makes waterskins for the same reason

**Comment by assortedbeads** [comment]
> > Maybe increase the crafting costs of these items?
> > 
> > Heavy Leather Armor
> > 
> > * 2 Fur 4 - 6 Hide
> > 
> > Heavy Leather Gloves
> > 
> > * 1 Fur 2 Hide
> > 
> > Basing these new numbers over the fact that hunting is very easy to rack up hide from, and bait is easily craftable
> > 
> > Hunting gives
> > 
> > * Saiga - 4 steak, 2 fat, 4 hide
> > * Goat- 4 steak, 2 fat, 2 hide, 1 fur
> > * Volf - 2 steak, 2 hide, 1 fur
> > * Rous - 1 steak, 1 hide
> > 
> > So the chest armor would need 1-2 Saiga and 1 Goat/Volf which seems hard enough to prevent seeing it everywhere but easy enough to not be overly restrictive.
> 
> if you do this nobody will make it, ever, I mean it. Nobody makes waterskins for the same reason

I make waterskins personally, isnt it possible they dont know they can make them?

You dont even have to do the hunting/farning yourself you can get the berries from the soilsons, and the hide/fur from them or the butcher.

**Comment by CVSthePharmacy** [comment]
> You dont even have to do the hunting/farning yourself you can get the berries from the soilsons, and the hide/fur from them or the butcher.

you're one of them "special" ones ey? well I'm talking about a majority of the people not wanting to make them cause they can't be fucked to farm more than once

**Comment by assortedbeads** [comment]
> > You dont even have to do the hunting/farning yourself you can get the berries from the soilsons, and the hide/fur from them or the butcher.
> 
> you're one of them "special" ones ey? well I'm talking about a majority of the people not wanting to make them cause they can't be fucked to farm more than once

They can just buy these items from the people that do farm then though?

Im not set on a 4-6 also if it was lower that's fine, like 2 fur and 3-4 hide.

**Comment by LucaNotLucas** [comment]
> They can just buy these items from the people that do farm then though?
> 
> Im not set on a 4-6 also if it was lower that's fine, like 2 fur and 3-4 hide.

While i do understand why you'd like cheaper prices, i must say most of the furs/hides are normally sold to the merchant for higher prices than the stockpile, not only that but not many people have the skincrafting hability to actually do the armors, so most people that don't have skincrafting just go and sell the hides, and some people that do have skincrafting might just prefer to sell the hides and then buy armor from the armourer instead of crafting it themselves.
If i do raise the cost, it's just gonna make it so the armor is almost never used
But if someday hides are used more, the costs will probably start going up

**Comment by LucaNotLucas** [comment]
imagen_2024-05-21_121055677

This is the armor icon

imagen_2024-05-21_121201631

And these are the on-mob icons


> bro gave him the rust parka jacket

If you've got a better idea on how "heavy leather armor" should look like, tell me, but a thick coat made of furs was the best thing i could think of

**Comment by Sevaaas1** [comment]
> imagen_2024-05-21_121055677
> 
> This is the armor icon
> 
> imagen_2024-05-21_121201631
> 
> And these are the on-mob icons
> 
> > bro gave him the rust parka jacket
> 
> If you've got a better idea on how "heavy leather armor" should look like, tell me, but a thick coat made of furs was the best thing i could think of

It looks good, but if you want inspiration for other styles, Mount and Blade Bannerlord has a ton of leather armor that looks amazing, like this 
2729255384_preview_BannerLordArmorGuideBeforeYoung

**Comment by LucaNotLucas** [comment]
Thanks btw, really appriciate you giving me some reccomendations, but i gotta say that just looks like a gambeson dyed black.
Will check the other armors tho

**Comment by Takyon69** [comment]
Don't we already have studded leather armour? Isn't that, in effect, heavy leather armour? I'm not familiar with its stats, but I think it could be used as a kind of light armour instead of adding yet another armour set.

**Comment by H0gberg** [comment]
the new armor fills a niche that has not been filled, very good pr, however, the only issue I have is that it seems like sentinels do not have any speed increases, doesn't that make it so sentinel shouldn't get the new dodging trait, however, it also does seem like it's the kinda class that should get it, so maybe just increase the speed sentinels get!

Either way very good pr!

**Comment by CVSthePharmacy** [comment]
> > Don't we already have studded leather armour? Isn't that, in effect, heavy leather armour? I'm not familiar with its stats, but I think it could be used as a kind of light armour instead of adding yet another armour set.
> 
> Studded leather armor is just leather armor with metal studs, the only differnece with the normal one is that it blocks chopping crits and has slightly better protection. Not only that but it needs iron to make so the armourer needs to craft it. This one on the other hand only needs furs and hides, protects the armas, and doesnt shine, so it fits more something a rogue, hunter or ranger would wear

protects the armas arterios

**Comment by Takyon69** [comment]
Only issue I have is that the sprite looks like a winter jacket and not heavy leather armour.

**Comment by LucaNotLucas** [comment]
imagen_2024-05-22_192523537

Would this be better?

**Comment by H0gberg** [comment]
> imagen_2024-05-22_192523537
> 
> Would this be better?

Maybe adding some shoulder armor the same way the studded leather had some I think would bring this all together

**Comment by LucaNotLucas** [comment]
> Maybe adding some shoulder armor the same way the studded leather had some I think would bring this all together

Great idea

**Comment by LucaNotLucas** [comment]
I'm not gonna lie i'm having trouble trying to add shoulder armor to it and actually make it look like shoulder armor, so i might not be doing it. This is the end result tho. Think it looks slightly better than before, 
imagen_2024-05-23_101349332

**Comment by LucaNotLucas** [comment]
imagen_2024-05-23_121600917
Made a liiiiiittle change so it looks less like a coat, and more like an armored vest w sleeves

**Comment by LucaNotLucas** [comment]
okay, sincerley, i'm not good enough to come up with a good looking leather armor, so i'll delete it from the PR and leave the rest.

**Pull request merged**
