### PR TITLE
Adds condemnations, the opposite of commendations FOR PLAYERS WITH PQ OF 30 OR ABOVE. Can be done once per round.

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Will be testmerged for a few rounds because I'm evil

## Why It's Good For The Game

Players are guinea pigs for my sick experiments

## REASONING

Ok this PR will most likely *NOT BE MERGED.*

The intent with this PR is two fold:
1. Seeing how much our players will abuse self-moderation tools, to judge viability on something like a sanity system
2. Seeing who are the most widely disliked players by seeing who gets most condemned

### CODE REVIEW

**Comment by Yellows91** [comment]
I just want to raise concern of removing PQ should be left purely to the admins and not the common players as this can easily be abused by meta groups, just like how commends are.

The same can be said for two people who hate each other and keep tanking each other's PQ in an attempt to permaban the other

**Comment by efzapa** [comment]
metagang buff my beloathed, gitban this man

**Comment by Alexeivichi** [comment]
This is a terrible idea frankly. Time to nuke all good players' commendations to prove a point.

**Comment by BigBigga** [comment]
lol PR

**Comment by NGGJamie** [comment]
I would limit the condemnations per condemned person. That way a metagroup of 10 people can't nuke someone's PQ in one round.

**Comment by Vivalas** [comment]
I think both commendation (and condemnations, if they stay) need to be limited per person. For instance, getting a commend from one person counts as one, and then the next time from the same person, as half, and then as a quarter, and so forth. This would pretty much neuter metagangs.

**Comment by thebigtony** [comment]
I love it when a PR actively encourages metacliques

**Comment by NGGJamie** [comment]
Closed per headdev

**Pull request closed without merging**
