### PR TITLE
Re-add elf queens, remove dark-elves allowed in everything, and removes female squires

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

Elf queens are very based and the description for queen says they were married for political reasons. 

Reverted #590 adding dark elfs and tieflings to everything, the whole point is that they're shunned in society, you literally get negative moodlet for looking at them. So they wouldn't be allowed as butler. And prisoner doesn't make sense for them either since they would just be executed and wouldn't be kept as a political prisoner. They definitely wouldn't be allowed to be the bogmaster.  I left them for blacksmith which is kind of borderline since blacksmith is a respected position but it's still a peasant position.

Removes female squires since the whole point of squires is that they are training to be a knight, which can only be male. 

## Why It's Good For The Game

How can you not like elf queens they're just very based.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
elf queens are bad imo sorry

**Comment by Gyrandola** [comment]
`And prisoner doesn't make sense for them either since they would just be executed and wouldn't be kept as a political prisoner. `

Disagree. First of all not all prisoners are political lol. Second of all "they would just be executed" is your headcanon.

**Comment by JTGSZ** [comment]
Once again, conflicts and you need to talk to mister chungus about this.

**Comment by BadAtThisGame302** [comment]
The only two bad changes is the Elf Queen and removing the Tiefling/Drow from Prisoners, it's weird race locking a role who is supposed to be stuck in the dungeons the entire round to only some specific races, like, let him be who they want.

Second, elf Queen is bad and I don't see how marrying an elf for "political" reasons is a good idea, might even be political suicide in a place like this, considering the only Elvish Kingdom in lore is not even close to the Isle and it would be very much worth it to marry a Humen Noble from either of the empires.

**Comment by BlueMemesauce** [comment]
Keeping a prisoner was expensive since you had to feed them at least a minimum amount and keep them dying and give them free shelter. Dark elves and tieflings just aren't valuable enough to keep in a prison, they would probably be executed if they were suspected. Prisoners that were kept long term were usually important nobility that were being kept as hostages 

Foreign marriage creates alliances, which is pretty important for a weak kingdom. And elves and humans can create children. But I guess it wouldn't make sense if the elf kingdom was too far away

**Comment by Real-MAGNUM** [comment]
Yes and no. So many changes I'd rather just make my own pr than spam this one with change requests.

**Comment by BlueMemesauce** [comment]
when no elf queens
yakuza

**Pull request closed without merging**
