### PR TITLE
Goblin Race!

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Goblin race being playable race from roundstart!
As for now players won't spawn as there isn't a role for goblins. But they can look at the little goblin on during lobby time!

## Why It's Good For The Game
GOBO!

### CODE REVIEW

**Comment by assortedbeads** [comment]
Tempted by that which we cannot reach

**Comment by SELFHELL** [comment]
This is extremely reduntant to merge when theres nothing to even do with the race.

**Comment by Real-MAGNUM** [comment]
Having it means it's easier for things to be done with it. It will be excluded from the character creation menu via config.

**Comment by EnzoSeptum** [comment]
You make me happiest man alive

**Pull request merged**
