### PR TITLE
Makes prisoner roundstart only to fix them latejoining on the boat outside cells

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Temporary fix for me not being able to figure out how to make prisoners spawn in the cells latejoin

## Why It's Good For The Game

Prisoners no longer latejoin outside of cells

### CODE REVIEW

**Comment by TheManWithNoHands** [comment]
Maybe look how the adventures and pilgrims can spawn not in the boat as late join.
Thats a role restricted spawn point after all.

**Comment by zakanater19** [comment]
> Maybe look how the adventures and pilgrims can spawn not in the boat as late join. Thats a role restricted spawn point after all.

Yeah i tried using it as a reference but using the adventuerlatejoin spawns and overriding the jobrole to prisoner still didn't work even after like four attempts at tweaking it, and even making a new marker didn't work

**Comment by BlueMemesauce** [comment]
Adventurers spawn in the forest along the edges of the map which makes sense. Prisoners randomly appearing in a cell wouldn't make much sense

**Comment by thebigtony** [comment]
Spawning in a cell would make more sense than spawning on the boat. But I think this is a good PR.

**Comment by Real-MAGNUM** [comment]
Testmerging. You probably need to create a new spawn marker for prisoners in specific.

**Comment by CVSthePharmacy** [comment]
people with -30 pq can't spawn anymore, this is a shadowban now, revert this pr

**Comment by BlueMemesauce** [comment]
Only if admins give you negative pq

**Comment by CVSthePharmacy** [comment]
> Only if admins give you negative pq, which shouldn't be happening

we just disproved what you said, now revert it as it shadowbans people

**Comment by BlueMemesauce** [comment]
The admins can also just straight up ban people so

**Pull request merged**
