### PR TITLE
Tones down Goblins

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

If the PR author has no interest in making goblins a proper antagonist, they should be toned down to NOT function as such every round.

Also goblin kings having the ability to spam everyone is.. stupid?

## Why It's Good For The Game

Common sense.

### CODE REVIEW

**Comment by Xkallubar** [comment]
No

**Comment by Xkallubar** [comment]
Goblins are already weak enough. This just completely dooms them.

**Comment by Real-MAGNUM** [comment]
They dont need a nerf at the moment.

Goblin announcements should be goblin faction/species only. Change that if you want to remove their global announcements.

You didnt put an end */ to your comment.

**Comment by BlueMemesauce** [comment]
> Goblins are already weak enough. Goblins are only strong when they have the support of adventurers. Goblins are incredibly weak and only stand a chance in large numbers, this will just doom them to die to bandits or adventurers.

Good, they are meant to die to adventurers. Their entire purpsoe is to be content for adventurers to kill.

**Comment by Xkallubar** [comment]
> > Goblins are already weak enough. Goblins are only strong when they have the support of adventurers. Goblins are incredibly weak and only stand a chance in large numbers, this will just doom them to die to bandits or adventurers.
> 
> Good, they are meant to die to adventurers. Their entire purpsoe is to be content for adventurers to kill.

That's not their entire purpose, and they already die easily to a prepared group of adventurers, but okay.

**Pull request closed without merging**
