### PR TITLE
Rename doctor to doctor.dm

### PR DESCRIPTION
**Pull request by WindowTalents**
Yup.
SMOOTH, brain.

## About The Pull Request
FUCK

## Why It's Good For The Game
AAAAAAAA

### CODE REVIEW

**Comment by ophaq** [comment]
SOMEONE PLEASE SPEEDMERGE.

**Comment by WindowTalents** [comment]
> SOMEONE PLEASE SPEEDMERGE.

It genuinely makes me so happy to see even one person want to play my silly role this much, thank you lol.

**Comment by erik30015** [comment]
why no pilgrim doctor tough?

**Comment by WindowTalents** [comment]
I'm fixing it, it will be thrown on pilgrim too.

**Pull request merged**
