### PR TITLE
Makes all classes always show up when chossing class

### PR DESCRIPTION
**Pull request by K4rlox**
no longer luck based

### CODE REVIEW

**Comment by bobjension** [comment]
this is probably bad cuh uh there's no reason for people not to pick the better classes

**Comment by Xkallubar** [comment]
Huzzah

**Comment by YosemiteYam** [comment]
Maybe limit the rarer class slots like the upgraded versions of hunter (ranger), monk, crusader etc

**Comment by Henri9576** [comment]
Having to either kill myself and go through underworld or wait until the next round to do a gimmick that I have in mind for a specific class due to pure RnG is not a good gameplay feature.

Good change.

**Comment by K4rlox** [comment]
> Yeah this generally just seems bad... might as well just remove the worse classes.

im gonna buff and nerf some classes after this gets merged

**Comment by ChungusGamer666** [comment]
Awful for balance but I don't feel comfortable nuking this PR into the stratosphere

**Comment by ChungusGamer666** [comment]
didnt mean to close it OOPS yeah no

**Comment by Lauwma** [comment]
I like this PR but not for the same reasons. What I liked with this change is that it allowed character consistency. It's weird to come up one day as a ranger and another as a mage. Character consistency is good because it allows for organic evolutions. Maybe your character is an adventurer now but after an event they're gonna become a Towner or a town guard. 

Another alternative that fixes this problem would be to make a character selection happen after you chose your subclass.

**Comment by ChungusGamer666** [comment]
Closing this PR because the dev consensus seems to be: Not good, impacts balance and incentivizes bad player behavior (conformism).
I would consider expanding class selection by some margin but this is too much.

Will reopen later if a bigger belly button (emoney or jamie) tells me to reopen it.

**Pull request closed without merging**
