### PR TITLE
Medical rework part 5 - Reworks surgery, lifewebka style

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

WIP

## Why It's Good For The Game

WIP

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
pr  sucks, close it

**Comment by CVSthePharmacy** [comment]
PR still sucks, jt close it

**Comment by CVSthePharmacy** [comment]
pr broke healing as expected, close it

**Comment by Noobetski** [comment]
best fucking PR documentation i've ever fucking seen

**Comment by CVSthePharmacy** [comment]
surgery is not period accurate, close it

**Comment by wow50000** [comment]
CVS sucks, close his mouth

**Comment by wow50000** [comment]
also this PR was hella fun to play with

**Comment by ChungusGamer666** [comment]
writing an actual pr body for this is too much work

**Pull request merged**
