### PR TITLE
Bans the bloodstains and chairs from talking SHIT as maniac

### PR DESCRIPTION
**Pull request by WindowTalents**
NOTE: EDITED FOR CLARITY SORRY FOR TRYING TO BE 2 GOOFY.

Cleans up the bad dialogue that would literally get me banned (or at least PQ nuked) if I typed them in roleplay and pressed enter.

## About The Pull Request
Does above.

## Why It's Good For The Game
Ban the bloodstains for talking shit!

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
"The next time I roll this extremely rare antagonist, I do NOT want to fucking see this shit ingame. :)"

Don't pr things because you are a whiny gay baby, what the fuck is this shit?

**Comment by WindowTalents** [comment]
WHINY GAY BABY LOL

What? LOL, do you want these lines ingame still?

**Comment by ChungusGamer666** [comment]
Talking with Emoney about it, overall this PR weirds me out

**Comment by WindowTalents** [comment]
Hey man, I'm sorry if it weirds you out?

I literally, just wanted to kill these lines, so then people could come in and make it lore friendly?

Want me to just reword them? It was NOT meant to be whiny, I was trying to be a bit silly about something I thought... most people did not like in the 'script' LOL!

**Comment by ChungusGamer666** [comment]
Ok so I just wanna make one thing clear, I don't want PRs whose justification is solely "This content creeps me out or makes me uncomfortable", this is what bothers me about this PR, I can see some valid concerns with these lines but otherwise this is weird

**Comment by ChungusGamer666** [comment]
Most of these lines are ok to be removed, the ones i want to stay I will just add back instead of blabbering

**Review by ChungusGamer666 — CHANGES_REQUESTED** [review]
You removed closing tags on this json file and left an extra comma, this will actually not interpret properly when the game calls it

**Comment by bobjension** [comment]
yooo, it's almost like psychopathy serial killers were perverted and awful awful people in real life

**Comment by WindowTalents** [comment]
AIGHT JUST TO BE CLEAR GUYS.

I literally just, wanted to remove lines I would get BANNED for fucking saying in the game.

None of this shit makes my "whiny gay baby" eyes burn. IT ACTUALLY DOES NOT CREEP ME OUT EITHER I JUST THINK THEY ARE FUCKING STUPID. I literally just thought this would be so obvious I could be SILLY in the fucking description about it. I will edit it to be concise in a moment, and make sure people are aware - that no, I was not trying to actually state "AAAAA MEIN FUCKING LIBRUL EYES!" lmfao.

Whiny Gay Baby is the FUNNIEST "insult" I have heard in a long time bro, I just want you to know that made me laugh my fucking ass off.

**Comment by pilotmans** [comment]
Yeah I agree, these lines do need to be removed for their sadistic/guro/erp nature.

**Review by pilotmans — APPROVED** [review]

**Pull request merged**
