### PR TITLE
Grand reformation pt1 of 20.

### PR DESCRIPTION
**Pull request by Stagrawl**
## About The Pull Request

Adds Druid(ess), kicks Dendor and Noc out of the church except for Templars.

Maps in Druid spawn, increases acolyte slot by 1.

Church can now only be Pestra / Astrata, I'll come up with unique roles for these later but it's not a priority.

Druid is just a bog-dwelling Dendorite.

Doesn't touch archivist.

## Why It's Good For The Game

Priest Convert Roles are now worthless bloat, slots that aren't Astrata/Pestra are actively detrimental, people don't like Nocalytes, so they've just been booted out. Clerics only now ig.

I did it. Send PR.

### CODE REVIEW

**Comment by Stagrawl** [comment]
Might change Druid spells to use Druidry, just thought I'd throw it on there now to save me a minute later.

**Comment by CVSthePharmacy** [comment]
bad pr... now church has no reason to be joined.....

**Comment by JTGSZ** [comment]
Well, new job on the actual jobs list, and you are touchin archivist without talking to the guy who fixed it up. I guess

**Comment by Stagrawl** [comment]
> Well, new job on the actual jobs list, and you are touchin archivist without talking to the guy who fixed it up. I guess


"fixed it up"

**Comment by Wintermote** [comment]
If you're looking for some additional dedicated church roles, here's a few ideas:

Caretaker of Sacred Spaces - Looks after monuments, sacred groves, temples, and relics; Both physical upkeep and performing rituals to preserve their sanctity.

Oracle or Seer - Receives and interpret visions or prophecies from the gods, possesses a scrying orb.

Wiseman or Elder & Community leader - Provides mentorship to other church roles, organizes community events, festivities, ensures the welfare of the community, helps the priest mediate disputes and gives moral and ethical guidance.

Artisan Priest - Crafts sacred religious icons, amulets, monuments, tools, and weapons with divine blessings.

Pharmacist - Performs alchemical work to create salves, potions, and cures, and cares for a small garden filled with rare plants.

Some of these I think can provide some opportunity for soft antagonism (e.g. fun); for instance, raiding the pharmacist's grove, or desecrating a sacred space so it becomes evil (or inversely, consecrating an evil space to become good).

**Comment by Warfan1815** [comment]
As a person who spent quite a lot of time in functionalising the archivist, I would prefer it if they were not made into a church role.

Their entire relationship with noc should be tenious, at best, and as a matter of fact from the beginning I should have allowed archivists to be secular and or psydon as well as noc worshippers. Any attempt to further strengthen the ties of the archivist to the church is antithetical to the entire nature of the role, and is an attempt to game-ify an inately roleplay-centric role through magical elements.

It is my opinion that you should leave the magic to the court magician, the most the archivist should ever get is fetch.

**Comment by Stagrawl** [comment]
> As a person who spent quite a lot of time in functionalising the archivist, I would prefer it if they were not made into a church role.
> 
> Their entire relationship with noc should be tenious, at best, and as a matter of fact from the beginning I should have allowed archivists to be secular and or psydon as well as noc worshippers. Any attempt to further strengthen the ties of the archivist to the church is antithetical to the entire nature of the role, and is an attempt to game-ify an inately roleplay-centric role through magical elements.
> 
> It is my opinion that you should leave the magic to the court magician, the most the archivist should ever get is fetch.

These are all discussions that took place about a week ago.

The Archivist is going to get wrapped up into magic whether it's through this or the eventual Spellscribing system.

I honestly don't know where else a Noc Acolyte would fit other than... The archives? The only thing I'd be doing is making a seperate Noccite library or shoving some bookshelves in the church.

Do you have anything constructive to offer?

**Comment by Warfan1815** [comment]
> > As a person who spent quite a lot of time in functionalising the archivist, I would prefer it if they were not made into a church role.
> > Their entire relationship with noc should be tenious, at best, and as a matter of fact from the beginning I should have allowed archivists to be secular and or psydon as well as noc worshippers. Any attempt to further strengthen the ties of the archivist to the church is antithetical to the entire nature of the role, and is an attempt to game-ify an inately roleplay-centric role through magical elements.
> > It is my opinion that you should leave the magic to the court magician, the most the archivist should ever get is fetch.
> 
> These are all discussions that took place about a week ago.
> 
> The Archivist is going to get wrapped up into magic whether it's through this or the eventual Spellscribing system.
> 
> I honestly don't know where else a Noc Acolyte would fit other than... The archives? The only thing I'd be doing is making a seperate Noccite library or shoving some bookshelves in the church.
> 
> Do you have anything constructive to offer?

No need to get hostile, I'm simply saying that the archives should not be made into a place of magic, it should be for lore, history, and roleplay. To magically game-ify such a place undermines much of its roleplay.

Yes, you could get away with making a magical library in the church, or using the magical library in the wizard's tower, its undeniable that if you magic-ify (and game-ify) the archives as they stand a facet of roleplay will be lost.

I believe that both spellscribing system and this PR should have no effect on the archives as is.

**Comment by ophaq** [comment]
I like the druid idea as long as they get to keep their Dendor spells (and maybe some new cool ones) and if they aren't locked to adventurer roles.

**Comment by Stagrawl** [comment]
> I like the druid idea as long as they get to keep their Dendor spells (and maybe some new cool ones) and if they aren't locked to adventurer roles.

Yeah they would have kept dendor spells and eventually gotten some druidic stuff. Would have been a church role.

I'm not working on anything vaguely related to this until everyone has their shit together and stops flip-flopping and wanting to be argumenatitive 24/7 though.

**Comment by CVSthePharmacy** [comment]
pr successfully atomized

**Comment by Tipy1802** [comment]
I don't get why the archivist would get noc spells or be an acolyte... he is just a librarian, not a holy man. Sure he indeed fits the themes of noc but so does the court mage or really any character that you make that is an intelectual. That's just being a regular follower, miracles are reserved for people of the faith like clerics, acolytes, templars and priests... there is nothing holy about an archivist

I also do not understand why the archivist will be tied to magic in the future. That is what the court mage is for, the keep does not need a second and lesser court mage 

I believe it is much better to keep miracles to the church, arcane magic to the mages and the archivist as a regular record keeper. It is a clear distinguish that makes a lot of sense thematically and gameplay wise allows all three parties to have their own unique niches

**Comment by Stagrawl** [comment]
> I don't get why the archivist would get noc spells or be an acolyte... he is just a librarian, not a holy man. Sure he indeed fits the themes of noc but so does the court mage or really any character that you make that is an intelectual. That's just being a regular follower, miracles are reserved for people of the faith like clerics, acolytes, templars and priests... there is nothing holy about an archivist
> 
> I also do not understand why the archivist will be tied to magic in the future. That is what the court mage is for, the keep does not need a second and lesser court mage
> 
> I believe it is much better to keep miracles to the church, arcane magic to the mages and the archivist as a regular record keeper. It is a clear distinguish that makes a lot of sense thematically and gameplay wise allows all three parties to have their own unique niches

Oops. Let me edit the description of this.

Regardless, half of what you're complaining about has nothing to do with me. Take it up with relevant parties.

**Comment by CVSthePharmacy** [comment]
> > I don't get why the archivist would get noc spells or be an acolyte... he is just a librarian, not a holy man. Sure he indeed fits the themes of noc but so does the court mage or really any character that you make that is an intelectual. That's just being a regular follower, miracles are reserved for people of the faith like clerics, acolytes, templars and priests... there is nothing holy about an archivist
> > I also do not understand why the archivist will be tied to magic in the future. That is what the court mage is for, the keep does not need a second and lesser court mage
> > I believe it is much better to keep miracles to the church, arcane magic to the mages and the archivist as a regular record keeper. It is a clear distinguish that makes a lot of sense thematically and gameplay wise allows all three parties to have their own unique niches
> 
> Oops. Let me edit the description of this.
> 
> Regardless, half of what you're complaining about has nothing to do with me. Take it up with relevant parties.

you're making the PR, so you're getting the lashes

**Pull request closed without merging**
