### PR TITLE
historically accurate town guards (erase women from the game)

### PR DESCRIPTION
**Pull request by EnzoSeptum**
## About The Pull Request
Makes a realistic change and stop women from being guard cuz it makes no sense

## Why It's Good For The Game
I cringe when I see female guard

### CODE REVIEW

**Comment by EnzoSeptum** [comment]
this is my first ever pr

**Comment by EnzoSeptum** [comment]
nvm i fucked up this, will try later

**Comment by hivemuscle** [comment]
no.

**Comment by Yellows91** [comment]
Maintainers, send him to the necra void

**Comment by Real-MAGNUM** [comment]
This will likely not get merged. Bogguard are a peasant army, all-inclusive due to how often they die. They will recruit literally anyone.

**Comment by EnzoSeptum** [comment]
> This will likely not get merged. Bogguard are a peasant army, all-inclusive due to how often they die. They will recruit literally anyone.

Bog guard makes sense and they can be adventurer. But town guard and sheriff makes no sense

**Pull request closed without merging**
