### PR TITLE
emotes-pitch-fix-1.0

### PR DESCRIPTION
**Pull request by armorheart**
Experimental! This is an poor amateur attempt to fix the EMOTE PITCH to normal. Characters should no longer speak in high pitched retard emotes. Changes value ive researched from 200 to 100.

Not sure if this actually works. got help from coderbus.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
end of an era

**Comment by Wintermote** [comment]
Thank God

**Comment by Real-MAGNUM** [comment]
I want this back to normal. We'll have a voice selector eventually. 

Testmerging.

**Comment by Real-MAGNUM** [comment]
Doesnt seem to work. I'll test locally some time.

**Comment by emoats18** [comment]
THE HIGH PITCH VOICES ARE STAYING I THINK THEY ARE UNIQUE AND FUNNY

**Pull request closed without merging**
