### PR TITLE
Rng Beggar

### PR DESCRIPTION
**Pull request by Osmos123**
## About The Pull Request
Furthers the RNG theme for beggar, now there is sucky stats and less sucky. 

## Why It's Good For The Game
Beggar mains can somewhat do shit now.

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Based alert.

**Comment by BadAtThisGame302** [comment]
The beggar buff we did not need.

**Comment by zakanater19** [comment]
would be nice if the RNG went into the negatives too

**Comment by Real-MAGNUM** [comment]
Yeah, I suggest making the RNG go into the negatives as well.

**Comment by ChungusGamer666** [comment]
god no

**Pull request closed without merging**
