### PR TITLE
Make adminwho an admin verb

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

someone made this slop code for not letting people use the adminwho verb, why not just make it an admin verb

i guess they made it like that beacuse they wanted admins to be able to use it while being deadmin so i made it like the readmin command it appears if you deadmin

## Why It's Good For The Game

fixes slopcode

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
So does this allow normal players to see/use adminwho or not? My eyes dont work right.

**Comment by BlueMemesauce** [comment]
Basically it just hides it from non admins

**Comment by Real-MAGNUM** [comment]
Testmerged

**Comment by Real-MAGNUM** [comment]
image

**Comment by Real-MAGNUM** [comment]
Holy shit that's big. 4k monitors are genuinely griefing via hardware.

**Comment by BlueMemesauce** [comment]
Seems like you don't have the rights? but the second message is redundant

**Comment by Real-MAGNUM** [comment]
Yeah it's just because I pressed it twice. That's what came up during deadminned. It was working previously, meant to clarify.

**Pull request merged**
