### PR TITLE
Wrestling changes and fix

### PR DESCRIPTION
**Pull request by Bakeun0**
## About The Pull Request
As it is now, wrestling is near non-functional, with resist chances always being near-max, and punishes players with a chance to stun them for even trying to grapple. The purpose of this PR is to at least have it in a working state before adding any new wrestling-related features.

How it works:

- The difference in strength between attacker and defender modifies your resist chance by 10.

- The difference in wrestling skill reduces resist chance penalties from being aggro grabbed or prone. (more penalty types to come).

-  Wrestling skill also determines the minimum chance for the defender to break out of an aggressive grab. The base is 70 for passive and 50 for aggressive. which is reduced by having a higher skill than the defender, but cannot be increased. 
- This minimum chance prevents high strength chars from easily and always winning if they manage to grab you, but allows them to easily resist grabs themselves.

- Made changes to the struggling mechanic for attempting to upgrade a passive grab into a aggressive one. The chance to be stunned is much lower - unless the defender is also grabbing you as well, in which case it is the same as before.

- Failing to upgrade a grab also stuns the defender for half the duration. the overall stun duration is reduced.

## Why It's Good For The Game

Having an entire game mechanic be almost unused is a waste. These changes should get it working as it's supposed to.

Also, you can now groin twist people with 100% more effectiveness.

### CODE REVIEW

**Comment by EnzoSeptum** [comment]
Please add wrestling training I beg you. It is realistic to wrestle with the homies and get better at takedowns and shit

**Comment by Bakeun0** [comment]
> Please add wrestling training I beg you. It is realistic to wrestle with the homies and get better at takedowns and shit

That'll almost certainly be added however I'm waiting to see how skill training will be changed. If there's no change soon then i'll probably start with making grab resists increase the skill.

In the meantime, i'll be looking towards fixing the weird untethering bug that happens when you pull someone that is diagonal to you.

**Comment by Osmos123** [comment]
Wowza, can't wait to try this on my nudist dwarf. Could you also adjust the stun when ramming into a target? Usually what happens is the target gets downed but they can still move, while you who successfully charged into them gets stunned and cannot move. I think this relates to the wrestling as typically wrestling characters will have the constitution/strength to do this and pass the checks.

**Comment by Zebraman** [comment]
Remove nudist if you want to merge this, or ppl will just go kill themselve in the wood to become stupidly op wresting zombie (which they already do)

**Comment by Red-Honk** [comment]
Bakeun0 I am pretty sure that's less of a bug and more of a "feature" due to things not having the ability to move in a x fashion instead only relaying on a + access, so, dragging things in a diagonal manner confuses it.

**Comment by Bakeun0** [comment]
> Bakeun0 I am pretty sure that's less of a bug and more of a "feature" due to things not having the ability to move in a x fashion instead only relaying on a + access, so, dragging things in a diagonal manner confuses it.

This is definitely what's happening, but the bug that I'm referring to is what I noticed while testing on a private server - that there is some system in place for attempting to drag things diagonally alongside you, but for some reason cuts off after the first step.

**Comment by Bakeun0** [comment]
> Remove nudist if you want to merge this, or ppl will just go kill themselve in the wood to become stupidly op wresting zombie (which they already do)

Nudist class should be more of a challenge than it already is, rather than being monk+. Other changes i'm considering is removing the wrestling skill when transformed into a zombie or adding an attack cooldown after someone breaks free of your grab.

**Comment by Yellows91** [comment]
Will the 'Nosegrab' trait that Knights/King/Lord of heartfelt has remain or be removed following this fix?

**Comment by Bakeun0** [comment]
> Will the 'Nosegrab' trait that Knights/King/Lord of heartfelt has remain or be removed following this fix?

Probably just removed from heartfelt since it's an adventurer class, and the most likely to turn into a zombie.

**Comment by CVSthePharmacy** [comment]
> Will the 'Nosegrab' trait that Knights/King/Lord of heartfelt has remain or be removed following this fix?

what the fuck is a nosegrab trait

**Pull request merged**
