### PR TITLE
new buildings and tents, replaces the building next to the garden

### PR DESCRIPTION
**Pull request by Deroh-Ra**
Add's buildings to an otherwise nothing area, allowing people to set up shitty shops and crappy dense homes you'd expect in a urban environment.
cca954e5f4bd9cad3851331e0e2474ab-1
ae5f096e82d4441e9160af23274879a8
af37ca33047ff720e2811a98e248597e
ac5a50182acda32de5f85f723fd2fbf3

### CODE REVIEW

**Comment by Deroh-Ra** [comment]
@Real-MAGNUM won't let me click on the Reviewers button or I'm just stupid, either way here.

**Comment by Gyrandola** [comment]
WE GOT DORMS BOYS

**Comment by TheManWithNoHands** [comment]
Great design, just WAY too expensive for peasant.
As Explained in detail on the discord.

**Comment by bowlofcereal** [comment]
he fell down the rabbit hole holy shit

**Comment by Deroh-Ra** [comment]
e61f43ac9b258248efec43b87995bb15
1f7dc765e907bf46fcd95872dd47052f
e584060f4a7a6111d039557c25493e0e

did as NHC asked

**Comment by ophaq** [comment]
I think you should try putting some railings on the sides of the tables and hearths on the 3 wide entrance sides so it looks more divided and prevents people from walking into the hearths as much. Otherwise, this is cool. Also I think 4 hearths is too much, the two near the tables could be removed and the top can be shared.

**Comment by Deroh-Ra** [comment]
fcadd887763b7f5fc66fcd39a8ddafd5

**Comment by TheManWithNoHands** [comment]
> fcadd887763b7f5fc66fcd39a8ddafd5

Try the other railings we have. The ones used just north of the kitchen at the stairs. They look a bit better from the sides.

Also the four knigth statues are a bit too much. Keep in mind for what the area is, and for whom. Dont fall down the decorating rabbit hole. Its something you will have to grip your nose from time the time yourself. 

But overall much better. Looks like it would fit on a renecance fair.

**Comment by TheManWithNoHands** [comment]
If ya need a hand to resolve the mapmerg problem, ring me. Finally figured out how to fix the branch when that happens.

**Comment by Deroh-Ra** [comment]
Seems good now.

**Pull request closed without merging**
