### PR TITLE
Shitters have fallen. Gorillions must play Lunatic.

### PR DESCRIPTION
**Pull request by efzapa**
## About The Pull Request

Changes max PQ of Lunatic from -50 to -15. Anyone below -15 *should* be locked to playing only Lunatic.

## Why It's Good For The Game

Discussion was had about the previous number and i came to the agreement that my initial number of -50 was pretty dumb as 90% of people would be banned before they even approach that. This should cover and filter out alot more shitters and force them to actually are pee back to a reasonable PQ level until they hit Prisoner (Or hostage, whatever PR is merged first)

### CODE REVIEW

**Comment by Xkallubar** [comment]
Lunatic gaming. Maybe I should make a second account to grind -15 PQ specifically to play lunatic for shits and giggles.

**Comment by BlueMemesauce** [comment]
just remove this fucking shitty role why are we encouraging people to be shitters

**Comment by efzapa** [comment]
> just remove this fucking shitty role why are we encouraging people to be shitters



> just remove this fucking shitty role why are we encouraging people to be shitters

Aren't you literally the one making prisoner even worse of a punishment role.
They already got released like 75% of the time and now you encourage it, THEN say we need to remove this role.

Letting shitters into roles that literally GET STAT BUFFS is a one way road to having the same issue you would have had if you would have just not had prisoner at all.

**Comment by BlueMemesauce** [comment]
> > just remove this fucking shitty role why are we encouraging people to be shitters
> 
> Aren't you literally the one making prisoner even worse of a punishment role. They already got released like 75% of the time and now you encourage it, THEN say we need to remove this role.
> 
> Letting shitters into roles that literally GET STAT BUFFS is a one way road to having the same issue you would have had if you would have just not had prisoner at all.

yes, because shitty roles that are for shitters are stupid and encourage people to be shitters. We should be encouraging roleplay, not shitters

**Comment by efzapa** [comment]
> > > just remove this fucking shitty role why are we encouraging people to be shitters
> > 
> > 
> > Aren't you literally the one making prisoner even worse of a punishment role. They already got released like 75% of the time and now you encourage it, THEN say we need to remove this role.
> > Letting shitters into roles that literally GET STAT BUFFS is a one way road to having the same issue you would have had if you would have just not had prisoner at all.
> 
> yes, because shitty roles that are for shitters are stupid and encourage people to be shitters. We should be encouraging roleplay, not shitters. Ban shitters, dont encourage them to be shitters.

Forcing people to roleplay or get fragged is one punishment option to the admins
nowhere in this PR am i removing or discouraging the usage of bans, it is simply an option for shitters to redeem themselves through sane RP

**Comment by BlueMemesauce** [comment]
didnt you see that one guy who said he would make an alt account to be a shitter and become lunatic in purpose? we shouldnt have exlcusive roles for shitters that encourage people to be shitters. it shouldn't be an option.

**Comment by efzapa** [comment]
> didnt you see that one guy who said he would make an alt account to be a shitter and become lunatic in purpose? we shouldnt have exlcusive roles for shitters that encourage people to be shitters. it shouldn't be an option.

if we have people in the community that would be willing to be shitters for the sake of getting a role, then they should be stuck to that role

I don't see the problem, those ARE the type of people we are trying to weed out

**Comment by BlueMemesauce** [comment]
but its not weeding them out its encouraging them
weeding them out is banning them

**Pull request merged**
