### PR TITLE
Guard rework: The Chungus Cut - BAILIFF CAN REQUEST LAWS NOW

### PR DESCRIPTION
**Pull request by ChungusGamer666**
### REDOING https://github.com/Blackstone-SS13/BLACKSTONE/pull/858 WITH NO SLOP

Reworks the guards to make them more akin to a professional garrison.

Changes sheriff to Captain of the Guard.

Changes castle guard to man-at-arms.

Changes town guard to watchman.

Disables veteran and village elder.

Gives guards better equipment and makes their loadouts make more sense.

Buffs chain coif to 35 melee resist.

### MAN-AT-ARMS
331197695-f543a814-eb68-4b15-8f35-05321a908c26
331197708-57344172-a76a-4ff7-b028-2055870f4954

### WATCHMAN
331197711-78fe6349-1e7f-4534-a7bc-c32925561e9c
331197714-0a8c465b-71bb-499f-9f11-4fcf968b9c80

### CAPTAIN OF THE GUARD
image
image

### BAILIFF EXPANSION
Bailiff can request the king to do law changes now!
image

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
> give men at arms polearms!!! theyd use polearms!!!!!

doing it

**Comment by wgtjunior743** [comment]
very nice but why is the village elder removed he is just an old man

**Comment by Yellows91** [comment]
Are we giving the guard their gorgets back? I'm not sure but I think the chain coifs are still weaker than their original.

**Comment by YosemiteYam** [comment]
"War has always been a constant of your life, and you always chose the side of defense and justice. You rose up through the ranks as a guardman and you're now the head above all of them. Lead and train your men to defend the kingdom and maintain the peace. Recruit those who you believe capable of aiding the Kingdom against offenders and pushing the tides of the kingdom's battles in your favor..."

This flavourtext emoney wrote for Captain is some ESL garbage. What does “choose the side of defense” even mean. The rest of it sounds like a 14 year old trying to find big words and ending up sounding retarded. “Aiding the kingdom against offenders” lmao.

Just edit the sheriff flavourtext abit and add what duties you think are needed to that instead of this butchering and simplification of the veterans flavourtext.

**Comment by Yellows91** [comment]
Chungus one more point.

The new helmet that the castle guard has might be weaker than their original. If so can we get those two swapped. if not that's cool as well.

**Pull request merged**
