### PR TITLE
Wizard Spells / Noc T3 Spell / Dwarf Armor

### PR DESCRIPTION
**Pull request by Sarkness**
## About The Pull Request

WIZARDS REJOICE!! THE NEW ERA OF SPELLS ARE HERE!! INTRODUCING 3 (5 SOON) NEW SPELLS AND 1 ACOLYTE SPELL FOR ALL OF US TO ENJOY!! 
THE NEW SPELLS FOR WIZARD:
- Flame Blade, A Fire Sabre that burns targets on hit.
- Truesight, a spell that allows to see anyone around you, even behind walls!
- Arcaneum, a spell similar to the scrying orb, in which you can examine players now!
(Mage variants: Blindness and Invisibility)

Additionally, exclusively, dwarves armors are now INCLUDED IN GAME! (Soon Elves/Humans)

## Why It's Good For The Game

MORE STUFF FOR WIZARDS BECAUSE THEY CURRENTLY SUCK AT THE MOMENTT. (Sorry)

### CODE REVIEW

**Comment by Sarkness** [comment]
Also forgetting that the new Noc Spell being Moonbeam.
Similar to D&D, you charge the spell and it unleashes a heavy damaging blast of moon ray on the target.

**Comment by YosemiteYam** [comment]
Doesn't a  spell that does the same thing as scrying orb take away from how valuable a competent court mage with a scrying orb is? And won't it allow basically every rebel mage/attacker to be able to spy on publically known figures like the king whrever they go with little trouble?

**Comment by CVSthePharmacy** [comment]
sarknuts at it again, keep at it

**Comment by Sarkness** [comment]
> Doesn't a spell that does the same thing as scrying orb take away from how valuable a competent court mage with a scrying orb is? And won't it allow basically every rebel mage/attacker to be able to spy on publically known figures like the king whrever they go with little trouble?

The Arcaneum spells isn't Scrying orb. It only tells you the equipment of the player like if you were in front of him.

**Comment by OrbitalParadise** [comment]
Giving true sight and invisibility to the same class seems a little strong, ppl don't enjoy the necros blind

**Comment by CVSthePharmacy** [comment]
NO SARKNUTS WHY

**Pull request closed without merging**
