### PR TITLE
Gives the garrison a facelift, Adds a sewer entrance, and touches up the Wizards tower.

### PR DESCRIPTION
**Pull request by dunsel-hordon**
## About The Pull Request
Went through and cleaned up the flooring and some walls of the garrison. Also cleaned up the roof and made it into a training area. Adds a sewer entrance outside the garrison. Touches up flooring and some wall inconsistencies in wizard tower.

## Why It's Good For The Game
Makes it look less like shit was just spliced together and a junkie got ahold of a mapping tool. More sewer entrances so guards will actually patrol it. Same with wizard tower.

### CODE REVIEW

**Comment by TheManWithNoHands** [comment]
Pics or it didn't happen

**Comment by dunsel-hordon** [comment]
Just look under checks and click map bot

**Comment by TheManWithNoHands** [comment]
> Just look under checks and click map bot

oh i didnt know it could do that. Very usefull info

**Comment by Real-MAGNUM** [comment]
Conflicting.

**Pull request closed without merging**
