### PR TITLE
Adds a salt mine

### PR DESCRIPTION
**Pull request by dunsel-hordon**
## About The Pull Request
Adds a salt mine simple as. Added some decrepit roads to it.

Screenshot (45)

### CODE REVIEW

**Comment by Gyrandola** [comment]
Why it's good for the game?

**Comment by Real-MAGNUM** [comment]
You used mapmerger. This wont be merged till it's reverted. Ask me on discord and I'll help you.

**Comment by TheManWithNoHands** [comment]
> Why it's good for the game?

You salty? :)

**Comment by dunsel-hordon** [comment]
The game needs more SALT!

**Pull request merged**
