### PR TITLE
Seamstress Gaming

### PR DESCRIPTION
**Pull request by Stagrawl**
## About The Pull Request

Seamstress gaming begins now. Adds the Seamstress, a talented towner sewer with some other handy crafting skills.

Additionally, adds like... Two crafting recipes before I gave up entirely on trying to balance that shit.

## Why It's Good For The Game

First of a few fem roles I plan to introduce to steer slots away from adventurers and more into town, also rounds out Misogyny Lore by keeping women in respectable professions.

I'm gonna try introduce mouth+eye sewing once the medical changes have calmed down a little and with some guidance from Abraxas on how shit should work.

### CODE REVIEW

**Comment by Stagrawl** [comment]
I tested this shit, wtf.

**Comment by ophaq** [comment]
This is great. Now we just need a shepherd that herds sheep for wool and meat and fends off volfs with their bell staff.

**Comment by lovegreenstuff** [comment]
might want to consider giving them 1 level of carpentry to build a loom

**Comment by BlueMemesauce** [comment]
why not just call it tailor and make it gender neutral

**Comment by wow50000** [comment]
yeah seamstress is fucking useless, any high int role can just make the clothes or any low int role can grind tailoring

**Comment by immortalartisan** [comment]
> why not just call it tailor and make it gender neutral

why is miner male only?

**Pull request merged**
