### PR TITLE
Tunics

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
adds tunics to the game
long shirts
barp
thanks to Près de l'oiseau for the sprites

yes, it has sleeves when you turn around
yes, it is fitted for dwarves
intended to be given to towner roles to maximize town drip

## Why It's Good For The Game
drippin

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Looks awesome. How do you plan to implement these items? Tailoring? Dye? On-spawn?

**Comment by Takyon69** [comment]
Onmob looks good but can you please post the inventory icon sprite?

**Comment by cornercube** [comment]
> Looks awesome. How do you plan to implement these items? Tailoring? Dye? On-spawn?

for now, I will give them to towners to wear in place of shirts
eventually, I plan to make them producible in the same way as shirts



> Onmob looks good but can you please post the inventory icon sprite?

barp

**Review by Takyon69 — APPROVED** [review]
Sprites check out.

**Comment by ChungusGamer666** [comment]
fix conflicts, this is good shiiiiet

**Pull request merged**
