### PR TITLE
[QOL/Balance] Dynamic job slots for Adventurers (with cooldown), Pilgrim loadouts more consistent and worth picking (READ DESC!)

### PR DESCRIPTION
**Pull request by ariaworld**
Adventurer slots are now dynamic: Locked at 75, once a player playing as one departs to the underworld, effectively clearing that job slot to be picked by someone else.
Adventurers unlock an extra choice of class to pick from every 5 positive PQ points the player has.

Pilgrims' loadouts have been tweaked, to make them more worthy to pick: All of them have a self-defense knife to also use as a survival tool, + a flintsparker to ignite things.

Adventurers' loadouts were inconsistent, some had satchels, others didn't, now all Adventurers/Pilgrims have standard satchels (some Pilgrim roles that had backpacks still keep them as it's important for their occupation).

QOL: Lets some weapons like polearms and spears fit on back slots.

This PR's objective is to make sure Pilgrims are worthy of being picked as a job (with better equipment), while also making Adventurers more consistent between themselves, with the ability of death unlocking the role for someone else to play.

### CODE REVIEW

**Comment by bobjension** [comment]
argh
dynamic..... you just GIVING PEOPLE FREE RESPAWNS as adventurer, this is also gonna encourage people to wait in the lobby waiting for a adventurer role to pop up, instead of choosing pilgrim or beggar, or towner for that matter.

**Comment by YosemiteYam** [comment]
This is...a very bad change. Bob is right, please do NOT allow free respawns. The seventy five hard cap isn't enough, its SEVENTY FIVE adventurers. Already we have people that are veterans of the forest and dodging tdmers enough that MOST of these seventy five high skilled, good geared adventurers with NOTHING to do but combat arrive in town safely.

This basically encourages endless tdm, metagrudgery, imbalance AND fucks the economy with a never ending supply of adventurer armors, weapons etc. The next time I need to arm my men with crossbows I'll just wait for one dude to die and respawn as rogue 5 times over and just send one of my guys that memorized the forest spawns to pick them up.

Also if you want to tweak adventurer/pilgrim loadouts PLEASE reduce the mammon they spawn with. Because of near limitless adventurers and limitless pilgrims theres mammon inflation going on and makes the economy worthless except for craftsmen.

**Comment by YosemiteYam** [comment]
Also polearms spears shouldn't be equippable on your back. You think people carried their 8 foot long halberds on their back? Its cool to see people have to hold them in their arms, same with spears

**Comment by wow50000** [comment]
could you make the blacksmith pilgrim spawn with the two coal and one iron instead of one coal an iron and a flint ?

**Pull request merged**
