### PR TITLE
Music-Rework-Update-1.5

### PR DESCRIPTION
**Pull request by armorheart**
updates music based on player feedback and desires. 

all music is now tuned to -10 DB, to reduce the volume., future music updates will be tuned on exact same pregorative. Music now fits more in town to the dark theme of the town, and is also more ambient. combat music remains same, but quieter. Other town music and general single music file is replaced with fine score from ATRIUM CARCERI.

In next update. 1.6, i will talk to community extensively about the castle music, and see if we want a change. If there isnt any problem with castle OST and nothing is desired to be changed, wilderness music is going to be discussed and applied for 1.6.

SUMMARY :
- Size of files has been optimized without quality loss
- All music in this update and future update, will have - 10 DB volume.
- Raised baseline 44khz to 48khz
- 128 KBPS standardized quality.

### CODE REVIEW

**Comment by BigBigga** [comment]
nice. i love the combat one

**Review by Kush1Push1 — COMMENTED** [review]
Combat music is gold

**Comment by bobjension** [comment]
combat music is great

**Comment by BigBigga** [comment]
wait, can you make the combat music the weird_combat one? its so good. maybe make it so it has a small chance of triggering idk

**Comment by armorheart** [comment]
> wait, can you make the combat music the weird_combat one? its so good. maybe make it so it has a small chance of triggering idk

thats a big change, are we sure? 
The band is called heilung, the same band that made music for Hellblade 2. 
They're great. but i'd need to ask community again if they agree with something like that.

**Comment by ChungusGamer666** [comment]
so how is this goin

**Comment by AlexMorgan3817** [comment]
it could be better music files to have normalized +0 DB, and changed in code by need

**Comment by BigBigga** [comment]
is this getting merged? we desperately need some good music

**Comment by Real-MAGNUM** [comment]
Please resolve conflicts or reopen pr. :(

**Comment by Real-MAGNUM** [comment]
This is going to go stale soon.

**Comment by Deroh-Ra** [comment]
dead pr?

**Pull request closed without merging**
