### PR TITLE
bogguard slots 20 to 10

### PR DESCRIPTION
**Pull request by bobjension**
far far too many for a "milita"

### CODE REVIEW

**Comment by thefirstjeb** [comment]
literally every round start with 1~3 bogmen only, this makes no sense also boglands is giant and the most dangerous shit while bogmen are really lacking skills so why low it?

**Comment by bobjension** [comment]
> literally every round start with 1~3 bogmen only, this makes no sense also boglands is giant and the most dangerous shit while bogmen are really lacking skills so why low it?

is bro schizo? https://github.com/Blackstone-SS13/BLACKSTONE/pull/760#issue-2291203747

**Comment by thefirstjeb** [comment]
> > literally every round start with 1~3 bogmen only, this makes no sense also boglands is giant and the most dangerous shit while bogmen are really lacking skills so why low it?
> 
> is bro schizo? [#760 (comment)](https://github.com/Blackstone-SS13/BLACKSTONE/pull/760#issue-2291203747)

you implying i'm literally need to look all guit changes? the game needs a fucking changelog

**Comment by bobjension** [comment]
you boggers have gotten too content with your cozy slots and now upgraded skills it's time for you mfers to learn SOME pain

**Pull request merged**
