### PR TITLE
Might fix day/night cycles

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request

Trying to fix day/night cycles

## Why It's Good For The Game

shit's broken

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Desperately accepting help.

**Comment by Real-MAGNUM** [comment]
This only fixes the bog, I still dont know why the town isnt lighting up the same way.

**Comment by Osmos123** [comment]
Awesome change can appreciate the scenery, the bandits will love this

**Comment by Real-MAGNUM** [comment]
blackstone.dmm is a merge of bog.dmm and roguetown2.dmm. Currently unfinished, and unused.

**Pull request merged**
