### PR TITLE
Making STR not adding dozens of damage

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Same as title

## Why It's Good For The Game
Balance

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
shit pr, someone close this

**Comment by hivemuscle** [comment]
buff other stats, make them more useful, so no one will want to just max str

**Comment by kacperpl1234pl** [comment]
bad pr removes fun

**Comment by Wintermote** [comment]
Strength is too good, puts every other stat to shame honestly.

**Comment by ChungusGamer666** [comment]
Good change but I am afraid of merging it

**Comment by CVSthePharmacy** [comment]
unmerge

**Pull request merged**
