### PR TITLE
Adventurerslimitclasses

### PR DESCRIPTION
**Pull request by bobjension**
Really fucking weird there can be a infinite amount of paladins, clerics, rogues, mages, vaqueros, female mages, etc

however, the two classes that I think are really fucking basic are warrior and ranger, so they stay infinite

also adds 1 single slot to crusader, just for someone to dick around with him.

### CODE REVIEW

**Comment by Wintermote** [comment]
I don't mind a limit (although I don't think it's necessary at all), but I don't want to select a character who's thing is being a cleric, only to find out there are no more cleric slots and now I have to play whatever else that doesn't fit that character at all.

If it's going to be like this, then the slots should be selected at round start rather than just being "adventurer" so I can select a different character to play a different (open) job instead.

**Comment by BlueMemesauce** [comment]
this would make half the server warriors or rangers

**Comment by bobjension** [comment]
I'll reopen it soon.

**Comment by Ambrose997** [comment]
Imo really bizarre to limit them en masse like this. The main issue is having a potential for like 50 rogues or something retarded. 

Limit them, and limit others if the need arises (which is already a principle you guys usually follow).

**Comment by CVSthePharmacy** [comment]
just forget this PR, community hates it

**Pull request closed without merging**
