### PR TITLE
Adds a howl emote to bandits

### PR DESCRIPTION
**Pull request by MickDick1**
## About The Pull Request

Just a basic howl emote for bandits.

## Why It's Good For The Game

I thought it would be neat to have. Helps bandits coordinate without clear leadership and help to identify each other in the dark and other murky situations.

If someone thinks they have a better sound file or want to add variations, so we don't hear the same one over and over go ahead.
I'm not sure how well it propagates out of vision range or how to mess with that either. I'd like it to be pretty far reaching so bandits can locate each other at some distance.

https://streamable.com/t60wf1

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
This is marked as a draft. Is this ready?

**Comment by MickDick1** [comment]
> This is marked as a draft. Is this ready?

I just wanted to give people time to add or do things if they wanted. It's good to go.

**Comment by Real-MAGNUM** [comment]
unmark as draft for merge

**Comment by MickDick1** [comment]
Actually I will tidy something up.

**Comment by MickDick1** [comment]
Deleted duplicate sound file and put it in the sound/villain/ folder since it's a villain only sound anyway. This seems more proper to me but if someone knows better say so.
Lower cased the howl print log. Works locally.

**Comment by MickDick1** [comment]
I'll get back to it later when I figure out how to print directional chat logs for it out of sight. It's just meh without that.

**Comment by CVSthePharmacy** [comment]
> I'll get back to it later when I figure out how to print directional chat logs for it out of sight. It's just meh without that.

the fate of forever closed prs

**Pull request closed without merging**
