### PR TITLE
Adds kings soldiers

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Reduces castle guard from 8 to 4, adds 12 soliders that spawn in the throne room, they have worse gear but have manor guard keys, they are commanded by the sheriff but ultimately are the kings men to send on expeditions outside of the keep, the castle guard and knights will be sufficient to defend the castle walls

## Why It's Good For The Game

Let's the king extend his influence without having to send his castle guard out of the castle, PQ requirement is only 1 for soldiers right now but i can change anything if you want me too, tested and working locally

Outfit

Ingame
2 - Copy

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
that is a HARD removal of castle guard slots, change it to at least 6 or keep it at 8. otherwise someone close this pr please

**Comment by zakanater19** [comment]
> that is a HARD removal of castle guard slots, change it to at least 6 or keep it at 8. otherwise someone close this pr please

Well, the thought is this will make it so the king does not have to send his castle guard out of the keep to fight, but sure im open to ideas on this PR

**Comment by CVSthePharmacy** [comment]
> Reduces bog guard number from 20 to 10 as per magnum request

an average of 14 guard die in the initial bandit attacks including the bog master, let's keep it at 12

**Comment by zakanater19** [comment]
Raises PQ for soldier from 1 to 4

**Comment by BigBigga** [comment]
It feels weird to have the Sheriff command professional army soldiers when they're just supposed to be a chief of police for the entire town guard. Maybe have them answer to the King and Knights only? Since that's realistically who they'd answer to.

**Comment by zakanater19** [comment]
> It feels weird to have the Sheriff command professional army soldiers when they're just supposed to be a chief of police for the entire town guard. Maybe have them answer to the King and Knights only? Since that's realistically who they'd answer to.

Sure, changing it now

**Comment by Osmos123** [comment]
I would recommend giving them bogguard level of skill. Starting with expert-master sword skill is very strong for a soldier. I would imagine them to be more expendable to throw away in expeditions. It would also encourage training.

**Comment by zakanater19** [comment]
> I would recommend giving them bogguard level of skill. Starting with expert-master sword skill is very strong for a soldier. I would imagine them to be more expendable to throw away in expeditions. It would also encourage training.

Training is going to be getting a nerf PR soon, that is confirmed

**Comment by TheManWithNoHands** [comment]
The castle is already overfilled. It does not fit so many more people.
If you want to add 8 more people to the castle, you need to first make the castle bigger.
It in general needs to be made bigger. There are currently three beds for all castle guards. 

The current castle guards and knigths pluss all the advisors to the king already fill the throne hall up.
Where do you slap 8 more people into? Where are they supposed to be most of the round if not send out.
Are they supposed to be also in the throne room and repalce the castle guards that are in it? 
Those are most of the time half the castle guard, so about 4. And if the soldiers are more then 4 in your pr.

Dont merge this until the castle has more breathing room, because rigth now it only overfills the castle even more then it already is.
Ignroing the job bloat.

**Comment by zakanater19** [comment]
> The castle is already overfilled. It does not fit so many more people. If you want to add 8 more people to the castle, you need to first make the castle bigger. It in general needs to be made bigger. There are currently three beds for all castle guards and knights.
> 
> The current castle guards and knights pluss all the advisors to the king already fill the throne hall up. Where do you slap 8 more people into? Where are they supposed to be most of the round if not sent out? Are they supposed to be also in the throne room and replace the castle guards that are in it? Those are most of the time half the castle guard, so about 4. And if the soldiers are more than 4 in your pr.
> 
> Don't merge this until the castle has more breathing room, because right now it only overfills the castle even more than it already is. Ignoring the job bloat.

Castle is big enough for more people for sure, but this PR makes it less, because soldiers will be outside of the keep most of the time doing stuff for the king

**Comment by Real-MAGNUM** [comment]
> Training is going to be getting a nerf PR soon, that is confirmed

true, but take them down only one tier anyways.

**Comment by zakanater19** [comment]
> > Training is going to be getting a nerf PR soon, that is confirmed
> 
> true, but take them down only one tier anyways.

alright

**Comment by Real-MAGNUM** [comment]
> > Reduces bog guard number from 20 to 10 as per magnum request
> 
> an average of 14 guard die in the initial bandit attacks including the bog master, let's keep it at 12

Yeah I changed my mind, do 15. Bogmaster can recruit more.

**Comment by Real-MAGNUM** [comment]
> Don't merge this until the castle has more breathing room, because right now it only overfills the castle even more than it already is. Ignoring the job bloat.

Working on a remapping but it'll take time. Not opposed to shoving these in potentially with half slots (5) and reducing the _eventual_ max slots to 10

**Comment by zakanater19** [comment]
> > Don't merge this until the castle has more breathing room, because right now it only overfills the castle even more than it already is. Ignoring the job bloat.
> 
> Working on a remapping but it'll take time. Not opposed to shoving these in potentially with half slots (5) and reducing the _eventual_ max slots to 10

just tell me what you want me to do

**Comment by Real-MAGNUM** [comment]
> just tell me what you want me to do

Set the soldier count to 6.

**Comment by zakanater19** [comment]
> > just tell me what you want me to do
> 
> Set the soldier count to 6.

done

**Comment by BlueMemesauce** [comment]
My ideas:
Make the soldiers outside of the keep. 
Give them an encampment on the outside of town
Add a general noble
The king commands the soldiers but through the chain of command of the general

**Comment by zakanater19** [comment]
> My ideas: Make the soldiers outside of the keep. Give them an encampment on the outside of town Add a general noble The king commands the soldiers but through the chain of command of the general

might be done longterm depending on how this goes as a test

**Comment by kacperpl1234pl** [comment]
it would be cool if they get a leader role like army capitan

**Comment by Gyrandola** [comment]
I get your idea but here's whats gonna happen: both castle guards and king soldiers are going to leave the keep anyway.
Also, medieval Europe had very few if any professional standing armies, they were made of seasonal levies. The concept of soldier will come later.

**Comment by BlueMemesauce** [comment]
Yea soldiers don't make much sense unless there's a war

**Comment by YosemiteYam** [comment]
A few points,

Firstly I don't mean to be rude but this pr doesn't make much sense. Adding soldier roles implies that there is a war-level threat in every round that requires a specific role with such a large amount of slots in it to deal with, when in reality nearly every round the majority of conflict against the crown comes from his own vassals/soldiers/church rebelling. There is no PVE to speak of to use these soldiers for, there is no outside power besides a siege gamemode that is being worked on to send these guys against, they're just weaker keep guards with no war, who will leave and fuck around worse than the guards because they will literally have nothing to do or create the conflict themselves by just existing.

Secondly, the king already has soldiers, ALL of the guards in their totality represent the royal army, the keep guard being the creme of the crop, the town guard and bog guard area literally the bulk of the royal army engaged in peace-time duties. You wouldn't have an additional professional force ontop of these guys just being..soldiers. 


> > It feels weird to have the Sheriff command professional army soldiers when they're just supposed to be a chief of police for the entire town guard. Maybe have them answer to the King and Knights only? Since that's realistically who they'd answer to.
> 
> Sure, changing it now

Thirdly concerning the chain of the command, the Sheriff IS the head of the entire military, not just the town guard. I'm unsure why people think he just commands the town guard when multiple role texts say that they all answer to the Sheriff who is meant to be the head of military and the general in times of battle. It literally says in the bogmasters text that he answers directly to the sheriff, the sheriff himself spawns in the throne room with the other keep guard with more gear and skill than all of them to signify his authority, in every other iteration of Roguetown his role was explicitly to command ALL the guard, it would be odd to add in a bunch of soldiers that already have nothing to do, and not put them under the command of the sheriff. The King and knights cannot have direct command over an army, they literally are meant to stay in the keep, the knights are there to guard the king and aren't officer roles. If this pr DOES get passed then it should make it clear that the chain of command is with the Sheriff that can actually lead them on the field as opposed to the immobile king and his bodyguards. 

Finally, with all the points above I really don't see the point of this pr, in essence we have a royal army of the combined guards who are peacetime soldiers anyway and theres nothing to send 'expeditions" against in the game that all the other roles can't do already. If there ever was a rare out-of-game threat that requires a shitton of people then the crown can roleplay raising levies, hiring adventurers/mercenaries, or literally using the join townguard/bogguard spells they have to conscript men to bolster their forces if their already combined 40 men aren't enough. I'm unsure why we would just hand them that piece of roleplay instead of letting people "prepare" themselves. I would suggest to close this PR and just make a separate one to limit bog guard to 15 people instead, we really don't need the rest of this.

**Comment by Real-MAGNUM** [comment]
> Thirdly concerning the chain of the command, the Sheriff IS the head of the entire military, not just the town guard.

Sheriff should probably just be renamed to guard commander eventually, honestly.

**Comment by Real-MAGNUM** [comment]
I'm also mixed on this PR. It's essentially turning guard into soldiers for a purpose they're already capable of. I'm willing to testmerge it to see how it goes for a little, but I'm not committing to this one.

**Comment by Real-MAGNUM** [comment]
> My ideas: Make the soldiers outside of the keep. Give them an encampment on the outside of town Add a general noble The king commands the soldiers but through the chain of command of the general

I'm more inclined for something like this, a chain of command that's more than a bunch of more men sitting in the keep. New map could support this fairly well.

**Comment by JTGSZ** [comment]
Closing on the criteria of the following:
1. new job - no mechanics attached aka bloat role
2. everyone is already the kings soldiers if they fuckup then thats part of intrigue.

**Comment by CVSthePharmacy** [comment]
> The castle is already overfilled. It does not fit so many more people. If you want to add 8 more people to the castle, you need to first make the castle bigger. It in general needs to be made bigger. There are currently three beds for all castle guards and knights.
> 
> The current castle guards and knights pluss all the advisors to the king already fill the throne hall up. Where do you slap 8 more people into? Where are they supposed to be most of the round if not sent out? Are they supposed to be also in the throne room and replace the castle guards that are in it? Those are most of the time half the castle guard, so about 4. And if the soldiers are more than 4 in your pr.
> 
> Don't merge this until the castle has more breathing room, because right now it only overfills the castle even more than it already is. Ignoring the job bloat.

castle roles are just left out, nobody plays them anymore

**Pull request closed without merging**
