### PR TITLE
Fixes the railings which are messed up and the wrong way and adds three more lights to areas which were completely dark

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Adds two standing fires on the Western Manor courtyard where there's virtually no light next to the hedge maze, also a single torch in the underground basement next to the Merchant.

Now, I fixed the railings on the stairs which were all fucked up and looking the wrong direction and the wooden borders on the western bridge, the second floor of the Church, the Inn and alot of other places where the railings were fucked.

## Why It's Good For The Game

No more ugliness and more lights.

### CODE REVIEW

**Comment by Wintermote** [comment]
Great change. I don't know why this got messed up in the first place honestly. Resulted in some silliness like being able to walk off the 2nd floor of the inn because the railings were floating in the air instead of on the walkway.

**Comment by Real-MAGNUM** [comment]
Map conflicts.

**Comment by BadAtThisGame302** [comment]
> Map conflicts.

I'll get around to fixing them after Easter.

**Comment by Real-MAGNUM** [comment]
I fixed these in my own PR.

**Pull request closed without merging**
