### PR TITLE
Disables knights, castle troops and nobles from joining peasant rebels

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Title

## Why It's Good For The Game

The kings personal garrison now have more cohesion

### CODE REVIEW

**Comment by BigBigga** [comment]
i mean ok? its not like any of those roles you mentioned NEED to be rebels to kill shitty kings/supervisors anyway.

**Comment by zakanater19** [comment]
forgot sheriff lol

**Comment by YosemiteYam** [comment]
This is pretty limited for what is a larger problem for rebellion game mode = you can recruit anyone starting from the beginning of the round and those who do not accept the call for rebellion do not get an indicator or advantage to not accept it. Someone that denied joining the rebellion should get something to show him as a loyalist or be unable to join for future requests.

Second this is pretty limited , knights and guards rarely join rebels anyway although atleast this will theorically stop them from starting as rebel leaders. You should instead bar everyone in the court faction (court magician, Lord Hands, Sheriff, Steward) along with all the soldiers (castle/town guard and ESPECIALLY gatemaster) from not being able to convert to rebels, since they are representative of the Head/Sec roles and all of them are supposed to rolewise be completely loyal to the throne barring aspirants. Otherwise this doesn't change much.

**Comment by Autisem** [comment]
keep in mind roundstart roles for prince and few other high roles to become the rev leaders.

**Comment by zakanater19** [comment]
left the bogs alone since bog guard are historically rebellious for funny reasons

**Comment by zakanater19** [comment]
> keep in mind roundstart roles for prince and few other high roles to become the rev leaders.

i don't see why the prince would be a peasant rebel, he would be an aspirant

**Comment by Osmos123** [comment]
This is good, it is retarded when a knight joins in. This is a PEASANT rebellion, not just a rebellion but a PEASANT rebellion. ALL NOBLES GET THE GUILLOTINE A knight is supposed to be the most loyal ride or die follower of the King (big reason why they get full armor and skills/priveleges). One exception is I would honestly allow the sheriff to join the rebellion though, they tend to be justice focused and also spawn with objectives of overthrowing the king alot. I've seen a lot of sheriffs play the good guy and help overthrow the king whenever they enact a genocide of elves and such.

**Comment by YosemiteYam** [comment]
> This is good, it is retarded when a knight joins in. This is a PEASANT rebellion, not just a rebellion but a PEASANT rebellion. ALL NOBLES GET THE GUILLOTINE A knight is supposed to be the most loyal ride or die follower of the King (big reason why they get full armor and skills/priveleges). One exception is I would honestly allow the sheriff to join the rebellion though, they tend to be justice focused and also spawn with objectives of overthrowing the king alot. I've seen a lot of sheriffs play the good guy and help overthrow the king whenever they enact a genocide of elves and such.

Thats the thing though is the objective they get to overthrow the king is related to the aspirant gamemode, which is completely different to the rebellion gamemode and involves replacing the sheriff just becoming the king, wheres rebellion is a peasant rebellion usurping the entire system. Allowing sheriff to be both just fucks the system.

**Comment by Autisem** [comment]
> > keep in mind roundstart roles for prince and few other high roles to become the rev leaders.
> 
> i don't see why the prince would be a peasant rebel, he would be an aspirant

ah fair, tho I think aspirants use the same code so this will effect them too

**Comment by zakanater19** [comment]
> > > keep in mind roundstart roles for prince and few other high roles to become the rev leaders.
> > 
> > 
> > i don't see why the prince would be a peasant rebel, he would be an aspirant
> 
> ah fair, tho I think aspirants use the same code so this will effect them too

Good point, hopefully this won't break aspirant

**Review by Real-MAGNUM — APPROVED** [review]
Looks good to me :)

**Comment by CVSthePharmacy** [comment]
ok so this works but the thing is, THEY CAN STILL ROLL REBEL LEADER

**Pull request closed without merging**
