### PR TITLE
Disallows female sheriff

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Makes sheriff a male only role

## Why It's Good For The Game

about tree fiddy

### CODE REVIEW

**Comment by hivemuscle** [comment]
no more strong woman?

**Comment by Ambrose997** [comment]
Or don't be a cringe motherfucker?

**Comment by Gyrandola** [comment]
This PR verges too much on the "just because incel" side. Removing female squires made sense but this doesn't.

**Comment by Alibouk1** [comment]
Local chud seething he got his groin twisted off.

**Comment by Osmos123** [comment]
based

**Comment by Ambrose997** [comment]
If you merge this you're pathetic. No real reason for this

**Comment by Yellows91** [comment]
I don't see the reasoning behind removing female sheriffs since technically its just a guard who is higher up.

Knights/Squire makes sense, this does not.

**Comment by Ambrose997** [comment]
> I don't see the reasoning behind removing female sheriffs since technically its just a guard who is higher up.
> 
> Knights/Squire makes sense, this does not.

Women dont get promotions /s

**Pull request closed without merging**
