### PR TITLE
Drifter Queue + Triumph Buy System + Class Handler

### PR DESCRIPTION
**Pull request by JTGSZ**
The fourth or fifth return of the gigaslop PR.
Adds Drifter Queue

Adds Triumph Buy System
Reworks Triumph Saving

Adds Class Handler + Menu
Reworks Class Category Sorting

### CODE REVIEW

**Comment by JTGSZ** [comment]
Idk about that, I will still probably have to do a marathon of bugfixes

**Comment by CVSthePharmacy** [comment]
wtf is drifter queue

**Comment by Wozzy09** [comment]
> wtf is drifter queue

i geuss something like migrant wave in lifeweb

**Comment by erik30015** [comment]
oh the triumph nuke...

**Comment by JTGSZ** [comment]
Yea, I still gotta do some work on this tho

**Comment by JTGSZ** [comment]
undergoing more fixes/adjustments/examinations of pre-existing code

**Comment by pilotmans** [comment]
> > wtf is drifter queue
> 
> 
> 
> i geuss something like migrant wave in lifeweb

The hell is that?

**Comment by Coastfront** [comment]
For if the sun has no light to speak for it; I want to express this opinion to ensure that nobody else fails to.

Whilst the idea of a triumph store is neat; I do not think it is an intelligent idea to add triumph-buys that allow you to affect/fuck with other peoples experiences in a round.
From a roleplaying perspective; Having everyone forced for a round to play a massively difference race, is sucky if they were planning on roleplaying a specific aspect of their chosen race.

From a gameplay perspective; Being able to just say 'Fuck you' to the server when you hit 180 triumphs & burn it all, is shitty. 

This is derritive & removes agency from other people, because one player farmed a billion triumphs on bandit/by idling.


The idea is not deeply flawed, nor terrible; However the current prospective implementation of it it, is at best short sighted; & At worst, actively self-sabotage.

The most beloved tools are ones that don't call for a fee in anothers blood. Literally just don't add triumph buys that allows one player to exert a massive amount of control over other peoples character choice/personal triumph economy & its not a terrible idea.

**Comment by WindowTalents** [comment]
> Literally just don't add triumph buys that allows one player to exert a massive amount of control over other peoples character choice/personal triumph economy & its not a terrible idea.

Yes, **basically this**, just let the buys be something we all are excited to see when we see them. Sorta like when people use those items on TF2 that actually affect the entire server and give everyone a fun experience - without destroying the nature of the game.

People should feel like it is a cool reward when a player uses that, not "I'm gonna skip this round now." which WILL happen if you add shit like "everybody humen cause I said so lol" which is genuinely the dumbest thing I can even think of man.

People like me literally play elf and dark elf - BECAUSE it is harder to survive. I don't play bitchass humen for a reason lol.

I'd *much* rather see stuff like "if people all put in X triumphs then Y will happen to everyone" if you wanna do that kinda shit. Like a VOTE almost - for a TOTAL ROUND CONVERSION. Shit like "if 100 are donated then we are ALL dorfs" cause AT LEAST THEN it won't happen fucking BACK TO BACK TO BACK like it will once people get triumphs lol.

>This is derritive & removes agency from other people, because one player farmed a billion triumphs on bandit/by idling.

You also need to remove *collapse because I am in the top ten from literally idling and using *collapse :)

I like to do silly RP, so triumphs have actually been a negative experience for me SINCE THE START OF THIS - due to how fucking stupid it feels to even lose them at all for *engaging with the game*. SS13 is literally about FAILURE to CREATE FUNNY DRAMA - it's the only game I know of where people fucking up IS THE GAMEPLAY lol. So I immediately stopped caring about them when IT WOULD PUNISH ME FOR PLAYING BRAVELY and now I'm in the top 10 so - basically, we aren't saying this shit to you because we HATE the idea - it's because it adds nothing but problems, honestly.

And, also:

Why is the destruction of the adventurer role so critical to your development for this server? Do you genuinely want to sabotage the health of the server with a slow ass 6 player at a time wave of people? Give us roundstart drifters then dude, like 20 of them, then fucking throw the waves in. This seems like the most BORING change to the game ever, this is gonna make the bog suck at roundstart lol. Also what the fuck is the deal with everyone HATING the players who CREATE MORE DRAMA AND ENGAGING MOMENTS THAN *ANY* OF OUR ANTAGS? Our antags fucking suck, that's literally why I am not happy with you trying to ruin the one role that CAN create fun moments BECAUSE they aren't IMMEDIATELY gonna murderbone unless they are an actual antag too... lol.

This is like sawing off a table's leg cause you didn't like the wobbly table, and then you just prop that shit up on a folding chair - that is how ass backwards this change feels. It does not make sense for this PVP orientated BARELY medium RP server, to remove such an important element of the system. I don't even agree that it's MRP, this shit is LRP WITH SOME FUN RP SOMETIMES man.

I AM NOT A CODER, YOU HAVE MADE GREAT MENUS AND COOL STUFF HERE THAT I LIKE AND I DON'T WANT TO SHOOT DOWN - PLEASE DO NOT FUCKING RUIN THE FUN WITH IT THOUGH WE ARE BEGGING YOU! D:

I think the drifter menus and that stuff is super cool, I am LITERALLY only "complaining" (constructive criticism) about the balance perspective of things, because I WANT to see this in the game IN A GOOD STATE - if not simply for the fact that you have worked very hard on it, _and I know and respect that._

Best of luck. :)

**Comment by WindowTalents** [comment]
After playtesting this for a bit, I can absolutely see the promise of a good feature that this could be. Stuff like spawning all players nearby to intend for them to work together, is a great touch.. It also does not prevent roundstart antag "adventurers" (which was a huge issue I was worried about, Lord of Heartfelt MUST be allowed to be maniac/rebel lol)

I would highly recommend adding something in this that removes the *collapse (and *faint apparently) emote from "knocking you unconscious". I am unsure if removing the "knock dood out" lines would cause any issues, so, if you can possibly consider it - I GENUINELY think that the "requirement to sleep in a bed to get a triumph" is essential for this to work in the long run.

Pretty cool stuff, I just wish there was a "re-roll" button again. Even if it was kinda superfluous it would feel neat to be able to hit "no these all sucked" at least once per spawn. (Unless I am dumb, and it shows them all lol.)

**Pull request merged**
