### PR TITLE
Limit Death Knight summons, remove necromancers

### PR DESCRIPTION
**Pull request by NGGJamie**
## About The Pull Request

Limits the death knight summons to 3 to prevent spamming them. Removes necromancers from the game until they can be reworked.

## Why It's Good For The Game

Requested by @emoats18

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
don't merge this

**Comment by Real-MAGNUM** [comment]
Hoping this gives someone a reason to finally turn necromancers into an antag. #861 could be implemented into this somehow, maybe.

**Comment by TheManWithNoHands** [comment]
> Hoping this gives someone a reason to finally turn necromancers into an antag. #861 could be implemented into this somehow, maybe.

Am working on a map for them already like the vamp lord has.

**Comment by CVSthePharmacy** [comment]
> Hoping this gives someone a reason to finally turn necromancers into an antag. #861 could be implemented into this somehow, maybe.

i told you to not merge this wtf

**Pull request merged**
