### PR TITLE
Inquisitor Stuff

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Everyones favorite witch hunter has been given a sack to shove on peoples heads

## Why It's Good For The Game

Psydon only gave the gift of sight to the WORTHY.

sackked

Credits to Takyon for making the obj sprite less ugly

### CODE REVIEW

**Comment by Takyon69** [comment]
Can you post images of any sprite changes?

**Review by Takyon69 — APPROVED** [review]
Sprites check out. Up to other devs if they wanna merge this.

**Comment by Gyrandola** [comment]
I believe the sack should remain unique to the dungeoneer/executioner. it existed for a reason. An agent of the inquisition would have zero reason to wear one.

**Comment by Gyrandola** [comment]
I think the sack shouldn't be the same one worn by the dungeoneer,

**Comment by ChungusGamer666** [comment]
epic conflicts

**Comment by SELFHELL** [comment]
mfw. I love sprite conflicts

**Pull request closed without merging**
