### PR TITLE
Lumberjacking and Mining skills 

### PR DESCRIPTION
**Pull request by wgtjunior743**
## About The Pull Request

- Lumberjacking skill added, mining skill activated with new calculation, lumberjack also has new calculations, both also have their xp gain, lumberjacking only gains xp on wood and mining only gain xp on rocks.

- Added these skills to miners, carpenters, woodcutters and mason, as they are specific skills i don't think everyone should get them.

- Cutting wood and mining nerfed for those without the skill, you will need atleast 2 lumberjack or 2 mining to go back to what it was, but those above 2 will mine/lumberjack faster, this need TM, it could be too op for people like LMiner, i know the economy functions alot around wood right now but in the future adventures will get dungeons, they should not be mining or lumberjacking for money, they are built for combat.

- I already tested and yes these skills don't affect combat damage values.

- At the moment it just reduces the amount of hit is necessary to break stuff, but after a Test Merge if it is too weak, i could add the speed change associated to the skill.

## Why It's Good For The Game

Make Woodcutters and Miners have real skills besides just having the names, make so people play more these jobs, LMiner is now actually very useful, progression towards skills even tho it is slow, still viable to get expert/master on these skills from zero, more logic into the game.

### CODE REVIEW

**Comment by wgtjunior743** [comment]
yeah i got no idea how to remove the mining.dm without running into a error

**Comment by dunsel-hordon** [comment]
neat bout time we got an actual mining skill and a reason to be a miner

**Comment by ophaq** [comment]
ABOUT DAMN TIME DWARVES CAN FUCKIN MINE FASTER. All dwarves should start out with novice mining by default.

**Comment by CVSthePharmacy** [comment]
lumberjacking off

**Comment by CVSthePharmacy** [comment]
> ABOUT DAMN TIME DWARVES CAN FUCKIN MINE FASTER. All dwarves should start out with novice mining by default.

at that point give them novice in all smithing types too

**Comment by wgtjunior743** [comment]
> also pr sucks, make it go back to normal at the first level

lvl 2 is 250 xp, if you got 10 int, you will get 2 per hit so about 125 hits on trees and you will get to that level by cutting 25 trees if you take 5 hits to break them, nobody is born a lumberjacker and that type of skill is not simple as strong axe on tree, this way adventures and non lumberjackers search other ways to make money rather than simple cutting some wood in 5 seconds and getting 200 mammon in 15 minutes, the xp gain could be increased but nerfing these activities for people without that profession is important to the game.

We already got sewers for combat people, in the near future we will get dungeons, there are other ways to make money.

**Comment by CVSthePharmacy** [comment]
> > also pr sucks, make it go back to normal at the first level
> 
> lvl 2 is 250 xp, if you got 10 int, you will get 2 per hit so about 125 hits on trees and you will get to that level by cutting 25 trees if you take 5 hits to break them, nobody is born a lumberjacker and that type of skill is not simple as strong axe on tree, this way adventures and non lumberjackers search other ways to make money rather than simple cutting some wood in 5 seconds and getting 200 mammon in 15 minutes, the xp gain could be increased but nerfing these activities for people without that profession is important to the game.
> 
> We already got sewers for combat people, in the near future we will get dungeons, there are other ways to make money.

hey cocksucker that's 25 fucking TREES, I'D HAVE TO CLEAR OUT THE ENTIRE FOREST SURROUNDING THE TOWN FOR LEVEL 2

**Comment by wgtjunior743** [comment]
> > > also pr sucks, make it go back to normal at the first level
> > 
> > 
> > lvl 2 is 250 xp, if you got 10 int, you will get 2 per hit so about 125 hits on trees and you will get to that level by cutting 25 trees if you take 5 hits to break them, nobody is born a lumberjacker and that type of skill is not simple as strong axe on tree, this way adventures and non lumberjackers search other ways to make money rather than simple cutting some wood in 5 seconds and getting 200 mammon in 15 minutes, the xp gain could be increased but nerfing these activities for people without that profession is important to the game.
> > We already got sewers for combat people, in the near future we will get dungeons, there are other ways to make money.
> 
> hey cocksucker that's 25 fucking TREES, I'D HAVE TO CLEAR OUT THE ENTIRE FOREST SURROUNDING THE TOWN FOR LEVEL 2

i guess you are going to need to suffer and hit the tree ONE more time to get your sweet 6 logs from the big tree, you will get carpal tunnel just from that grinding! better activate your auto clicker!

**Comment by dunsel-hordon** [comment]
why is this not merged yet...

**Pull request merged**
