### PR TITLE
Overhauls the young roles into "Apprentices" and rewords a lot of stupid shit that should never have been here. (Check my code, otherwise merge ready.)

### PR DESCRIPTION
**Pull request by WindowTalents**
## About The Pull Request
Fixes a BUNCH of stuff that I found in several of the "young" roles.
Rewords stuff, changes some stat levels, and NERFS THE SHIT out of Orphan and Shophand (wtf guys)
I typed a much more thorough post and then hit BACK like a FOOL so this is what you GET:

1. nerfs some bullshit with the orphan and shophand
2. small buffs to the places that felt really weak, overall just balance that feels more "fun" and/or fitting
3. fixes the wording on orphan so they aren't "children" (they never were, they were always 18 lmao)
4. fixes the clerk having to pay taxes (and renames Noble-Blooded to Noble and changes the description to explain its use)
5. makes the prince/princess have more balanced skills between them, while still making them remain gender diverse
7. a totally absolutely good idea addition to the races allowed to play prince that is not inspired by my own elf shittery (surely)

(I kept notes in the commits, so check there if you want more info. Please leave comments below on what you think.)

## Why It's Good For The Game

_OTHER THAN PRINCE (and the girl one)_ - the point of these roles is to actually teach players new ways to do stuff in a low stress environment where you might even get a player who cares about you enough to explain how stuff works! The simple concept of "an apprentice" inspires this in most players of SS13, who usually like to teach the whacky game with its many stupid layers to people who ask them what the fuck is going on in the funny room they just walked into.

_ONLY_ the royal heirs should be treated like RP roles, the rest should be used specifically to train people on what to do IN THE REAL ROLE which is THE POINT. We need people to play the real roles, not shitty "young" versions of them. This should incentivize that, and so I have reduced the maximum slots on almost all of them. Infact, players who see those roles SHOULD KEEP IN MIND that they MIGHT be a new player - and treat them accordingly. No this does not mean "be nice" to them, this specifically means crank up whatever BEST roleplay machine you got and make them like it here lol.

Squire, for example, shouldn't be picked over and over by a player - that player should fucking pick KNIGHT or MAN AT ARMS once they feel better at the combat. Even though Squire is much more of an RP role than the others - it should not be treated as one. Just pick "adult" and roleplay as a young knight bro, c'mon please lol.

Prince mains fighting for 2 slots (between 10 prince rollers) is ALREADY silly enough lol.

The "final goal" of working on these roles is eventually changing the wording of "Youngfolk" to say something like "Apprentices" but that is a different PR for another time.

Yes obviously, if you want to lynch me for that one line in the prince.dm - I *can remove it* but come on that would be so funny lol.

### CODE REVIEW

**Comment by Stagrawl** [comment]
I’ll review this ASAP when I get home if no one else picks it up.

**Comment by WindowTalents** [comment]
> I’ll review this ASAP when I get home if no one else picks it up.

No rush. I won't be able to change anything for a few hours.

**Comment by Tipy1802** [comment]
Elf prince good, keep it

**Comment by Tipy1802** [comment]
> fixes the wording on orphan so they aren't "children" (they never were, they were always 18 lmao)

What do you mean orphans were never children? An orphan is BY DEFINITION a child. Nobody calls an adult an orphan, once you are an adult you are no longer dependent on your parents and as such if they are alive or not is not important to your societal role. In fact under the natural flow of life an adult will lose his parents before he dies...
image

**Comment by WindowTalents** [comment]
@Tipy1802
Because *THIS* shit you just did is getting old.
I am *SICK* of arguing with people about the fucking *SEMANTICS* of this issue.

Seriously, holy shit.
The ultimate goal is to literally remove "children" from the setting so this shit is STOPPED.

*BUT* the goal OF *THIS PR* is to FUCKING CHANGE THINGS FOR BETTER BALANCE - and you are hyperfocused on one thing I wrote that as a joke inside parenthesis. 

Fuck's sake man. Please give me input on the actual changes and not the joke I wrote about "they were always 18 lol".

**Comment by WindowTalents** [comment]
I believe it is time to completely disable Orphan, honestly.

It's a shit role, play a Beggar. Stop roleplaying as CHILDREN/MINORS thanks it genuinely fucking sucks.

It upsets me so fucking much how much *we talk about this topic, and how much drama this has caused.*

Give me a bit to edit this, please do not merge it.

**Comment by WindowTalents** [comment]
Teenager is now "Young Adult" and "Youngfolk" on the Late Join menu is now "Apprentices"

I have asked OOC about this several times, and many have said that sounds like a good idea.

Changes NOTHING in the code, because that's stupid don't do that. This JUST changes what players can see.

Also, please note that this is not meant to remove your ability to roleplay as "a young person" in this setting. I am aware of how fun that struggle can be as a character, so just... do it and don't say that you're a minor basically lol.

I will see if adding "young" to beggar (so you can still be an "orphan") will cause issues, but it should be do-able.

**Comment by WindowTalents** [comment]
I don't care to fix the elf shoes. I will just get new shoes ingame.
Merge ready, or tell me what to change if you want it changed.

I am *fucking done* being treated like shit for trying to do FREE LABOR to fix THINGS THAT SHOULD HAVE BEEN FIXED MONTHS AGO and have caused the community to be dragged into the fucking dirt. "WE" genuinely deserve to be seen as shitheads, we are.

Other than fixing THIS PR, I am done helping out. I guess I forgot that people who play SS13 are fucking shitty people who don't respect the concept of having fun with another person online in an ancient game that barely has 2,000 total players each day lol.

Here's a social skill that will help you in life: "Simply ignore the parts about people you don't like, if you can."

Thanks to everyone who has been cool about the changes I have made, *every single one* has been to increase the overall fun and experience for the people who play here - with no other goals or incentives besides that.

"If it's not fun, why bother."
-Nintendo guy IN RESPONSE to TLOU2's devs saying "We don't say FUN here."

**Comment by WindowTalents** [comment]
> Please atomize balance changes into it's own PR. All it does is make it harder to have your other changes merged.

The balance changes are literally half of my PR. Less people in these roles unless they are learning, is the goal.

This is a DESPERATE fix attempt at making people play the actual roles we have. This is a nerf to young roles for that reason.

If there's specific shit that needs adjustment, tell me specifically what it is, on what line and what exactly you see as bad about it.

I will check this PR every few hours. Until it closes or is merged. Then I am done editing this codebase for good. o7

**Comment by SpaceSlug2** [comment]
baby rage

**Comment by Tipy1802** [comment]
Please calm down. There is no need to get overly emotional over something this petty. If you submit a change you should be ready to expect people voicing their concern.

I fully disagree with the design direction of this PR. Firstly Blackstone having teenagers is not an issue. I don't know why you are acting like this is destroying blackstone and only this PR can fix it. I have not seen any drama about Blackstone having teens, only about Ratwood having teens, instigated by Emoney. For obvious reasons, it is an 18+ ERP furry server with rape. Meanwhile on Blackstone there is no danger of an adolescent partaking in sexual intercourse and as such there is no problem with teenagers existing. The ONLY person I have seen bring up blackstone's teens is the host of Ratwood in an attempt to deflect the accusations of teenagers and pseudo-teenagers on his own server, ignoring the glaring different natures of the two servers. Additionally, I do not believe it wise to validate his deflections and saying that somehow we were in the wrong all along when we were not. The best way to kill this non-existant drama is to just not bring it up...

Removing orphans sucks because it is a different rp vibe from a beggar and some people enjoy that, I know of at least two people who regularly play orphan.

I do not see it an issue for more experienced players to play the child roles. Yes they are mainly learning roles but they also act like assistants to the grown up roles, which is good for both rp and gameplay. Steward and merchant benefit of this a lot. It doesn't make people treat youngfolks worse or not teach them because in all of my experience playing as one the adults were happy to show me the ways of the trade. And the teen roles certainly don't get flooded with good experienced players anyways as they often have open slots left... and if it was a problem why would you be decreasing the job slots anyways? That would only cause for less newbies to be able to play the learner roles.

> Teenager is now "Young Adult"

Considering Emoney and the upper echelons of staff criticised Ratwood for doing the exact same thing it is unwise to use the term "young adult". Besides it is redundant as "adult" is already 18-30, the age of young adults and "middle aged" is 30+. I know that in the leaked VC Emoney (at least I think it was him, could have been somone else from backstone) said that in america young adult means teenager but if so, then that means you are fixing nothing to americans and to others you are adding a confusing redundancy. 

Also I just like elf prince, dunno what's the issue with it. C'mon one of the elf hair styles is literally called "princely"

**Comment by WindowTalents** [comment]
Fix it yourselves then lol.

Also elf prince has always been in the game, I added dwarf here to be silly.

I genuinely don't have time for this.

**Comment by WindowTalents** [comment]
@SpaceSlug2 
> baby rage

Ahem, okay pedophile. :^)

For your sake, this is average adult human rage at a group of shitty people like you.
I will not do free work for fuckheads that are totally fucking vile, bro this shit shouldn't be an argument.

BUT YET?
We got leaked VCs and dumbass shit over semantics yet again making us ALL look like shit for even taking part in this - fuck off lol.

**Pull request closed without merging**
