### PR TITLE
KENSHI TRAINING

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Training dummies only train you up to NOVICE.
You can only train up to ATTACKER SKILL - 1, AKA a legendary trainer only gets you up to master skill level.

## Why It's Good For The Game

Grindcucks need to man the fuck up, dude.

### CODE REVIEW

**Comment by TheManWithNoHands** [comment]
Based and Kenshi pilled

**Comment by BigBigga** [comment]
baaaassed

**Comment by zakanater19** [comment]
based

**Comment by CVSthePharmacy** [comment]
shit pr

**Comment by OrbitalParadise** [comment]
BASED

**Comment by LancashireladOnGitHub** [comment]
I too am in this comment section.

**Comment by Yellows91** [comment]
General concern.

Does this ONLY affect combat or both non combat skills. This seems PERFECTLY good for combat but for non combat skills which has no real big impact in most stuff. It seems like this is bad.

**Pull request merged**
