### PR TITLE
Goblin fixes and balances

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
This should fix latejoin. Iron helmet protect their huge noses, goblin king is immune to stab crits death from being fat. Adding tanning to cook and stealth, pickpocket to all but King being so fat he is won't be able to do it as good as his brothers.
No more zombies and +1 STR as goblins with 6 STR were not intended, same with guard goblins with 7 STR.

## Why It's Good For The Game
Graggar told me to

### CODE REVIEW

**Comment by YosemiteYam** [comment]
Can you give the goblins their own language rather than use orcish? Because every round goblins are just joined by people who spawn and respawn as horcs, mitigating the low stats of the goblins

**Comment by CVSthePharmacy** [comment]
can you add some skills to adminspawned goblins? had 0 skills last time I was spawned

**Comment by Real-MAGNUM** [comment]
Skills wont go to adminspawned goblins. That's an admin issue, not a code issue.

**Comment by Real-MAGNUM** [comment]
> Can you give the goblins their own language rather than use orcish? Because every round goblins are just joined by people who spawn and respawn as horcs, mitigating the low stats of the goblins

Unfortunately no.

**Comment by Real-MAGNUM** [comment]
testmerging

**Comment by Gyrandola** [comment]
Goblin king global announcements need to go.

**Comment by panvxv** [comment]
I fixed everything, they have accent, names, proper skin names, can't roll antags like rebels, bandits, vampires, maniac.
Examine shows correct job, Goblin king has his announcement set to only goblins and other power works too.

**Comment by ChungusGamer666** [comment]
conflicts

**Comment by CVSthePharmacy** [comment]
can you rename player goblins to mind goblins, so there's a difference between the simplemobs

**Comment by Real-MAGNUM** [comment]
I dont know a word about what's happening with this PR, but make sure you're getting approval as you make changes. I'd hate to see more of your effort go to waste due to poor communication with development leads.

**Pull request closed without merging**
