### PR TITLE
The Apothecary sets up shop & map fixes, keys

### PR DESCRIPTION
**Pull request by TheManWithNoHands**
## About The Pull Request
Adds the Apothecary job in town, giving the town their own doctor now as well.
Well, more a drug store. But still.

Fixes some map problems. Missing walls wrong layers, missing walls, reducing the blacksteel armor set.

Gives people more keys. Like the queen now has her own key that lets her open her and her husbands bedroom. The king can still open it being that his key is the master key and can open everything.
Also the Court physician now spawns with their key on them.

Also gives the court phys and Apothecary combat music.

## Why It's Good For The Game
The medical system is slowly but surely getting to be a thing. Taking some pressure off the church in terms of being our "medbay".
The court physician is already there to allow players to slowly get used to it, and with this there will be a towner role for that.
Will need to be added soon anyway.

Some nice new keys to make being queen consort nicer, and also for the physician.

map fixes good.

### CODE REVIEW

**Comment by ophaq** [comment]
Would be nice to see a towner role added too or pilgrim for apothecaries. I feel that this is a bit too premature to implement though without proper alchemy mechanics and more things to grow for herbs/etc. Also the pestle and mortar is in code still but not yet implemented I think. I guess it could be added later though but for now if this gets in the game, the role may feel empty or dull.

**Comment by TheManWithNoHands** [comment]
> Would be nice to see a towner role added too or pilgrim for apothecaries. I feel that this is a bit too premature to implement though without proper alchemy mechanics and more things to grow for herbs/etc. Also the pestle and mortar is in code still but not yet implemented I think. I guess it could be added later though but for now if this gets in the game, the role may feel empty or dull.

Fair, but pretty much the same for the court phys. Was just in my backlog for a while and i thought why not put it out.

**Comment by dunsel-hordon** [comment]
whyd you delete all the /obj/structure/closet/crate/roguecloset/dark???

**Comment by TheManWithNoHands** [comment]
> whyd you delete all the /obj/structure/closet/crate/roguecloset/dark???

didnt. That where other versions of it, with diffrent variables i created in SDMM, and then deleted afterwards.

**Comment by TheManWithNoHands** [comment]
Gonna close this, made this half tired and realized it has no real purpose rigth now, while the church is the towns healer.

**Comment by TheManWithNoHands** [comment]
Gonna close this, made this half tired and realized it has no real purpose rigth now, while the church is the towns healer.

**Comment by CVSthePharmacy** [comment]
reopen

**Comment by TheManWithNoHands** [comment]
Ok, fixed and changed some stuff. With the new surgery Pr this should be good.

**Comment by TheManWithNoHands** [comment]
oh shit, i forgor something

**Comment by TheManWithNoHands** [comment]
nevermind, i need to give the apothecary the tools, wich i cant while the surgery pr is only testmerged.

**Pull request closed without merging**
