### PR TITLE
Bogtown Detached

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request

Detaches bogtown from the main town, and compresses its overall size down quite a lot without removing the previous buildings.
Made a rough path from town to bogtown so people have some sort of guidance/trade route to follow.
There are no stockpiles or shylocks in bogtown, all technology is within the actual town. Scoms still exist within bogtown. This is to promote travel via saiga/handcart to sell goods, and potential highwayman gameplay/pvp.
New mines inside of bogtown have high tier spots right away, but will get patchy fairly quickly. Lava caves are still the best high frequency area.
Main town's mine was nerfed pretty heavily to only green tier.
Town guard should probably be defending the town gate now, as well as patrolling with saigas (they have a few round start, but only bogtown can breed more round start since town has no female saiga)
Bog guard have a few saiga.

Manor walls refurbished again.
King's court slightly altered.
Added a bunch of tiny cave paths.
Fixed the excidium's outdated offset.

## Why It's Good For The Game
Bogtown has no danger, town guard are redundant with the existence of bogguard to the point noone plays them. After a town remap, they'll be patrolling the town and watching the town gate but without such an obnoxiously large area to try to cover. I know it's hard for town guard to watch the entire town, but major reworks of the map like that requires a lot of time, which will be chipped away at asap.

Bogtown is now a solid place to gain resources, but they need to be ferried through the bog. It's more likely to allow outcasts from the town due to range, and is more of an exile when the king orders you to serve the bog.

Also, bogguard have just been wandering the city. I know it's not really a mapping issue, but it's telling when bogguard are trying to enforce the town that it's getting redundant.

Experimental, do not merge. Testmerges will only happen for a few rounds at a time, probably.

z1
z2
z3
z4
z5

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Tested the changes, ready for testmerge tomorrow.

**Comment by Hmeister-real** [comment]
this is gonna be so fucking good, great work magnum <3

**Comment by CVSthePharmacy** [comment]
can you please make bog gaurds spawn in their barracks so they don't have to fucking run all the way to the bog town

**Comment by Real-MAGNUM** [comment]
> can you please make bog gaurds spawn in their barracks so they don't have to fucking run all the way to the bog town

Did you read the code? There's a new latejoin marker that's in the bog barracks.

**Comment by Real-MAGNUM** [comment]
> oh mb I only check mapdiffbot2

Ah okay, just making sure we're on the same page and I didnt miss something.

**Comment by WindowTalents** [comment]
This is seriously one of the best maps for SS13, ever. Excellent work - I genuinely am so happy to see this continue to grow better and better from where I first saw it in April.

By editing the King's Court, do you mean that you gave the 2nd Prince a chair to sit in? If not, don't. Don't ever give them a chair it is so funny having to get out a folding chair as the 2nd heir LOL.

Amazing stuff.

**Comment by Real-MAGNUM** [comment]
> This is seriously one of the best maps for SS13, ever. Excellent work - I genuinely am so happy to see this continue to grow better and better from where I first saw it in April.
> 
> By editing the King's Court, do you mean that you gave the 2nd Prince a chair to sit in? If not, don't. Don't ever give them a chair it is so funny having to get out a folding chair as the 2nd heir LOL.
> 
> Amazing stuff.

Thanks!

The only edits to the king's court were the tile patterns on the floor, and moving the pillars one block out while moving the statues to the old pillar's location, if that makes sense. It's for a more open visual channel for people waiting in line.

**Comment by Real-MAGNUM** [comment]
> this is gonna be so fucking good, great work magnum <3

Thank you so much 😌

**Comment by ophaq** [comment]
At last, I can finally establish a fortress right on top of the gateway to the town between bog and town, and have us dwarves be proper gatekeepers within the bog pass.

**Comment by MickDick1** [comment]
Really good looking. Would you consider culling the raw resources behind the town gate? There's really no reason to set up in bog town or go out of town if everything is obtainable in the 'safe' area. Make it a wasteland where everything has already been stripped feeding the town. No grasses, no bushes, no trees. If you want stuff, go outside to touch grass.

**Comment by Hmeister-real** [comment]
can you do another test merge at some point? Or just merge. current bog is becoming stale.

**Comment by Real-MAGNUM** [comment]
> Really good looking. Would you consider culling the raw resources behind the town gate? There's really no reason to set up in bog town or go out of town if everything is obtainable in the 'safe' area. Make it a wasteland where everything has already been stripped feeding the town. No grasses, no bushes, no trees. If you want stuff, go outside to touch grass.

I'll map in empty stripped out mines and stuff to represent it. Was already kinda planning on it. I dont want to alter tree generation due to how much empty space the town has at the moment, but once there's a remap it'll be reflected that way.

**Comment by Real-MAGNUM** [comment]
> can you do another test merge at some point? Or just merge. current bog is becoming stale.

Should be done with changes today.

**Comment by Real-MAGNUM** [comment]
Reopened in #1301

**Pull request closed without merging**
