### PR TITLE
Examining adventurers no longer tells you their class

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

now it just says "This is [name], the wandering [race]."

## Why It's Good For The Game

it's dumb to tell people's class
now rogues can disguise themselves easier

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
not a fan, come up with a better solution for rogues

**Comment by BlueMemesauce** [comment]
bruh what's a better solution

**Comment by Real-MAGNUM** [comment]
testmerging

**Comment by EnzoSeptum** [comment]
This is peak

**Comment by CVSthePharmacy** [comment]
unmerge due to abraxa's request

**Comment by Real-MAGNUM** [comment]
> unmerge due to abraxa's request

Decision was changed publicly last night. He already signed off on a testmerge.

**Comment by BlueMemesauce** [comment]
It's not merged, just test merged

**Comment by Real-MAGNUM** [comment]
Testmerge has been going really well. People can identify eachother most of the time if they're wearing default kits, but it's clear who's an outsider and who isnt because you can see them as a traveller, not a townie.

**Comment by pismorizzo** [comment]
Only adventurers that should be excluded from this are Lord Heartfelt and the Hand of Heartfelt, With this change theres no way to even know the titles are Lord Heartfelt since now its just Human man.

**Comment by ChungusGamer666** [comment]
Merging this, but I agree with Pismo

**Pull request merged**
