### PR TITLE
Silk dress & silk coat, add weaving recipe, add silk drop from webs, minor buff to clerk

### PR DESCRIPTION
**Pull request by Viviridia**
## About The Pull Request
- adds Silk dress (chemise) in green, white, and some pastels
Screenshot 2024-05-27 162725
inventory icon
Screenshot 2024-05-27 163431

clerk teen:
Screenshot 2024-05-27 143401

dwarfvailable (dwarf clerk teen ↓) 
Screenshot 2024-05-27 143318

https://github.com/Blackstone-SS13/BLACKSTONE/assets/169249975/ab202dfc-e203-4732-b0bd-c774edf5ad98

- adds Silk coat in green, lime(original color), red, purple 
Screenshot 2024-05-27 162938
inventory icon: 
Screenshot 2024-05-27 163338

some princess looks: 
Screenshot 2024-05-27 160234
Screenshot 2024-05-27 160222
should be dwarfvailable just  forgot to take a pic
- adds silk drop from sewer webs

https://github.com/Blackstone-SS13/BLACKSTONE/assets/169249975/1019579f-7296-40ee-bffc-edc703816be1

- minor clerk buff (just some skills)
- weaving recipe for barkeep dress, chemise and silkcoat
- sewing recipe prices

## Why It's Good For The Game

more things for the seamstress also allows her to survive in this economy, adds silk in web since web is limited anyways.

### CODE REVIEW

**Comment by Takyon69** [comment]
All sprites look good except the princess hat. It's at too much of an angle, which is understandable considering the size restriction. Only solution is to stick it on a larger 32x64 canvas.... ask a coder to help you out with it.

**Comment by Viviridia** [comment]
> All sprites look good except the princess hat. It's at too much of an angle, which is understandable considering the size restriction. Only solution is to stick it on a larger 32x64 canvas and make it a proper looking tall hat.... ask a coder to help you out with it.

Oh the princess hat is actually already a part of the game i didnt make it, I think its called a hennin in game

**Comment by Takyon69** [comment]
> Oh the princess hat is actually already a part of the game i didnt make it, I think its called a hennin in game, just used it to show how princess would look in game

Oh, fair enough then. Something I might have to look into then in the future.

**Review by Takyon69 — APPROVED** [review]

**Comment by Viviridia** [comment]
@ChungusGamer666 sorry to ping, but anything needs to be changed?, I probably shouldn't have added my clerk pr with this

**Pull request merged**
