### PR TITLE
Gives templars chain coifs and chain legs instead of tights

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

It was requested

## Why It's Good For The Game

You can put the amulet in bracer slot

### CODE REVIEW

**Comment by zakanater19** [comment]
Also gives templars pants = /obj/item/clothing/under/roguetown/chainlegs instead of tights

**Comment by panvxv** [comment]
Can we stop with buffing every role and adding more and more gear on them?

**Comment by Osmos123** [comment]
may overwrite the psicross on their neck, recommending changing its placement to wrist

**Comment by zakanater19** [comment]
> may overwrite the psicross on their neck, recommending changing its placement to wrist

Done

**Comment by Real-MAGNUM** [comment]
I'd rather have templars buying upgrades from smiths, please. Stimulate the economy instead of giving it roundstart.

**Comment by JTGSZ** [comment]
im closing cause they too coward to jus do it.

**Pull request closed without merging**
