### PR TITLE
Thieves cant for rogues and beggars

### PR DESCRIPTION
**Pull request by OrbitalParadise**
## About The Pull Request

The PR adds the fantasy and real-life relevant thieves cant language, given to rogues and beggars. Instead of using a list of syllables, the language is done with replacing words with others making possibly confusing sentences to listeners, but to those who understand it is comprehensible by un reverting it back to its original meaning. Mainly the special trait of this language is the fact that it is meant to look the exact same as common. 

My first pr let me know if there is any issues, still need to work on the list of words and to test if it can be translated and then untranslated correctly. Needs testing on class spawn in language assignment for rogue and beggar.

Not finished

### CODE REVIEW

**Comment by NGGJamie** [comment]
You didn't add the thieves cant dm file to the DME so it isn't being loaded. Also, you need to provide a screenshot of it working per the head dev.

**Comment by OrbitalParadise** [comment]
might give the language to assassins

**Comment by OrbitalParadise** [comment]
for some reason I get undefined proc when I add the language for beggars but it works fine for rogues

**Comment by NGGJamie** [comment]
You should really do your dev on your local machine and ensure it builds locally. It'd save you a lot of time waiting for the CI since I have to approve the CI to run every time.

**Comment by OrbitalParadise** [comment]
doing it on local machine, stuck rn on how to assign the language on class selection correctly

**Comment by Osmos123** [comment]
Would recommend looking at #412 for language and make use of the same things.

**Comment by OrbitalParadise** [comment]
I got assignment for language on class selection
https://cdn.discordapp.com/attachments/1104808570383519874/1233958762226651247/image.png?ex=662efd26&is=662daba6&hm=60653b9fdabe03bcbe6a10e1c2b1e51fa391b608ff0d20df752d44b941637f16&

issues im having is that the proc can translate a single word but not a sentence
there is also the fact that I wanted translated words to get untranslated if the listener understands the language, its gotta work fowards and backwards idk if #412 fixes my issue. Also need to make it work in all caps cases

**Comment by OrbitalParadise** [comment]
just realized my code removed elvish from the drow so I gotta redo how I did it

**Comment by CVSthePharmacy** [comment]
does this mean rouges and beggars can't speak common anymore

**Comment by OrbitalParadise** [comment]
no they can speak both

**Comment by OrbitalParadise** [comment]
Probably not going to figure out how to grant language outside of species like how languages are usually assigned. Will work on it more later. 

Leaving idea here for myself to use the 1000 most used words string in the code and just randomize that for the language like codespeak did

**Comment by OrbitalParadise** [comment]
Closing until I get more time

**Pull request closed without merging**
