### PR TITLE
Moves steward into the castle, opens old steward area into a market area

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Moves steward into the castle, where the steward building used to be is now open space with a few tables around, tested it because last map PR i made was broken, this one is golden

## Why It's Good For The Game

Steward kept getting rolled, now they won't get robbed so often

Z3
2 - Copy
Z4
2 - Copy (2)
Z5
2 - Copy (2) - Copy
New market area

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Looking for second opinions before testmerging. Lots of open space now.

**Comment by Real-MAGNUM** [comment]
I fuck with this town of salem vibe heavy, or whatever the kids say. Testmerging.

**Comment by YosemiteYam** [comment]
The open space the stewards old spot creates could be used for some new shops like tailors, maybe some public market stalls?

**Comment by Viviridia** [comment]
I feel like the steward needs the feeding hole inside the warehouse. since the office is inside the keep now

**Comment by TheManWithNoHands** [comment]
Good for opening room for future shops, but has some problems.
Mainly two:
* As already mentioned before, the warehouse is now far away. Add another slurp hole inside the warehoue migth be the best option.
* The steward is less present outside the keep with this. This MIGTH lower the ammount of interaction the steward has with people outside keep. But thats just a concern, migth be that it works out well and people from outside the keep still interact with the steward a good ammount.

**Comment by zakanater19** [comment]
Placed a submission hole in the warehouse, and also fixed the open space above the closet

**Comment by zakanater19** [comment]
> is that a fucking door that leads into a stone wall

Nah it's just the Z above the door having open space, kinda silly

**Comment by CVSthePharmacy** [comment]
> Good for opening room for future shops, but has some problems. Mainly two:
> 
> * As already mentioned before, the warehouse is now far away. Add another slurp hole inside the warehoue migth be the best option.
> * The steward is less present outside the keep with this. This MIGTH lower the ammount of interaction the steward has with people outside keep. But thats just a concern, migth be that it works out well and people from outside the keep still interact with the steward a good ammount.

you might have a point, I can no longer murder the steward undetected and rob the treasury without having 6 guards on the door

**Pull request merged**
