### PR TITLE
Crossbow and bow balance

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
No more scaling with PER, as having more than 100dmg meant it went through armor and crit people.

## Why It's Good For The Game
Armor should protect against range attacks.

### CODE REVIEW

**Comment by Ambrose997** [comment]
Might as well delete the perception stat.

**Comment by Deroh-Ra** [comment]
Crossbows by design are meant to pierce armor, bows shouldn't be able to pin armor though

**Comment by Hmeister-real** [comment]
bows are gonna be fucking worthless, at least buff them to do something unique, like maybe they do a a ton of damage when you remove them and when they fall off

**Comment by pismorizzo** [comment]
Bow damage was already buffed and currently does more damage than crossbows when skilled, dont understand the complaints against them. 
I do agree this makes perception kinda weak and perhaps should simply reduce or cut the scaling in half like was done with strength instead of removing all scaling outright.

**Comment by YosemiteYam** [comment]
The ranged cabal needs to stop crying over not being able to one shot people

**Comment by CVSthePharmacy** [comment]
> The ranged cabal needs to stop crying over not being able to one shot people

you should be banned from the github

**Comment by OrbitalParadise** [comment]
> The ranged cabal needs to stop crying over not being able to one shot people

All weapons can one shot get over yourself

**Comment by Real-MAGNUM** [comment]
This is a weird idea to fix a problem we all know exists. Remove scaling from crossbow only, it's a simpler weapon to use, has more base damage, but no scaling. Keep crossbow damage where it was.

Keep perception scaling on the bow.

**Comment by Real-MAGNUM** [comment]
Discussed internally amongst staff, including head dev. We're reopening a new PR that should balance crossbows in a way heads agree on.

**Pull request closed without merging**
