### PR TITLE
New Bog Map

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request

Hyuuuuge shit. Entirely new bog area. Removes old forest, old bog, and lava caves from active map pool.
Puts the town behind the bog gate
Doubles bogguard max count (until we get reopening job slots)
New rules to change how anarchy zone is structured. It no longer reaches behind the gate, only everything outside of the gate.
Moves soilsons into the town.
Moves the dwarf area into the mountains.

## Why It's Good For The Game

Bog needed a rework bad. Puts the town behind the gate. Does some other cool ass shit. **READ THE NEW RULES FOR BOG ANARCHY ZONES ON DISCORD ONCE THEY COME OUT.**

Screenshot 2024-05-02 194933

### CODE REVIEW

**Comment by pismorizzo** [comment]
Bog has no stones or bushes

**Comment by CVSthePharmacy** [comment]
send a pic

**Comment by Real-MAGNUM** [comment]
> Bog has no stones or bushes

Unrelated to pr. Preexisting bug.

**Comment by Real-MAGNUM** [comment]
> send a pic
updated.

**Comment by RedNiloc** [comment]
This new map is massive, it would be nice to see some interesting ruins in it though.

**Comment by RedNiloc** [comment]
There need to be wayyy less bog spawns, I feel like there is alot.

**Comment by CVSthePharmacy** [comment]
give the bandits a ladder or at least a platform so they don't instantly die due to head trauma when they fucking fall 3 stories, like my GOD why did you make them live in that mountain that they can DIE OFF OF without any light, and EVEN WHEN CLIMBING DOWN YOU GET HURT BECAUSE IT'S ON THE THIRD STORY

**Comment by zakanater19** [comment]
mapmerger no longer works?

**Comment by Real-MAGNUM** [comment]
I think mapmerger is what's breaking the grass. I cant tell.

**Comment by Real-MAGNUM** [comment]
> There need to be wayyy less bog spawns, I feel like there is alot.

Bog spawns? What do you mean.

**Comment by zakanater19** [comment]
> > There need to be wayyy less bog spawns, I feel like there is alot.
> 
> Bog spawns? What do you mean.

i believe he means the bog guard count of 20 instead of 10

**Comment by Real-MAGNUM** [comment]
> i believe he means the bog guard count of 20 instead of 10

I's possible. I've noticed bog guard die FAST in the first 30 minutes. We dont have reopening job slots, and currently there are many jobs that require the bog guard to exist, else they just get ran over.

**Pull request merged**
