### PR TITLE
[SPLIT] Sarkness Extravaganza: Dwarves armor

### PR DESCRIPTION
**Pull request by Sarkness**
## About The Pull Request

Add the following:
Dwarf Knight Armor
Dwarf Punisher Armor
Dwarf Engineer, Overseer Helmets
Wizard Iron Cap
The remaining Gem rings (Steel/Gold Variant)
Secret Valuable

## Why It's Good For The Game

Dwarf Armors, were requested since a while, and are the first of a three-parts series, in which each race will have to get specific armor tailored and smithed only for them. The following is a work from Takyon, and fixes were done by Karl. Approved by MAGNUM and Sangheili since a moment.

### CODE REVIEW

**Comment by Xkallubar** [comment]
Can you show sprites?

**Comment by Takyon69** [comment]
Gem rings are silver not steel also post sprites please.

**Comment by Sarkness** [comment]
Sprites are the remaining ones in rings.dmi in /icons/roguetown/clothing 

Furthermore they're steel because we ain't got silver ingots YET.

**Comment by Takyon69** [comment]
> Sprites are the remaining ones in rings.dmi in /icons/roguetown/clothing
> 
> Furthermore they're steel because we ain't got silver ingots YET.

Can you post all the sprites listed, including armour?

**Comment by Sarkness** [comment]
I'll post them once at home. Will ping you on discord.

**Comment by Sarkness** [comment]
image
image
image
image
image
image

Hi Takyon

**Comment by Takyon69** [comment]
> image image image image image image
> 
> Hi Takyon

Alright so the palettes on the "punisher" and "knight" armour will have to be edited with the new palette. It's pinned in the discord's spriter channel. Same for the other helmets. The other three helmets are also differently stylized compared to the helmet icons we have at the moment.

**Comment by Gyrandola** [comment]
Why does the dwarf punisher helm look like graggar?

**Comment by TheManWithNoHands** [comment]
Always love seeing our unused sprites being used. Most look actually very decent, like the dwarf knight helmet. Dayum that's badass. Just some helmets don't have the zoomed-in thing for in-hand sprites. But who cares much about that if they look decent on mobs, we have tons of sprites like that already that are being used.
Like many of the hoods.

But the claws on the dwarf gauntlets are a bit weird.

**Comment by ChungusGamer666** [comment]
conflicts...

**Comment by Real-MAGNUM** [comment]
Closed by request of takon and sark's understanding.

**Pull request closed without merging**
