### PR TITLE
adds brazillians (as a smite) AND REWORKS A METRIC FUCKTON OF BAD SPECIES CODE

### PR DESCRIPTION
**Pull request by ChungusGamer666**
image

### CODE REVIEW

**Comment by Gyrandola** [comment]
scalies

**Comment by EnzoSeptum** [comment]
dick better translation is pau

**Comment by ChungusGamer666** [comment]
this pr needs to be speedmerged because i had to do SEVERE changes to species code

**Comment by ChungusGamer666** [comment]
cancer

**Comment by ChungusGamer666** [comment]
hooooly fuck.... lois... im coming

**Pull request merged**
