### PR TITLE
FUCK FOG

### PR DESCRIPTION
**Pull request by Ambrose997**
## About The Pull Request

FUCK FOG

## Why It's Good For The Game

FUCK FOG

### CODE REVIEW

**Comment by wgtjunior743** [comment]
It is truly annoying as hell but what make it worse is that even inside buildings the fog is there and that makes  no sense, if someone is able to program so the fog can't appear inside buildings it would probably more accepted.

**Comment by thefirstjeb** [comment]
just got 1 hit-instakilled as the king inside throne room because of the fog and it's so boring, it sure should not happen inside buildings. And 1 hit kill is very nonsense.

**Comment by OzfurAtlas** [comment]
Hey Ambros, could this be fixed by a tile check? So that only dirt tiles etc will have fog?

**Comment by Wintermote** [comment]
Are structures in this using areas to define them? (e.g. how powernets and APC's work) That should be able to do it.

**Comment by OzfurAtlas** [comment]
> Nuking cool thing instead of fixing is badd

True. But the mist is clunky as hell and needs more refinement before being commited.

**Comment by ChungusGamer666** [comment]
Does not compile

**Comment by Ambrose997** [comment]
> Does not compile

Does now!

**Comment by bobjension** [comment]
what the fuck, what is this pr bro, STOP REMOVING SHIT AND EITHER CHANGE OR ADD IT SO IT ISN'T AS BAD ANYMORE, NOT THIS STUFF WHERE YOU JUST OUTRIGHT REMOVE WEATHER BECAUSE YOU DIED ONCE BECAUSE OF IT

**Comment by Ambrose997** [comment]
> what the fuck, what is this pr bro, STOP REMOVING SHIT AND EITHER CHANGE OR ADD IT SO IT ISN'T AS BAD ANYMORE, NOT THIS STUFF WHERE YOU JUST OUTRIGHT REMOVE WEATHER BECAUSE YOU DIED ONCE BECAUSE OF IT

No one wants to work on it, i'm not code-savvy enough to know how to prevent it fucking with things indoors. Feel free to do so though!

**Comment by Ambrose997** [comment]
The logic was to comment it out temporarily until it can be improved upon in future, you know, quality of life for players in the meantime?

**Comment by efzapa** [comment]
just make fog not fucking completely blind you and its fine

**Comment by BigBigga** [comment]
just make it so it can't go inside buildings like it used to.

**Comment by OzfurAtlas** [comment]
> ## About The Pull Request
> FUCK FOG
> 
> ## Why It's Good For The Game
> FUCK FOG

Ambros ill grab this fork tonight and work on properly room-ing the maps, then ill implement the same lavaland/snowbox code over. for now close this merge

**Comment by Real-MAGNUM** [comment]
Closing this PR since Ozfur is picking up the fog.

**Comment by Ambrose997** [comment]
> > ## About The Pull Request
> > FUCK FOG
> > ## Why It's Good For The Game
> > FUCK FOG
> 
> Ambros ill grab this fork tonight and work on properly room-ing the maps, then ill implement the same lavaland/snowbox code over. for now close this merge

Are we able to replace the fog overlay as well? It's way too thick and idk about you but fog irl doesnt literally blind me.

**Comment by Ambrose997** [comment]
Please reopen and merge this. fog was meant to be fixed ages ago but it just hasn't happened.

**Comment by Real-MAGNUM** [comment]
If this breaks stuff it'll get reverted. Weather can get tricky. Hopefully it'll be fine though.

**Comment by OzfurAtlas** [comment]
> Please reopen and merge this. fog was meant to be fixed ages ago but it just hasn't happened.

i foudn the FUCKING problem.. so the fog icon is fucking  FULL SCREEN

**Pull request merged**
