### PR TITLE
Medical rework part 2 - The monkey's paw curls

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Removes all instakills and replaces them with even more gruesome wounds

Ear stab instakill - Replaced with eardrum rupturing, you can poke ears out now
Nosestab - Can now permanently disfigure you, also halves stamina regeneration, cannot be fixed ever
Skullstab and skullcrack - Replaced with cranial fractures, which much like necksnaps will leave your body entirely paralyzed, additionally makes you slur your speech while not fixed
Mouth stab and mouth fracture - Can now fracture your jaw instead of the head, which obviously makes your speech gargled until fixed

## Why It's Good For The Game

People hate instakills so why not give them the change they want so badly?
image
image

### CODE REVIEW

**Comment by Stagrawl** [comment]
The real crit is being hit so hard your cervix flies up into your skull

**Comment by CVSthePharmacy** [comment]
this is hugbox shit lmfao, what a hypocrite

**Comment by ChungusGamer666** [comment]
> this is hugbox shit lmfao, what a hypocrite

cvs as always dropping the hottest takes
yeah this is hugbox but it's funny and in practice worse than instakills

**Comment by CVSthePharmacy** [comment]
> > this is hugbox shit lmfao, what a hypocrite
> 
> cvs as always dropping the hottest takes yeah this is hugbox but it's funny and in practice worse than instakills

if this is just a 1 round thing then it's fine, but this is really something I'd rather get closed. Kinda fucks with how the game is played too much, and as I said, is hugbox shit. The game will literally just be cookie clicker sim

**Comment by DirtTastesBad** [comment]
Could just make it so when a crit procs, there's a %chance it'll either do the insta-kill or the effect

**Comment by DirtTastesBad** [comment]
Ear could have something like a 25% chance for the instakill while eye has a 75% chance, or something along those lines

**Comment by wgtjunior743** [comment]
i agree with the changes, instant kill is not funny when you are hit by it, i already got hit in the eyes so many times and instant critted died, i don't even knew ear could instant kill, good changes

**Comment by Hmeister-real** [comment]
People like CVS are just quaking at the idea of not being able to instantly grab and crit kill people in all scenarios with a high wrestle+swift combo, good PR. cope

**Comment by pilotmans** [comment]
this seems like a pain to deal with.

**Comment by dunsel-hordon** [comment]
I think people underestimate the actual precision and force needed to stab through the skull

**Comment by erik30015** [comment]
can vampires heal from this stuff correctly?

**Comment by ophaq** [comment]
Can we get limb targeting hotkeys too? I feel that medical is such a pain when you have to constantly click on each wound on the doll, when in codebases like TG you can use the numpad. 8 for swapping through head parts, 5 for chest, 2 for groin, 1 and 3 legs, 4 and 6 arms, 7 or 9 neck. Something like that would be nice to have for those who heal others and just in general in combat.

**Comment by ChungusGamer666** [comment]
> Can we get limb targeting hotkeys too? 

those are a thing

**Comment by EnzoSeptum** [comment]
This pr should be called TG blackstone station 13

**Comment by zoktiik** [comment]
This PR should be called Blackstone: Theater of Pain.

**Comment by Hmeister-real** [comment]
> Can we get limb targeting hotkeys too? I feel that medical is such a pain when you have to constantly click on each wound on the doll, when in codebases like TG you can use the numpad. 8 for swapping through head parts, 5 for chest, 2 for groin, 1 and 3 legs, 4 and 6 arms, 7 or 9 neck. Something like that would be nice to have for those who heal others and just in general in combat.

shift+scroll wheel lets you go up and down limb targetting

**Comment by wgtjunior743** [comment]
This may be causing All swords being able to be stuck in the chest

**Comment by dunsel-hordon** [comment]
please revert this it is utter ass and completely fucks most antag rolls

**Pull request merged**
