### PR TITLE
[FIX] Bandit Necklace Buff / Dragon Ring / Execution Sword

### PR DESCRIPTION
**Pull request by Sarkness**
## About The Pull Request

This PR adds the following:
- Dragon Ring, which is a general boost to all players (+ STR/END/CON)
- Bandit Necklace buff, has iron gorget defense and stats bonuses only for bandits, but nothing else for other players!
- An execution sword in the anvils tables

## Why It's Good For The Game

Bandits Necklaces being the final tier but wielding no actual power sucked ass, so that's fixed.
Dragon Rings, just addss a forgotten ring in game, gives it an actual purpose to be made (Dungeon-loot soon?)
Execution blade, just terminus est but shittier, ccraftable at anvils.

### CODE REVIEW

**Comment by erik30015** [comment]
can you repair it if it breaks or can it break?

**Comment by MickDick1** [comment]
Good idea. The dragon necklace was more like proof you completed your goal as the bandit antag, but you have to bother an admin grant your wish. Most of the time admins just ignore you (or aren't around). So, fuck it.

Just leave it unbreakable. It's magic. Pretty much the only actual unique reward you're gonna get as bandit. It breaking would be annoying as shit and the only option to wear it on your neck means you're just gonna get throat slit immediately in a fight otherwise. All that being said I tested this locally and found several problems:

1. You need to define integrity. By default, items have 100 or whatever their original item-type has set. Give it 9999 or something.
2. It needs an armor-hit-sound
3. When you pick it up, it applies the buff, and when you put it on your neck, it applies the buff again without removing the previous one. You can permanently stack buffs up to 20 by putting it on/off your neck over and over. You only lose 2 stat when completely dropping it from your character. Im sure the ring has the same problem.

**Comment by Sarkness** [comment]
Greetings!
Just to clarify on few things:

1) Integrity hass been adedd and the armor is indeed unbreakable (despite having well durability)
2) Armor sound has been added. 
3) _**YOU FOOL, YOU'VE FALLEN FOR MY TRAP CARD!**_ There's a Var specifically to block this, the stacking doesn't happen and it works.
HOWEVER, it would make sense if I pushed that commit for that var fix lol

**Comment by Sarkness** [comment]
> can you repair it if it breaks or can it break?

Erik, it cannot break (but you can repair it), but it cannot break.

**Comment by Takyon69** [comment]
Can you post the execution blade sprite?

**Comment by Sarkness** [comment]
> Can you post the execution blade sprite?

image
image
image

Located in weapons/64.dmi

@Takyon69

**Comment by CVSthePharmacy** [comment]
> > can you repair it if it breaks or can it break?
> 
> Erik, it cannot break (but you can repair it), but it cannot break.

free smithy exp................

**Pull request merged**
