### PR TITLE
The Daylight Update

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

make night not absurdly long

previous: 
night 4 pm to 8 am
dawn 8 am to 10 am
day 10 am to 2 pm
dusk 2 pm to 4 pm

now:
night 5:30 pm to 5:30 am
dawn 5:30 am to 7 am
day 7 am to 4 pm
dusk 4 pm to 5:30 pm

## Why It's Good For The Game

now nighttime isnt from 4 pm to 10 am

### CODE REVIEW

**Comment by SELFHELL** [comment]
Just a small consideration, but most antags require night-time to actually function. Such as vampires dusting in the sun

**Comment by YosemiteYam** [comment]
It would be nice that it wasn't 16 hours long but putting it down to 8 hours could also harm the grimdark nature of it all, I feel like nights and seasons are supposed to be fucky in this universe. Maybe 12 hours of night would be a better compromise, considering night-time antags as well.

**Comment by bobjension** [comment]
day and night right now are 10 minutes and 30 minutes irl


10 hours of mfering night time?? how about you carry a light around, this would fuck up steath (you can go only go invisible while in the dark), this would also fuck up vampires so much more because they only get 10 minutes of doing shit, then 30 minutes of staying in a building, this is a cope PR

**Comment by BlueMemesauce** [comment]
also vampires apparently can use cloaks during the day or something

**Comment by BlueMemesauce** [comment]
misclick

**Comment by CVSthePharmacy** [comment]
> day and night right now are 10 minutes and 30 minutes irl
> 
> 10 minutes of mfering night time?? how about you carry a light around, this would fuck up stealth (you can go only go invisible while in the dark), this would also fuck up vampires so much more because they only get 10 minutes of doing shit, then 30 minutes of staying in a building, this is a cope PR, 12 hours is still ass for vampires and anyone skulking around.

you'll get used to it, in the meantime shut up

**Comment by ChungusGamer666** [comment]
i don't really like this, as bob says it messes vampire balance and feels unfitting

**Pull request closed without merging**
