### PR TITLE
Makes crossbows rarer, and changes their purpose in the ranged meta

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request

Makes crossbows rarer across the board, limiting spawns. Removes them from most on-spawn

## Why It's Good For The Game

Crossbows are everywhere. We want to keep the power and accessibility to use, but make them less common.

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
I might give bandits regular bows instead of crossbows. Same with every other guard that spawns with crossbows rn (bogguard)

Total crossbow death tbh, keep them in limited supplies within armories

**Comment by CVSthePharmacy** [comment]
everyone on the discord thinks this is a shit pr, maybe you should listen to them? Idk, just stop taking stuff from roles

**Comment by CVSthePharmacy** [comment]
adding onto a actual comment, you're nerfing torso, which is hilarious as it's a challenge role, also you're removing the crossbow from rogue, the crossbow class. have you like idk thought about this for more than 20 seconds after dying? mayyyyyybe take community feedback on the discord?

**Comment by TheManWithNoHands** [comment]
> adding onto a actual comment, you're nerfing torso, which is hilarious as it's a challenge role, also you're removing the crossbow from rogue, the crossbow class. have you like idk thought about this for more than 20 seconds after dying? mayyyyyybe take community feedback on the discord?

Bro, the ability to craft them aint gone. If you're so dying to get one just buy one from the weapon smith. Only needs one steel, so aint hard.

**Comment by OrbitalParadise** [comment]
Rogues could use crossys to one tap rous, bees, Saiga, a single knife isn't going to protect you from anything and I think some other classes like naked have that issue during ambushes

**Comment by Real-MAGNUM** [comment]
This isnt being changed no matter how much you cry, cvs. Just buy them if you want to shoot from rooftops as a rogue, the skill isnt gone. Oneshotting crossbows dont need to be given out to everyone roundstart, you'd cry just the same if I removed the high damage. Crossbows are in a bad spot and they're getting changed in one way or the next. This is what maintainers decided on internally, it's what will happen. I'm sorry your favorite role is getting nerfed.

Most ranged classes will soon get bows instead of crossbows at roundstart, including guards. Armories will probably still have one or two max. Otherwise, smith them. I'm focusing on remapping the town but I'll get around to it eventually.

**Comment by OrbitalParadise** [comment]
> > adding onto a actual comment, you're nerfing torso, which is hilarious as it's a challenge role, also you're removing the crossbow from rogue, the crossbow class. have you like idk thought about this for more than 20 seconds after dying? mayyyyyybe take community feedback on the discord?
> 
> Bro, the ability to craft them aint gone. If you're so dying to get one just buy one from the weapon smith. Only needs one steel, so aint hard. Only thing this pr really those is lower the ammount of round start xbows.

Nope 3 bolts are 1 iron each, their quivers are gone. Idk how you are supposed to afford all that by being a nice guy only butchering animals to get once was a given roundstart

**Comment by Real-MAGNUM** [comment]
> Rogues could use crossys to one tap rous, bees, Saiga, a single knife isn't going to protect you from anything and I think some other classes like naked have that issue during ambushes

Rogues arent intended for direct combat. Crossbows just let them do this extremely easily by shooting people from above, or even in-combat. It outclasses the roles that are built to be ranged classes. It's bad design to throw oneshot weapons at every class just because "it's how it's always been". It devalues archers, and it gives classes that arent designed to be strong at range the ability to win against ranged classes at range, as well as an rng trump card against melee characters.

> Nope 3 bolts are 1 iron each, their quivers are gone. Idk how you are supposed to afford all that by being a nice guy only butchering animals to get once was a given roundstart

Unrelated. If you have a problem with ammo production, PR a crafting change.

**Comment by OrbitalParadise** [comment]
> Rogues arent intended for direct combat.

Being stealthy is what you meant here, but now that roundstart they are no longer a ranged class will you give them another weapon?

**Comment by Real-MAGNUM** [comment]
> Being stealthy is what you meant here, but now that roundstart they are no longer a ranged class will you give them another weapon?

They were given a second dagger, but other than that I have no plans for them. They can earn their power via stealing or killing, and buying their crossbow like all other adventurers.

**Comment by pilotmans** [comment]
> > Being stealthy is what you meant here, but now that roundstart they are no longer a ranged class will you give them another weapon?
> 
> They were given a second dagger, but other than that I have no plans for them. They can earn their power via stealing or killing, and buying their crossbow like all other adventurers.

This seems kind of antithesis to the rogue class concept, they are mean't to be backhanded and steal stuff, yes... but the way they do that is with either hiding in the shadows or sniping from rooftops with crossbows.
this just heavily limits their capability.

**Pull request merged**
