### PR TITLE
Add Siege Gamemode (attempt 2)

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

It adds a new gamemode called siege which spawns a baron and soldiers with the goal of taking over the crown.

For now they use the bandit spawn, but soldier spawns can be added.

Baron might be weak to head stabs but he looks cool

Proof images:

image

image

image

## Why It's Good For The Game

Epic battles
Bog is the first line of defense and has to run to inform the king
king can conscript an army for defense
If the Baron wins he can establish a tyranny for himself and his men (although King is already evil half the time)
Basically nuke ops

### CODE REVIEW

**Comment by zakanater19** [comment]
very nice

**Comment by Real-MAGNUM** [comment]
testmerging

**Comment by zakanater19** [comment]
can you replace the barons mens equipment for this instead of bandit?

	head = /obj/item/clothing/head/roguetown/helmet
	pants = /obj/item/clothing/under/roguetown/chainlegs
	neck = /obj/item/clothing/neck/roguetown/chaincoif/iron
	shirt = /obj/item/clothing/suit/roguetown/shirt/shortshirt/merc
	armor = /obj/item/clothing/suit/roguetown/armor/leather/studded
	gloves = /obj/item/clothing/gloves/roguetown/chain
	shoes = /obj/item/clothing/shoes/roguetown/boots
	beltl = /obj/item/keyring/guardcastle
	belt = /obj/item/storage/belt/rogue/leather
	beltr = /obj/item/rogueweapon/sword
	backr = /obj/item/storage/backpack/rogue/satchel

**Comment by BlueMemesauce** [comment]
ok untestmrege it we need to do the herald thing that chungus wants

**Comment by Real-MAGNUM** [comment]
done

**Comment by BlueMemesauce** [comment]
ok i give up

**Pull request closed without merging**
