### PR TITLE
Archivist more interesting - scholar

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Archivist broke the system, move to other plane of existence! But with what cost! He can no longer fight to protect himself!

Moved archivist to nobility (basement noble), made him pacifist and legendary at every skill that isn't crafting (for now as I need to make new trait which will prevent him from crafting).

This should make him more interesting as a man/woman of skill to share with others for some coin.
For that reason his Intelligence and Endurance are at maximum (it is still a mystery if his high Endurance is because of knowledge he acquired or just the amount of Qahwah wine he drinks), to teach as best as he can!
As he is a pacifist his high Endurance will help him run when startled.

## Why It's Good For The Game
FUNNY! Unique role just for Ye!

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
This is the PR I just closed. Stop making these.

**Comment by BigBigga** [comment]
LMFAO

**Comment by Real-MAGNUM** [comment]
This might suck idk yet

testmerging

**Comment by BigBigga** [comment]
legendary on every single skill???? why? he's a bonefide bookworm, not some legendary war hero. reading doesn't make you a legend at something. by this logic we should also give the court wizard legendary on everything. and regular wizards master on everything. just make him able to teach people how to read and maybe trade. this is too much.

**Comment by CVSthePharmacy** [comment]
> legendary on every single skill???? why? he's a bonefide bookworm, not some legendary war hero. reading doesn't make you a legend at something. by this logic we should also give the court wizard legendary on everything. and regular wizards master on everything. just make him able to teach people how to read and maybe trade. this is too much.

he actually just got isekai'd into blackstone that's why

**Comment by Gyrandola** [comment]
please dont add this memey shit

**Comment by BigBigga** [comment]
literal meme yeah lmfao. truly a BLACKstone pr

**Comment by Real-MAGNUM** [comment]
Yeah no reason to have this until we can teach skills via writing.

**Pull request closed without merging**
