### PR TITLE
Coat of plates

### PR DESCRIPTION
**Pull request by LucaNotLucas**
## About The Pull Request

This pull request adds the coat of plates armor (medium armor with 250 integrity (+50 than scalemail) and that protects the arms)
and crafting recipes for some unused armors like the iron breastplate (2 iron), studded leather armor (1 iron + armor), plated chausses (2 steel), brigandine (2 steel + gambeson), and coat of plates (1 steel + hide)

## Why It's Good For The Game

Not only does this make more armors available, and give more choices, it also uses some previously unused materials (iron, hide) for armor crafting, and lets you "upgrade" (leather armor -> studded leather, gambeson -> brigandine) some other armors that would be otherwise almost never used.

### CODE REVIEW

**Comment by YosemiteYam** [comment]
Medium armor already has quite good armors, I feel like any armors that utilize plates more than just a chest piece like a coat of plates should go under heavy armor instead, and make them slightly weaker/cheaper than normal plate armor. Otherwise this is a buff to everyone who doesn't have the heavy armor trait and lets them powercreep up on the heavy armor users.

**Comment by LucaNotLucas** [comment]
Makes sense, let me go ahead and change it to make it heavy armor

**Comment by panvxv** [comment]
> ## About The Pull Request
> 
> This pull request adds the coat of plates armor (medium armor with 250 integrity (+50 than scalemail) and that protects the arms) and crafting recipes for some unused armors like the iron breastplate (2 iron), studded leather armor (1 iron + armor), plated chausses (2 steel), brigandine (2 steel + gambeson), and coat of plates (1 steel + hide)
> ## Why It's Good For The Game
> 
> Not only does this make more armors available, and give more choices, it also uses some previously unused materials (iron, hide) for armor crafting, and lets you "upgrade" (leather armor -> studded leather, gambeson -> brigandine) some other armors that would be otherwise almost never used.

Could you make so brigandine requires 2 cloth and not gambeson? Remove it arm protection too and made it medium armor.

**Comment by CVSthePharmacy** [comment]
> Medium armor already has quite good armors, I feel like any armors that utilize plates more than just a chest piece like a coat of plates should go under heavy armor instead, and make them slightly weaker/cheaper than normal plate armor. Otherwise this is a buff to everyone who doesn't have the heavy armor trait and lets them powercreep up on the heavy armor users.

ehhhh don't do this cause making plated chausses heavy will fuck up knight armor

**Comment by LucaNotLucas** [comment]
> Could you make so brigandine requires 2 cloth and not gambeson? Remove it arm protection too and made it medium armor.

If it's gonna be medium armor then yeah i'll make it cheaper to make, although i think it's better if it has arm armor instead of leg, since if it also had legs then it would just be a more expensive version of scalemail, wich is already only 1 steel and has 200 integrity with leg and chest protection.

**Comment by LucaNotLucas** [comment]
> ehhhh don't do this cause making plated chausses heavy will fuck up knight armor

Oh and also, all of the pants don't have weight, so no skills needed to wear plate chausses

**Comment by CVSthePharmacy** [comment]
> > Could you make so brigandine requires 2 cloth and not gambeson? Remove it arm protection too and made it medium armor.
> 
> If it's gonna be medium armor then yeah i'll make it cheaper to make, although i think it's better if it has arm armor instead of leg, since if it also had legs then it would just be a more expensive version of scalemail, wich is already only 1 steel and has 200 integrity with leg and chest protection.

just keep it as light and ignore pan's comment, it's a gambeson with plates, it's not like you magically shear off the legs once you add the bar

**Comment by panvxv** [comment]
> > > Could you make so brigandine requires 2 cloth and not gambeson? Remove it arm protection too and made it medium armor.
> > 
> > 
> > If it's gonna be medium armor then yeah i'll make it cheaper to make, although i think it's better if it has arm armor instead of leg, since if it also had legs then it would just be a more expensive version of scalemail, wich is already only 1 steel and has 200 integrity with leg and chest protection.
> 
> just keep it as light and ignore pan's comment, it's a gambeson with plates, it's not like you magically shear off the legs once you add the bar

Brigandine has nothing to do with gambeson. It isn't "gambeson with plates", gambeson is really thick cloth armor.
Brigandine should only protect chest, vitals and groin. Be medium armor and having more integrity than other medium armors.

**Comment by LucaNotLucas** [comment]
Ok i'm gonna be honest right now, i think it's good how it is, a brigandine is basically a cloth piece with plates and mail attached to it, that's why i had put it with a gambeson recipe, but i realized that might be a liiiiittle bit too expensive since it takes a lot of cloth and skill to make one, so i made it 2 cloth, it's also not the heaviest armor so it makes sense it's medium, not light since it has plates in it. BUT i think i'll leave arm protection on, since it costs 2 steel, if i made it only protect chest then it'd just be a worse (or slightly better if i raise the integrity) cuirass, wich almost nobody uses already. With the arm protection in, and high integrity (same as cuirass) it would basically become a nice, mid-high price armor. Worse than plate armor, better than chain.

**Pull request merged**
