### PR TITLE
Adds walls to the town with a gate, also walls off the farm area so it's considered part of the town lands

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Adds a big wall around the town and a gate for the town guard to man, also adds some iron bars in the sewers to stop invaders using the sewers to gain access to bypass the gate easily

## Why It's Good For The Game

People were talking about adding a wall so i want to see how it plays out

The gatehouse
2 - Copy
Surrounding the gatehouse

View of the farm area
2 - Copy (2)
Showing the barr
2 - Copy (2) - Copy
The gates working
https://github.com/Blackstone-SS13/BLACKSTONE/assets/15787530/39288cab-89a6-45b4-afe5-168839e73774

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Looks good to me, +1

**Comment by Autisem** [comment]
whos maintaining the gate? the keep has a gatemaster and bog have bog master

**Comment by zakanater19** [comment]
> whos maintaining the gate?
The town guard

**Comment by BadAtThisGame302** [comment]
Why would you remove the Western bridge and the moats from here?
image

**Comment by zakanater19** [comment]
> Why would you remove the Western bridge and the moats from here? image

the moat continues as normal undernearth

**Comment by ChungusGamer666** [comment]
fix conflicts chimp

**Comment by zakanater19** [comment]
> fix conflicts chimp

fug

**Comment by zakanater19** [comment]
i will come back to this one after the other sewer thing

**Pull request closed without merging**
