### PR TITLE
steel short sword

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
adds a steel short sword, loosely patterned after the gladius hispaniensis

same overall stats as the iron short sword, but with a small bump to damage and defense
it cannot be wielded but has a stronger and faster stab attack
texct

## Why It's Good For The Game
the gladius is cool
rapier still probably a better choice due to defense, but slightly more damage on hit might be able to reduce enemy armor to 0 integrity faster

### CODE REVIEW

**Comment by Takyon69** [comment]
Use the right steel palette. Pinned on the discord.

**Comment by ChungusGamer666** [comment]
takyon can merge this at his leisure

**Review by ChungusGamer666 — APPROVED** [review]

**Comment by Takyon69** [comment]
> > Use the right steel palette. Pinned on the discord.
> 
> looks about the same texct

Similar but not the same. Use the steel palette pinned in the spriter channel pinned on the discord. The one with the purple-hued darker shades.

**Comment by Xkallubar** [comment]
This will be extremely overpowered against werewolves and vampires, correct?

**Comment by cornercube** [comment]
> Similar but not the same. Use the steel palette pinned in the spriter channel on the discord. The one with the purple-hued darker shades.

texct



> This will be extremely overpowered against werewolves and vampires, correct?

if only

**Pull request merged**
