### PR TITLE
Fog fix attempt

### PR DESCRIPTION
**Pull request by OzfurAtlas**
re-added some code for indoor flagging of an area to prevent the weather going into said areas.

### CODE REVIEW

**Comment by OzfurAtlas** [comment]
can someone test this i could not get fog to spawn

**Comment by OzfurAtlas** [comment]
Waiting till run weather verb is fixed
- should start weather IMMEDIATELY
- verb should affect ALL z levels

**Comment by Ambrose997** [comment]
could you make it last less time as well? its fucking painful.

**Comment by Real-MAGNUM** [comment]
How is this going?

**Comment by OzfurAtlas** [comment]
> How is this going?

sorry ive been away for the past week. i couldnt seem to get any fix done as the, run weather:fog verb didnt seem to do anything. so i couldnt test it

**Comment by OzfurAtlas** [comment]
THEORETICALY this code change will fix fog as its a copy of lavaland ash storm code

**Pull request closed without merging**
