### PR TITLE
Update treasury.dm (bank rework)

### PR DESCRIPTION
**Pull request by Coldstrike30**
THIS is a fix to the bank system.

1. Fined money actually goes to the treasury.
2. You cant over fine an account and you cant exceed the treasury balance when giving money to players account.
3. The treasury now updates after every transaction.

### CODE REVIEW

**Comment by Coldstrike30** [comment]
speed merge totally

**Comment by JTGSZ** [comment]
this compiles, and i don't see anything wrong with it.

**Comment by Coldstrike30** [comment]
so it was accepted?

**Comment by JTGSZ** [comment]
it was merged in yea

**Pull request merged**
