### PR TITLE
Gives the castle armory more stuff

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Includes equipment for castle guards and new guards, also a bunch of chains added to the garrison in town and castle armory too

## Why It's Good For The Game

Equipment for guards roundstart, because smithing is slow

2 - Copy

### CODE REVIEW

**Comment by zakanater19** [comment]
changes the boots to leather

2 - Copy

**Comment by BigBigga** [comment]
looks reasonable

**Comment by Real-MAGNUM** [comment]
Did you use mapmerger.

**Comment by zakanater19** [comment]
> Did you use mapmerger.

strongDMM already saves in TGM

**Comment by Osmos123** [comment]
Would recommend tossing in some gorgets also.

**Comment by BigBigga** [comment]
gorgets are way too good. coifs would be fine

**Comment by CVSthePharmacy** [comment]
> changes the boots to leather
> 
> 2 - Copy

change back to plated, leather boots have no use

**Comment by CVSthePharmacy** [comment]
> > change back to plated, leather boots have no use
> 
> nah i think leather is better, plus no coifs, this stuff is meant for new guards

it literally does nothing, it will never be used by any players, just switch it back to plated

**Comment by BigBigga** [comment]
guards don't need roundstart plate

**Comment by CVSthePharmacy** [comment]
> guards don't need roundstart plate

it's literally just shoes

**Comment by zakanater19** [comment]
conflicts, maybe ill redo this again

**Pull request closed without merging**
