### PR TITLE
Balance to swords

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Balancing sword based on Battle axe - a weapon you need 12 STR yet it deals 33 damage and doesn't have so many intents

Made bastard sword a little worse but rider's sword will have little advantage due to lack of thrust.
Old sword is suppose to be longsword so it handles worse in one hand (not as bad as Zweihander) but deals most damage out of every sword that isn't super rare.

### CODE REVIEW

**Comment by Gyrandola** [comment]
rapier meta

**Comment by Osmos123** [comment]
Please do something about rapiers and eye crit meta. You seem to understand the code well (saw you adjust the wound system).

**Comment by CVSthePharmacy** [comment]
> Please do something about rapiers and eye crit meta. You seem to understand the code well (saw you adjust the wound system).

hey poopy head, I think getting stabbed in the brain through the eye hole is supposed to kill you? idk but I'd be willing to test it on you

**Comment by CVSthePharmacy** [comment]
wait nvm this pr nerfs weapons, dnm

**Comment by Autisem** [comment]
> > Please do something about rapiers and eye crit meta. You seem to understand the code well (saw you adjust the wound system).
> 
> hey poopy head, I think getting stabbed in the brain through the eye hole is supposed to kill you? idk but I'd be willing to test it on you

great for realism, not so great for gameplay

**Comment by Gyrandola** [comment]
Rapiers should be completely useles against any kind of armor. Also they are borderline not medieval

**Pull request merged**
