### PR TITLE
Makes sewing loop

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Makes sewing loop for less annoyance.

## Why It's Good For The Game
Better for less chat spam about stitching wound, less clicking on laggy server, easier for new players.

### CODE REVIEW

**Comment by panvxv** [comment]
don't merge. Need to fix a bug

**Comment by NGGJamie** [comment]
Seems to remove the medicine skill from the progress equation entirely, but still grants medical experience? I would keep medicine as an influencing factor. Otherwise, absolutely love this idea.

**Comment by panvxv** [comment]
> Seems to remove the medicine skill from the progress equation entirely, but still grants medical experience? I would keep medicine as an influencing factor. Otherwise, absolutely love this idea.

moveup = (((doctor.mind.get_skill_level(/datum/skill/misc/medicine)) * 5) + moveup)
This is the part where it takes doctor's medicine skill to equation.

**Comment by NGGJamie** [comment]
I was reading on mobile, I might've just missed that. LGTM.

**Pull request merged**
