### PR TITLE
graveyard remodel

### PR DESCRIPTION
**Pull request by Scarlet-Oduko**
## About The Pull Request

Remodels the towns graveyard to be aesthetic and hopefully functional as well 

## Why It's Good For The Game

Graveyard always felt pretty awful to use, and even by dark fantasy checks didn't look that great, hopefully this will solve two birds with one stone and serve as a more functional place to bury the dead and over all area of the map.

### CODE REVIEW

**Comment by Scarlet-Oduko** [comment]
first time trying to do map stuff and it seems I've messed something up, will see about it in the morning

**Comment by Gyrandola** [comment]
I hope it adds gates like in the old map

**Comment by NGGJamie** [comment]
Adding do not merge until you can address what you mentioned above.

**Comment by Scarlet-Oduko** [comment]
> Adding do not merge until you can address what you mentioned above.

should be good now, I was working on an outdated branch and looked through it and found that other map updates were merged so that was causing the conflicts, but let me know if I missed anything

**Comment by NGGJamie** [comment]
Will be in TM next round

**Comment by Scarlet-Oduko** [comment]
seems something went wrong on (most likely on my end) none of the changes went through, I'll have to once again fix things up again once again, apologize. I think merging upstream reverted my changes and I didn't realize so I'll have to remake them on the updated one.

**Comment by NGGJamie** [comment]
Sure, just let me know and I'll push it into a TM again.

**Comment by Scarlet-Oduko** [comment]
> Sure, just let me know and I'll push it into a TM again.

okay! hopefully this will be the last time, should be good now lol. changes look to be showing much more so that's a promising thing.

**Pull request merged**
