### PR TITLE
Updated books, hud elements and priest's stole sprites.

### PR DESCRIPTION
**Pull request by Takyon69**
## About The Pull Request

Books now lie flat instead of looking slightly closed like before. They also look better and have more depth. Male and female gargoyle target dolls have been re-shaded somewhat. Angel holding the glass heart on the hud has been re-shaded and now has more depth than before. Priest's golden stole has been edited slightly.

## Why It's Good For The Game

Aesthetics.

### CODE REVIEW

**Comment by Takyon69** [comment]
image

New books

**Comment by Takyon69** [comment]
image

Re-shaded gargoyles.

**Comment by Takyon69** [comment]
image

Updated hud element

**Comment by Takyon69** [comment]
image

Updated hud element.

**Comment by Takyon69** [comment]
image

Before

**Comment by Real-MAGNUM** [comment]
Looks badass. Merged.

**Pull request merged**
