### PR TITLE
Adds walls to the town and two gate houses for the town guards

### PR DESCRIPTION
**Pull request by zakanater19**
## About The Pull Request

Adds a wall around the town with two gatehouses for the town guards, also adds a few iron bars in the north west of the town to stop people just going around by climbing in the water, this map PR will work with or without the sewer PR merged, it's all tested and the gates work for the correct gate

## Why It's Good For The Game

A few people were talking about the town having a wall and the town guard feeling outgunned, this will ensure they can keep control over the town proper

South gate

West gate
2 - Copy
Birds eye view of the wall
2 - Copy (2)

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
The amount of people condemned to stand at a gate has now increased by _two_. Consider removing the northwest gate, and making the wall protect the farm by going south along the sewer moat. Also, the wall can be bypassed by climbing into the sewer from the outside, and coming up from the inside, no?

**Comment by zakanater19** [comment]
> The amount of people condemned to stand at a gate has now increased by _two_. Consider removing the northwest gate, and making the wall protect the farm by going south along the sewer moat. Also, the wall can be bypassed by climbing into the sewer from the outside, and coming up from the inside, no? Fixable by putting some iron bars down.

yeah i didn't include a screenshot but there are iron bars to prevent going around the gates, but if the sewer PR gets merged there will be multiple ways into the town from the moat

**Comment by zakanater19** [comment]
and yeah ill work on that now and update it

**Comment by JTGSZ** [comment]
conflicts

**Comment by zakanater19** [comment]
> conflicts

ok going to close this and start with the new map on the other one

**Comment by Real-MAGNUM** [comment]
make sure you're running mapmerger2 in the tools folder. Read the readme if you dont know how.

**Comment by OrbitalParadise** [comment]
you mistake the way this PR works, there are 3 Gatekeepers now not 2

**Comment by OrbitalParadise** [comment]
one south, one left, one castle

**Pull request closed without merging**
