### PR TITLE
PQ tweaks, raise king much higher, lower some other roles

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

Lord 
* Changed to from 2 to 5. 
* Basically the whole game revolves around the King and he has to be experienced. Why was this so low? Also, we already have a system where people can be King with less PQ so it's fine if this is high.

Lady 
* Changed to 3 to 2.
* they dont do much unless theres court drama i guess but they should still be a 

Knight
* Changed 3 to 4
* hes supposed to be really strong warrior directly under the king

Gatemaster
* Changed from 3 to 4 
* he can kill people instantly

Bailiff, Bogmaster, and Sheriff
* All changed from 5 to 4
* They're leader roles but they still shouldn't be over the King.

Councillor
* Changed from 4 to 2
* They're just guards that follow the bailiff (unless theres some reason this should be super high idk why it was)

Archivist
* Changed to 0
* hes literally just a librarian

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
testmerging

**Comment by BigBigga** [comment]
can you please raise the knight's dude. like holy shit please. 4 at least.

**Comment by Real-MAGNUM** [comment]
Raise knight to 4, then fullmerged.

**Comment by JTGSZ** [comment]
Yeah, you need to talk to mister chungus about all of this.

**Comment by Real-MAGNUM** [comment]
merging for now due to a long testmerge. mr chungus can pr his changes.

**Pull request merged**
