### PR TITLE
fem hair additions single braid & kepthair (polite)

### PR DESCRIPTION
**Pull request by Viviridia**
New hairs for female Humans, Dwarves, Aasimars, Helf
## About The Pull Request

-adds single braid
Screenshot 2024-06-02 200324
Screenshot 2024-06-02 192953
Screenshot 2024-06-02 200524

-adds polite hair
Screenshot 2024-06-02 212146
Screenshot 2024-06-02 212102
## Why It's Good For The Game
ehhh I like braids

### CODE REVIEW

**Comment by assortedbeads** [comment]
Can you add shorter hair for elfs/delfs/women as well

**Comment by Viviridia** [comment]
> Can you add shorter hair for elfs/delfs/women as well

I can try

**Comment by Takyon69** [comment]
Looks decent 👍

**Review by Takyon69 — APPROVED** [review]

**Comment by ophaq** [comment]
Would be awesome if we could just take a majority of TG/Monkestation's hairstyles and put them here if they are fitting.

**Pull request merged**
