### PR TITLE
TG Rebase 

### PR DESCRIPTION
**Pull request by Xander3359**
Rebase to TG. Likely gonna take forever to get it compilable.

### CODE REVIEW

**Comment by JTGSZ** [comment]
Well, good luck

**Comment by SELFHELL** [comment]
Bless your autism

**Comment by ChungusGamer666** [comment]
I'm sorry what

**Comment by Henri9576** [comment]
man has officially gone insane

**Comment by hollyhocc** [comment]
why

**Comment by Kush1Push1** [comment]
This branch has conflicts

**Comment by Wirpy** [comment]
deletes the codefbase and replaces it with GAYT

**Comment by BlueMemesauce** [comment]
At https://github.com/BlueMemesauce/BLACKSTONE/tree/tgstation-update I deleted most of the files we don't actually need

**Comment by BlueMemesauce** [comment]
Basically we just wanna delete all the files that add random shit and only keep the files that update the vital systems

**Comment by BlueMemesauce** [comment]
anyway this i figured out is not the way to do it, even if you try to go through and delete the files you dont need theres like thousands of files of ss13 things added
it will be much better to just go through and update the systems we need

**Comment by CVSthePharmacy** [comment]
> deletes the codefbase and replaces it with GAYT

ban this guy

**Comment by BigBigga** [comment]
GYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT

**Comment by CVSthePharmacy** [comment]
why'd this get closed

**Comment by BlueMemesauce** [comment]
because he literally just copy pasted the tg station code and made no effort

**Pull request closed without merging**
