### PR TITLE
Goblin Kingdom!

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Adds Goblin Kingdom to the BOG, located underground. WIP
Goblin Kingdom was made based on Arx Fatalis Goblin Kingdom.
It has kitchen, gate, throne room, room for King, garrison, treasury, armory, "toilet".

## Why It's Good For The Game
GOBOS are awensome! More stuff in BOG make it more interesting. Gobos being a "neutral" (gobo players decide what to do) playable faction will improve RP.

### CODE REVIEW

**Comment by panvxv** [comment]
As what is needed:
Gobo playable race
"Spawners" inside of the kingdom (where players spawn)

**Comment by Real-MAGNUM** [comment]
Allow goblins to wear talkstones on their neck in this PR, please. I dont care about sprite placement, just the flags to allow it to be wearable.

**Comment by panvxv** [comment]
obraz

**Comment by panvxv** [comment]
obraz

**Comment by Real-MAGNUM** [comment]
Those are the wrong gems.

Their weapons are too advanced. Make them shitty so they have to steal/make more.

What keys are those?

**Comment by assortedbeads** [comment]
> Those are the wrong gems.
> 
> Their weapons are too advanced. Make them shitty so they have to steal/make more.
> 
> What keys are those?
> 
> 

Do they have any skills to support making or stealing weapons? Because Im not sure base goblins do

**Comment by Real-MAGNUM** [comment]
> Do they have any skills to support making or stealing weapons? Because Im not sure base goblins do

Base goblins have to skills, but they will when I add them as playable.

**Comment by panvxv** [comment]
> Those are the wrong gems.
> 
> Their weapons are too advanced. Make them shitty so they have to steal/make more.
> 
> What keys are those?

gems are fine
they have good but still crude weapons I could give them, they need some power to protect themself.
Spear, goedendag, daggers, axes (not battleaxe), I think are fine.

**Comment by Real-MAGNUM** [comment]
Testmerging, but the gemmies need replacing.

**Comment by Real-MAGNUM** [comment]
nvm I'll just merge and do it myself.

**Pull request merged**
