### PR TITLE
Medicine skill for more roles

### PR DESCRIPTION
**Pull request by panvxv**
## About The Pull Request
Adding medicine for those those who work with sharp objects and in dangerous environment.

## Why It's Good For The Game
Makes stitching wounds easier from the start of the round.

### CODE REVIEW

**Comment by Diegoflores31** [comment]
Giving medicine skill to pretty much everyone is insane powercreep . How the hell someone doesnt even know to read just attended his first aid courses

**Comment by Wintermote** [comment]
>gives medicine to every role
>but not the clerics who heal people

**Comment by Diegoflores31** [comment]
> I definitely agree we need some higher medicine skill for a few roles but man I would have done a completely different spread, like probably just church functionaries - acolytes, priest, and clerics.

Do they really need medicine considering they can heal to 100% with just miracles ?

**Comment by ChungusGamer666** [comment]
this pr is all kinds of wack

**Comment by panvxv** [comment]
> this pr is all kinds of wack

What should I change?

**Comment by panvxv** [comment]
> gives medicine to every role but not clerics (???)
> 
> I definitely agree we need some higher medicine skill for a few roles but man I would have done a completely different spread, like probably just church functionaries - acolytes, priest, and clerics.

Forgor, it is added to cleric, paladin and dwarf warrior

**Comment by panvxv** [comment]
As asked, removed skill from guards, knights, lady. Masons, farmers and all adv/pilgrims (except rogues) have weak weak skill medicine.

**Comment by Wintermote** [comment]
> > I definitely agree we need some higher medicine skill for a few roles but man I would have done a completely different spread, like probably just church functionaries - acolytes, priest, and clerics.
> 
> Do they really need medicine considering they can heal to 100% with just miracles ?

Yes, because I'm 99% certain cleric healing is going to be nerfed at some point, and I'd rather not be functionally useless as a cleric in the church healing people when that happens. This was a good opportunity to head that off ahead of time.

**Pull request merged**
