### PR TITLE
Vampire Lord Buff

### LINKED ISSUE #379: Vampire Ancient ceremonial armor no sprite
What it says on the tin, Ancient ceremonial armor that vampyre lord spawns with has no sprite, Apparently the sprite DOES exist in the code it just needs to have _F or _M on the end of it.

### PR DESCRIPTION
**Pull request by Osmos123**
## About The Pull Request
Vampire antagonists are laughable, whenever I hear about them I can rest easy knowing they do jack shit. The vampire lord has been specifically buffed so they are now a god among men (makes sense they are ancient and have centuries of practice). The land must now organize together to stop this. I honestly never seen a vampire lord use or reach their tiered abilities to their full potential.

## Why It's Good For The Game
Adds drama and more story telling to the game.

Fixes #379

### CODE REVIEW

**Comment by DirtTastesBad** [comment]
Vamp lord probably could use a buff, but might be better to wait for like... a wiki page on it to be made first, cause the main problem I see is that people have 0 idea as to what the fuck they're doing. When someone who knows how it works shows up, vamp lord seems to be a lot more of a threat

**Comment by Osmos123** [comment]
> Vamp lord probably could use a buff, but might be better to wait for like... a wiki page on it to be made first, cause the main problem I see is that people have 0 idea as to what the fuck they're doing. When someone who knows how it works shows up, vamp lord seems to be a lot more of a threat

At the moment, without admin intervention (the spawning of multiple deathknights) vamps don't have much. The vamplord current sword skill is skilled, they will lose 1v1 fight against most guards and adventurers. But yes I agree with you that most people (including me) don't know the full potential of their abilities. This change can be a temporary one and dialed back when people get familiarized with vamp lord. As when vamp antagonist pops up in the match its usually wasted.

**Comment by NGGJamie** [comment]
I'm willing to give this a shot and run it. It only makes sense that killing what is basically Dracula should be hard.

Will TM it and see how it goes.

**Comment by NGGJamie** [comment]
Had a staff member test it this round as a spawned Vamp Lord, gonna say this is too broken in current implementation.

**Comment by Osmos123** [comment]
> Had a staff member test it this round as a spawned Vamp Lord, gonna say this is too broken in current implementation.

Good to know, adjusted the stats equal to of a knight and also gave their unique armor set (I know the vlord sword spawns in the closet, but I dont see them with the armor anywhere).

image

**Comment by NGGJamie** [comment]
That sounds more reasonable. The staff member that tested it was able to clock everyone in the face with his fists and drain them effortlessly.

I'll aim to TM it later today when more people are awake in case things don't go well, but it should be fine.

**Comment by CVSthePharmacy** [comment]
> That sounds more reasonable. The staff member that tested it was able to clock everyone in the face with his fists and drain them effortlessly.
> 
> I'll aim to TM it later today when more people are awake in case things don't go well, but it should be fine.

that's literally just average skill level with fists, it's insanely easy, rng shouldn't be taken into account for this

**Comment by CVSthePharmacy** [comment]
but yeah this seems cool

**Comment by NGGJamie** [comment]
Will be active as a TM next round.

**Comment by K4rlox** [comment]
sprites of the ceremonial armor is invisible

**Comment by Osmos123** [comment]
These ceremonial armor pieces refuse to appear for onmobsprites, i will continue to play with it and see if i can make it work.

**Comment by Osmos123** [comment]
image

I've got it to work, the side views are cursed though. I will see if i can fix that up.

**Comment by Osmos123** [comment]
Its done, uploading the files
image

**Comment by Osmos123** [comment]
The sprites are now added in and ready for a TM again.

**Comment by NGGJamie** [comment]
Been seeing reports that vamp lords are still too strong, and they're getting a lot of successes. I'm beginning to think we might want to revert their stats entirely but keep the other changes here.

**Comment by CVSthePharmacy** [comment]
remove the do not merge and just let it merge

**Comment by Osmos123** [comment]
Reupdated the armor.dmi and head.dmi to include the new necra robes and hood from recent pr. Vamp stats have been restored back to original except the slight increase in sword skill and intelligence.

**Pull request closed without merging**
