### PR TITLE
adds custom locks

### PR DESCRIPTION
**Pull request by lovegreenstuff**
## About The Pull Request

see title
you make locks and keys from iron bars, 5 per
you hit them with a hammer to set their ids, right click with a hammer to finish them
after you finish a lock, you can hit it with a hammer again to set a name to change your locked thing to
or hit a finished key with a hammer to change its name

you can right click between locks and keys to sync onto each other, which also works for pre-existing keys
this will definitely not have unforeseen consequences

## Why It's Good For The Game

because it's funny
also fixes a bug where you couldn't hit chests and lockers because roguetown coders lmao

https://github.com/Blackstone-SS13/BLACKSTONE/assets/59631103/1c8f008a-3dd1-4253-ad06-1e808f8d75fb

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
not a combat nor balance pr, just normal qol, speedmerge this

**Comment by Real-MAGNUM** [comment]
NEED this

Testmerging

**Comment by efzapa** [comment]
dorf fort stealth buff

i approve :)

**Comment by TheManWithNoHands** [comment]
Oh so this was one of the things your working on. Based.

**Comment by lovegreenstuff** [comment]
don't merge this yet there's still a few things i need to fix

**Comment by Real-MAGNUM** [comment]
> don't merge this yet there's still a few things i need to fix

Holding off.

**Comment by dunsel-hordon** [comment]
Can you put locks on levers?

**Comment by lovegreenstuff** [comment]
no idea why you'd need to lock a lever but you'd normally just lock the room its in right?

**Comment by dunsel-hordon** [comment]
> no idea why you'd need to lock a lever but you'd normally just lock the room its in right?
> 
> anyways i don't plan to make more changes to this so it should be mergable

you would lock a lever if you want a stronger door but a way in and out without someone on the other side working it

**Pull request merged**
