### PR TITLE
Surgery tools for church

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request

adds 2 surgery backpacks to the church racks.
removes surgery backpack from churchling

## Why It's Good For The Game

headdev request
image

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
im so lazy

**Comment by wow50000** [comment]
peak

**Comment by CVSthePharmacy** [comment]
this reeks

**Comment by ophaq** [comment]
I tested this locally and they don't spawn. Weird huh?

**Comment by pilotmans** [comment]
Shitcode, i mean it doesn't spawn in the backpacks most of the time, i only saw it spawn the bags in for one round, perhaps another pr is conflicting with it?

**Comment by CVSthePharmacy** [comment]
> Shitcode, i mean it doesn't spawn in the backpacks most of the time, i only saw it spawn the bags in for one round, perhaps another pr is conflicting with it?

I hope so, they're fucking church folk, not surgeons

**Pull request merged**
