### PR TITLE
One Line Change!

### PR DESCRIPTION
**Pull request by Stagrawl**
technically two lines.

Drow Dagger > Dark Elf Dagger

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
theyre actually called nite elves according to the loremen

**Comment by Wintermote** [comment]
Having to try and force your lore through string replacements ought to be telling you something

**Comment by Stagrawl** [comment]
yes, i am forcing my lore on you, that is what is happening. definitely.

**Comment by SELFHELL** [comment]
Tbh just remove it. Unused anyways

**Pull request merged**
