### PR TITLE
Raises the PQ required for important roles 

### PR DESCRIPTION
**Pull request by Wirpy**
## About The Pull Request

Raises PQ limit for many important jobs such as King, all types of guards, priest etc. 

None of the numbers are set in stone, I've based it off the PQ current players I know that do good roleplay have but still within the range of it being fairly fast to attain if you are good at roleplay lol. (PQ Isn't really hard to get I'd argue) 

## Why It's Good For The Game

Hopefully less shitters in roles of prominence, makes PQ removal by admins a more effective punishment as the bar for important roles is higher. 
Allegedly less guard RDM tickets for admins to deal with
funny 
Hopefully creates a better RP enviroment

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
LOL peak

**Comment by wgtjunior743** [comment]
Rising PQ is good but some PQs req are so high, on low pop or mid pop we won't literally have some roles because people can't roll them, anything above 15 PQ i would argue it is too much, this also will take a toll on the number of players who won't be able to play the role they enjoy and flood pilgrims/adventures/towners to do their own thing or roll high acolyte to revive/cure rot for PQ

**Comment by pismorizzo** [comment]
I think you are way underestimating how hard it is to get pq as a new playe, even moreso if they cant play any roles at all. It took me 2 months to get to 20 pq and that was TRYING for weeks to get it up. Having admin friends or being a well known player really makes it seem like PQ is easy to get when you get commended 1-2 per round without doing anything. 

Adventurer at 6 PQ means the most popular new player role is now 100% blocked off for atleast 3-4 rounds for what reason? Its already been nerfed pretty hard and isnt a great fragger role so I cant see the logic.
Bog Guard is not popular as is, seeing 1 or 2  queue for it at round start it doesnt make sense to block off at the same as adventurer is.
Many issues like this at 15+ PQ which is just a potentially absurd time sink for someone to play something as simple as Bog Master.

**Comment by BlueMemesauce** [comment]
yea this is pretty insanely high
how many players even have 10 pq? theres gonna be like no guard force

image

**Comment by efzapa** [comment]
I'm gonna put my two cents in but
this just feels like PQ inflation

you're inflating the pq requirements without actually giving people more ways to legitimately earn PQ

this basically forces new people into the loop of playing adventurer (which is not for everyone), towner, beggar, or one of the other shitter roles until you can finally make it to something where you can make an impact on the round

**Comment by wgtjunior743** [comment]
Game would turn into PQ farm, people would not play for fun or what they want, they would play for PQ, get possible reviveable bodies and bury them for PQ, let people rot and become zombies for rot cure, beg for commendation ingame or in OOC, get their friends to PQ them and many other ways, i know that we got alot of shitters but every healthy game/community will have them, when you block people of playing the roles like that, you block shitters and possible great new members of the community that don't have the time or want to get 15 or 10 pq to a role they want.

**Comment by Wirpy** [comment]
> I'm gonna put my two cents in but this just feels like PQ inflation
> 
> you're inflating the pq requirements without actually giving people more ways to legitimately earn PQ
> 
> this basically forces new people into the loop of playing adventurer (which is not for everyone), towner, beggar, or one of the other shitter roles until you can finally make it to something where you can make an impact on the round

I don't code so if you want more ways to earn PQ it's wyci moment unforunately. 

Adventurer, towner, beggar, pilgrim etc all can have a substanial impact on rounds. Beyond that with a very low PQ bar you can still play fairly prominent things at court such as Queen, Prince and counciller. All three of those in the right player hand's can be fairly impactful on rounds. 

> Game would turn into PQ farm, people would not play for fun or what they want, they would play for PQ, get possible reviveable bodies and bury them for PQ, let people rot and become zombies for rot cure, beg for commendation ingame or in OOC, get their friends to PQ them and many other ways, i know that we got alot of shitters but every healthy game/community will have them, when you block people of playing the roles like that, you block shitters and possible great new members of the community that don't have the time or want to get 15 or 10 pq to a role they want. I would say if you double the current requeriments that would be decent.

Getting 10-15 PQ isn't really time-consuming or hard. it's a pretty low bar tbh. I reached around 10 PQ within my first few hours of playing. (like 1-3 days of gaming). If people turn to PQ farming, that's on them lol. Who's to say you can not have fun with any of the other roles?





> yea this is pretty insanely high how many players even have 10 pq? theres gonna be like no guard force
> 
> image

What? 10pq is so low lol. It'd be great to find out the average PQ but I dont have the means of getting that but like come on. 10 PQ isn't really all that much. 

> I think you are way underestimating how hard it is to get pq as a new playe, even moreso if they cant play any roles at all. It took me 2 months to get to 20 pq and that was TRYING for weeks to get it up. Having admin friends or being a well known player really makes it seem like PQ is easy to get when you get commended 1-2 per round without doing anything.
> 
> Adventurer at 6 PQ means the most popular new player role is now 100% blocked off for atleast 3-4 rounds for what reason? Its already been nerfed pretty hard and isnt a great fragger role so I cant see the logic. Bog Guard is not popular as is, seeing 1 or 2 queue for it at round start it doesnt make sense to block off at the same as adventurer is. Many issues like this at 15+ PQ which is just a potentially absurd time sink for someone to play something as simple as Bog Master.

Maybe I am underesmating it, maybe I'm not. If I took you 2 months to get 20pq I'd argue that maybe you don't play interesting enough characters / provide a service to people. Like if you become a blacksmith and setup shop you can essentially farm PQ usually cause it's an extremely valued service that is often underfufilled. Who doesn't love waiting in the smith queue am I right?

I raised adventurer PQ cause there's less slots now (40) and it's a bit more interesting to have something to look forward to (luv me grind) 


> Rising PQ is good but some PQs req are so high, on low pop or mid pop we won't literally have some roles because people can't roll them, anything above 15 PQ i would argue it is too much, this also will take a toll on the number of players who won't be able to play the role they enjoy and flood pilgrims/adventures/towners to do their own thing or roll high acolyte to revive/cure rot for PQ

Numbers will most likely be adjusted. TM was interesting.

**Comment by Wintermote** [comment]
Pretty predictable - as the PQ of early players continues to climb the PQ required to play anything climbs with them.

Doesn't solve any problems that weren't already solved by the PQ we had to start with, just more grind for new players, and reduces them to some of the most boring roles nobody wants to play for potentially weeks. 

What's the playtime average, how many rounds do most players have, how quickly do average players earn PQ, how many PQ do they get per round? These are questions that should be answered before you start inflating PQ.

I think this will help kill momentum for anyone playing on the server at all; if I'm an average player and I join a server and I'm faced with earning 10 PQ just to play a security guard and after an entire weekend of playing I've got 1 PQ, I am just going to quit and find somewhere else to play, I'm not grinding that shit for 10 weeks.

**Comment by wgtjunior743** [comment]
> Pretty predictable - as the PQ of early players continues to climb the PQ required to play anything climbs with them.
> 
> Doesn't solve any problems that weren't already solved by the PQ we had to start with, just more grind for new players, and reduces them to some of the most boring roles nobody wants to play for potentially weeks.
> 
> What's the playtime average, how many rounds do most players have, how quickly do average players earn PQ, how many PQ do they get per round? These are questions that should be answered before you start inflating PQ.
> 
> I think this will help kill momentum for anyone playing on the server at all; if I'm an average player and I join a server and I'm faced with earning 10 PQ just to play a security guard and after an entire weekend of playing (so potentially 5 rounds, maybe) I've got 1 PQ, I am just going to quit and find somewhere else to play, I'm not grinding that shit for 10 weeks.
> 
> Also, people being shitty and bad at their jobs makes the game FUN

PQ is a decent mechanic but these reqs are so stupid, PQ gain is different for each person, the commendation i get are just for when i do funny shit sometimes because even i play roles like weaponsmith, merchant, armorer, steward, blacksmith, miner,mason i swear 99% they don't translate to PQ, since sometimes people don't care enough to give you a commendation for doing your job, you really need to stand out and sometimes you just want to do your shit and not care to stand out for some funny number.
PQ req in general kills abit of the game momentum but these being too high will literally get the same people to play the same role for multiple times because there won't be enough people with PQ high enough.

**Comment by wgtjunior743** [comment]
> > I'm gonna put my two cents in but this just feels like PQ inflation
> > you're inflating the pq requirements without actually giving people more ways to legitimately earn PQ
> > this basically forces new people into the loop of playing adventurer (which is not for everyone), towner, beggar, or one of the other shitter roles until you can finally make it to something where you can make an impact on the round
> 
> I don't code so if you want more ways to earn PQ it's wyci moment unforunately.
> 
> Adventurer, towner, beggar, pilgrim etc all can have a substanial impact on rounds. Beyond that with a very low PQ bar you can still play fairly prominent things at court such as Queen, Prince and counciller. All three of those in the right player hand's can be fairly impactful on rounds.
> 
> > Game would turn into PQ farm, people would not play for fun or what they want, they would play for PQ, get possible reviveable bodies and bury them for PQ, let people rot and become zombies for rot cure, beg for commendation ingame or in OOC, get their friends to PQ them and many other ways, i know that we got alot of shitters but every healthy game/community will have them, when you block people of playing the roles like that, you block shitters and possible great new members of the community that don't have the time or want to get 15 or 10 pq to a role they want. I would say if you double the current requeriments that would be decent.
> 
> Getting 10-15 PQ isn't really time-consuming or hard. it's a pretty low bar tbh. I reached around 10 PQ within my first few hours of playing. (like 1-3 days of gaming). If people turn to PQ farming, that's on them lol. Who's to say you can not have fun with any of the other roles?
> 
> > yea this is pretty insanely high how many players even have 10 pq? theres gonna be like no guard force
> > image
> 
> What? 10pq is so low lol. It'd be great to find out the average PQ but I dont have the means of getting that but like come on. 10 PQ isn't really all that much.
> 
> > I think you are way underestimating how hard it is to get pq as a new playe, even moreso if they cant play any roles at all. It took me 2 months to get to 20 pq and that was TRYING for weeks to get it up. Having admin friends or being a well known player really makes it seem like PQ is easy to get when you get commended 1-2 per round without doing anything.
> > Adventurer at 6 PQ means the most popular new player role is now 100% blocked off for atleast 3-4 rounds for what reason? Its already been nerfed pretty hard and isnt a great fragger role so I cant see the logic. Bog Guard is not popular as is, seeing 1 or 2 queue for it at round start it doesnt make sense to block off at the same as adventurer is. Many issues like this at 15+ PQ which is just a potentially absurd time sink for someone to play something as simple as Bog Master.
> 
> Maybe I am underesmating it, maybe I'm not. If I took you 2 months to get 20pq I'd argue that maybe you don't play interesting enough characters / provide a service to people. Like if you become a blacksmith and setup shop you can essentially farm PQ usually cause it's an extremely valued service that is often underfufilled. Who doesn't love waiting in the smith queue am I right?
> 
> I raised adventurer PQ cause there's less slots now (40) and it's a bit more interesting to have something to look forward to (luv me grind)
> 
> > Rising PQ is good but some PQs req are so high, on low pop or mid pop we won't literally have some roles because people can't roll them, anything above 15 PQ i would argue it is too much, this also will take a toll on the number of players who won't be able to play the role they enjoy and flood pilgrims/adventures/towners to do their own thing or roll high acolyte to revive/cure rot for PQ
> 
> Numbers will most likely be adjusted. TM was interesting.

That is your experience, sadly there are me and many others that played helpful roles , and did not gain 10 PQ that fast, i personally played many minor roles, helping people with mason, weaponsmith, armorer, merchant, steward, and i got 10 PQ in what, 1 to 2 week of playing and after that i just fucked off and started having fun and not playing roles that get me a higher chance of getting PQ, after 1month of playing i got 17.85 of PQ, getting 10 PQ is not fast and easy or low bar as you said, 30 PQ is insanely high and i bet a new player won't be able to get 10 PQ or 20 that fast nor 30.

**Comment by Gyrandola** [comment]
I agree with the spirit of the PR but it is a bandaid fix to a much deeper problem, which is a never ending PQ inflation. Sure, you might remove a couple of shitters from playing guard but what will the experience of brand new players be? hours and hours of PQ grind.

**Comment by Coastfront** [comment]
What is just should never hold a hammer; For it sees only nails where are there thumbs.

By doing this: You still stop shitter players.
By doing this: You will stop considerably more actual new players.

In my eyes, & in what should be any reasonable mans eyes; Punishing the innocent is never worth it in the pursuit of justice, or security.

I guarantee you that for every 1 shitter you got to stop trying, you likely pushed away 2-3 new players who didn't want to spend weeks looking for PQ.

This is a system, where literally nothing is guaranteed. Sure, you "might:" get a commendation from literally everyone in a round, 5 people, or no one.
You can even be memorable, & at times people could just miss doing it, or arbitrarily not have the energy for it.
Using code to enforce administrative & inter-personal issues is, and always will be: Extremely fucking stupid.
Every server that continually uses its codebase as a hammer to arbitrarily lock people out of things either becomes shit, is generally disliked, or experienced a massive drop in player-count over what it could've otherwise had with better administration.

This is a bad change, is a bad idea, and is an even worse pattern of thought.
PQ Requirements are fine on their own, & maybe only a handful should be raised by 1-2 points, not to fucking 10-15.

**Comment by efzapa** [comment]
> > I'm gonna put my two cents in but this just feels like PQ inflation
> > 
> > you're inflating the pq requirements without actually giving people more ways to legitimately earn PQ
> > 
> > this basically forces new people into the loop of playing adventurer (which is not for everyone), towner, beggar, or one of the other shitter roles until you can finally make it to something where you can make an impact on the round
> 
> I don't code so if you want more ways to earn PQ it's wyci moment unforunately. 
> 
> Adventurer, towner, beggar, pilgrim etc all can have a substanial impact on rounds. Beyond that with a very low PQ bar you can still play fairly prominent things at court such as Queen, Prince and counciller. All three of those in the right player hand's can be fairly impactful on rounds. 

So basically "make people grind PQ for a week playing the shit jobs until they can actually do anything substantial"

might I add half of those roles are RDMd or fragged by people just because, beggar/orphan/advent being good examples

**Comment by Wesreidau** [comment]
You know, if you're a new player and you haven't been here for a week, maybe you shouldn't be taking a round-critical role.
If your ability to roleplay isn't good enough to get commends, maybe you shouldn't be writing the laws.

As it stands you can grind PQ by standing on the bog bridge RDMing everyone who walks past and stuffing their own money in their mouth when they die. If you have a metabuddy on voice chat, you can both swap commends.

Maybe if you think 'grinding PQ' isn't fun you should get rid of that blatant rules loophole so people can't grind it and have to roleplay.

**Comment by Coastfront** [comment]
> You know, if you're a new player and you haven't been here for a week, maybe you shouldn't be taking a round-critical role. If your ability to roleplay isn't good enough to get commends, maybe you shouldn't be writing the laws.
> 
> As it stands you can grind PQ by standing on the bog bridge RDMing everyone who walks past and stuffing their own money in their mouth when they die. If you have a metabuddy on voice chat, you can both swap commends.
> 
> Maybe if you think 'grinding PQ' isn't fun you should get rid of that blatant rules loophole so people can't grind it and have to roleplay.

You're right, newer players should be locked out of even ADVENTURER until they have SIX PQ for their insolence, because this game is so INCREDIBLY complicated that they shouldn't even THINK about being allowed to touch anything more important than random town roles.


How dare they even GLANCE at town guard for a second?
I would not describe, many of the roles having their PQ as "incredibly important" beyond having 'slightly more power than normal'.

If this exists to punish shitters: They'll do exactly what you described, & get a friend to spam commend eachother for 10 rounds, reach guard roles & go back to griefing with them. Quite literally nothing changes for them.

If this exists to punish new players for existing Sure, it does that. But lets not pretend that anyone familiar with ss13 would need more than maybe 2 days at most to figure out roughly the layout of the town, roughly what the bad people look like, and by extension; Roughly how town guard is played.

On king: Sure, raising the PQ higher can be argued that its an important role.
Guard captain, knights, the priest, etc: Similar logic.

Raising nearly every guard to 10 minimum, adventurer & bog guard to 6, and then saying "Play town", only means that those roles will have less people in them, be more of a metaclique than normal security roles can become on ss13, & as you described: Quite literally will just not stop anyone who wasn't already going to break the rules to get what they want.
Not getting PQ commendations can happen for a wide array of reasons.
New player got unlucky & just up and died repeatedly.
New player played one of the roles that can amount to "item vending machine" & just mostly saw people who wanted items vended.
New player did something memorable with someone, & was later outshined in the same round in that persons eyes by someone else, who's more experienced.
Or, new player who didn't know how to try and make something interesting happen, just didn't have any interesting events happening around them.
If a blacksmith is roleplaying fairly well & being personable, even if they're doing fine: By virtue of just nothing of intrigue happening around them they're unlikely to be commended.

Next to the issue this PR aims to solve of shitter players taking high-value roles to be assholes: They will launch the game, see that this change went through, and have either already been playing long enough to have the PQ requirement, or they call a metabuddy, & farm 15 PQ & go back to being assholes.
Newer players have less tenacity than people being assholes to get to vital roles, because people being assholes want to keep being assholes. New players want to find out if they actually like the game.

**Comment by efzapa** [comment]
> You know, if you're a new player and you haven't been here for a week, maybe you shouldn't be taking a round-critical role.
> If your ability to roleplay isn't good enough to get commends, maybe you shouldn't be writing the laws.
> 
> As it stands you can grind PQ by standing on the bog bridge RDMing everyone who walks past and stuffing their own money in their mouth when they die. If you have a metabuddy on voice chat, you can both swap commends.
> 
> Maybe if you think 'grinding PQ' isn't fun you should get rid of that blatant rules loophole so people can't grind it and have to roleplay.

consecutive comms don't work btw

**Comment by BlueMemesauce** [comment]
> > You know, if you're a new player and you haven't been here for a week, maybe you shouldn't be taking a round-critical role.
> > If your ability to roleplay isn't good enough to get commends, maybe you shouldn't be writing the laws.
> > As it stands you can grind PQ by standing on the bog bridge RDMing everyone who walks past and stuffing their own money in their mouth when they die. If you have a metabuddy on voice chat, you can both swap commends.
> > Maybe if you think 'grinding PQ' isn't fun you should get rid of that blatant rules loophole so people can't grind it and have to roleplay.
> 
> consecutive comms don't work btw

Cheaters could maybe make multiple accounts, commend someone super quick then leave the server

**Comment by efzapa** [comment]
> 
> > > You know, if you're a new player and you haven't been here for a week, maybe you shouldn't be taking a round-critical role.
> > > If your ability to roleplay isn't good enough to get commends, maybe you shouldn't be writing the laws.
> > > As it stands you can grind PQ by standing on the bog bridge RDMing everyone who walks past and stuffing their own money in their mouth when they die. If you have a metabuddy on voice chat, you can both swap commends.
> > > Maybe if you think 'grinding PQ' isn't fun you should get rid of that blatant rules loophole so people can't grind it and have to roleplay.
> > 
> > consecutive comms don't work btw
> 
> Cheaters could maybe make multiple accounts, commend someone super quick then leave the server. Although this is kind of my fault for adding midround commends.
> 

alot of work for one PQ per alt account

**Comment by Coastfront** [comment]
> > > > You know, if you're a new player and you haven't been here for a week, maybe you shouldn't be taking a round-critical role.
> > > > If your ability to roleplay isn't good enough to get commends, maybe you shouldn't be writing the laws.
> > > > As it stands you can grind PQ by standing on the bog bridge RDMing everyone who walks past and stuffing their own money in their mouth when they die. If you have a metabuddy on voice chat, you can both swap commends.
> > > > Maybe if you think 'grinding PQ' isn't fun you should get rid of that blatant rules loophole so people can't grind it and have to roleplay.
> > > 
> > > 
> > > consecutive comms don't work btw
> > 
> > 
> > Cheaters could maybe make multiple accounts, commend someone super quick then leave the server. Although this is kind of my fault for adding midround commends.
> 
> alot of work for one PQ per alt account

Make 2 alts
Immediately donate PQ to shitter friend No.1
Rotate to shitter friend No.2
Rotate however many shitters until you're back at 1.

People who are proclaimed "shitters" hold kinship; Ants stay in their line, as do people.
If this change goes through; The people who this is meant to address will literally just circle-jerk commend eachother, or most likely already have fairly high PQ from this already happening.

**Comment by CVSthePharmacy** [comment]
make priest 20

**Comment by ChungusGamer666** [comment]
excessive

**Pull request closed without merging**
