### PR TITLE
Towner Role Update

### PR DESCRIPTION
**Pull request by Stagrawl**
Drunkard should actually be forced to Eora, Minstrel has the updated skillset rather than the old one.

### CODE REVIEW

**Comment by WindowTalents** [comment]
No, let drunkard also have Xylix - or he's valid to every inquis lol

Kinda important to let... me able to lie a bit as a role I can be examined as.

**Comment by Stagrawl** [comment]
Eh, you know what, sure.

**Comment by WindowTalents** [comment]
Yeh, do not get me wrong buddy - I am going to use that role WITH Eora 100% of the time...

BUT, it is fun to lie about patrons and hang out in the Church, honestly haha

**Comment by WindowTalents** [comment]
Nice, but... wtf does trait_generic do lol?

I can't find any define info for it, if that's what I need to throw on my role to fix it - pls let me know haha

**Comment by Stagrawl** [comment]
> Nice, but... wtf does trait_generic do lol?
> 
> I can't find any define info for it, if that's what I need to throw on my role to fix it - pls let me know haha

It’s just a source for a trait I’m using. I’ll see if I can work out why your role isn’t working at some point. Ping me on discord if I don’t get around to it soon.

@Sembia

**Comment by WindowTalents** [comment]
> Ping me on discord if I don’t get around to it soon.

I am not on discord, you can reach me here lol.
I just can't figure out why this won't appear in the list like everything else - nothing should be wrong. Hopefully this time, it works.

**Pull request merged**
