### PR TITLE
Siege gamemode marauders, should be ready to merge

### PR DESCRIPTION
**Pull request by zakanater19**
So it compiles.. but on the local host i can't get the gamemode to run LOL, i am a big retard, but i hope someone who isn't a big retard can fix this shit, or ignore this, or close this, whatever, i tried, and now i will leave this big dump here for you to look at

### CODE REVIEW

**Review by zakanater19 — COMMENTED** [review]
bruh why does this cause it not to compile

**Comment by Osmos123** [comment]
image

I think you will need to add the new file directs in the roguetown.dme file.

image

Sorta like how I had to include the new file of the class .dm.

**Comment by zakanater19** [comment]
Thanks, that should do it, i still can't get the gamemode to fire when forcing it locally... maybe it's because just one person is connected idk

**Comment by zakanater19** [comment]
maybe have a test merge see if it works

**Comment by Osmos123** [comment]
I've got a suggestion, maybe turn these ones loadout into horse archers similar to nomadic people. I know the tiefling vaquero adventurer loadout starts with a horse and could borrow those files to update this.

**Comment by zakanater19** [comment]
Sure, my hope is once the basic siege mode is actually in people will make it better

**Comment by zakanater19** [comment]
i'm stressing thinking about if bandits (minor antag) and marauders (major antag) spawn in the same round, they will probably kill eachother, maybe have the game admins enforce they are of the same band if that happens? i did not think this through

**Comment by bobjension** [comment]
bandits and marauders getting ready to kill each other for the right to loot and burn the city first

**Comment by NGGJamie** [comment]
Added to TM.

**Pull request closed without merging**
