### PR TITLE
Removes free respawns via prayer

### PR DESCRIPTION
**Pull request by Real-MAGNUM**
## About The Pull Request

Removes the free respawn toll coins you get by praying to your patron while in the underworld.

## Why It's Good For The Game

This shit bypasses the underworld for like no reason. Bad for player quality when you can do anything you want, get killed, and instantly respawn.

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Tested. No longer spawns a coin in your hand.

**Comment by CVSthePharmacy** [comment]
ok but what if someone prays for you

**Comment by BlueMemesauce** [comment]
why add the other code in there if it does nothing

**Comment by BlueMemesauce** [comment]
I dont think this did anything since you cant pray in the underworld

**Comment by CVSthePharmacy** [comment]
re-add free tolls

**Pull request merged**
