### PR TITLE
[REWORK] Werewolves comeback. PART 1

### PR DESCRIPTION
**Pull request by Gyrandola**
sittingwolfcontemplating

<h3>Fixes</h3>

- No longer retain/get insane wounds when transforming/untransforming,
- No longer have blank names or even worse a giant ass "WEREWOLF" as name.

<h3>QoL</h3>

- Howling reworked to be a spell. Cooldown 1 MINUTE to avoid spamming shit in peoples ears.
- Clearer and more Immersive transformation process that allows user to not get constantly caught with their pants down.

<h3>Balance</h3>

- Werewolves are now significantly tougher to fight and can EASILY chop through your armor like butter.
- The transformation process takes longer, which puts the werewolf into a vulnerable state.

<h3>Features</h3>

- New HUD icon #1078 
- New Combat music courtesy of Abraxas #1081 
- Feeding mechanic. Biting and chewing non rotten, non vampire corpses/people will slowly restore your health.
- Infection mechanic is now delayed and COMPLETELY silent. You will not know if you are infected until almost a minute after being bitten and it will be too late.
- Ability to extend/retract their claws at will, which are their only weapon and can easily cut through anything.
- Ability to jump up and down 1 zlevel. This means they can jump down a cliff or climb a building extremely fast.

<h3>Technical details</h3>

- Added NOFALLDAMAGE trait ~~and NOEMBED trait~~ if you want to use them I guess.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
furry fetish content

**Comment by Stagrawl** [comment]
yeah, so get merging.

**Comment by CVSthePharmacy** [comment]
close this pr

**Comment by TheManWithNoHands** [comment]
Do they get stronger for every vampire they maim?

**Comment by CVSthePharmacy** [comment]
furry content, delete this pr

**Comment by Takyon69** [comment]
Post the werewolf sprite.

**Comment by Gyrandola** [comment]
> Post the werewolf sprite.

OG one
image

image

**Comment by CVSthePharmacy** [comment]
I don't like this pr

**Comment by CVSthePharmacy** [comment]
ok now I think they're too op now even more than before

**Comment by CVSthePharmacy** [comment]
delete werewolves

**Pull request merged**
