### PR TITLE
removes recently added Lifeweb sprites

### PR DESCRIPTION
**Pull request by Cdey78**
Title. Too many to summarize.
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Gyrandola** [comment]
But why

**Comment by bobjension** [comment]
we already have sprite style differences, we don't need more of them and some of this stuff we got already in our "styles", and some of this stuff was already in roguetown

**Comment by Gyrandola** [comment]
Time to close this

**Comment by CVSthePharmacy** [comment]
holy shit what did they do to the cat

**Comment by Takyon69** [comment]
Thank you, Lord Squirrel.

**Pull request merged**
