### PR TITLE
Let dark elf be towner

### PR DESCRIPTION
**Pull request by BlueMemesauce**
## About The Pull Request

Lets dark elf be towner

## Why It's Good For The Game

well they were originally meant to be restricted to beggar and gravedigger but then we added them to butcher, cook, barkeep, mason, merchant, smith so I don't see why they could be all of those and not be towner

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
done without maint approval but i like it so

racism v4 in the future maybe? idk

**Comment by BlueMemesauce** [comment]
"done without maint approval"
well either way your gonna merge it or close it lol 
asking for approval only makes sense if its like a change that takes more than 10 seconds to make

**Comment by dunsel-hordon** [comment]
remove this bullshit they already get darkvision which is bullshit as everyone else is blind. PUT EM BACK IN THE FUCKING WOODS AND CAVES!

**Comment by CVSthePharmacy** [comment]
> remove this bullshit they already get darkvision which is bullshit as everyone else is blind. PUT EM BACK IN THE FUCKING WOODS AND CAVES!

can we just remove dark elves?

**Pull request merged**
