### PR TITLE
New spell for Necra worshipers, necrotic grasp

### PR DESCRIPTION
**Pull request by YuiY1997**
## About The Pull Request

Necra gamers now get a touch spell that inflicts brute and toxin damage as well as lowering body temperature

## Why It's Good For The Game

I know this is currently inaccessible in game, but I am trying to add more spell variety to certain roles so that clerics and acolytes aren't so same-y. Currently necra clerics/acolytes get no combat spells, so this adds one.

### CODE REVIEW

**Comment by Gyrandola** [comment]
all necra worshippers get that? sounds kinda broken

**Comment by TheManWithNoHands** [comment]
Necra worshippers do get a combat spell. They can insta kill any undead. And no range requirment besides sigth on that one.(i think)
So i would at least make it rather weak, if its the second combat spell they get. Like the first lv Astrata spell, "sun cleanse".

But if thats too weak for you then, maybe add even some ligth stun as utility to help tweak it. Often a theme with ghost/undead stuff that their ghosty fear powers make people freeze in shock. Idunno, just some braingoop for you.

**Comment by YuiY1997** [comment]
> all necra worshippers get that? sounds kinda broken

literally nobody gets this at the moment. I was planning on only giving it to acolytes.

I think instead of making new spells for every, individual God I'm going to do something similar to the "Domain" system from DnD and group Gods thematically and make spells that reflect one or two gods thematically.

I could give this to necra and pestra clerics/acolytes/paladins/priests or just some of those roles

**Comment by ChungusGamer666** [comment]
I'm not keen on merging PRs that are only admin content. Also, provide proof of testing.

**Pull request closed without merging**
