### PR TITLE
Revert baliffnerd

### PR DESCRIPTION
**Pull request by bobjension**
snowflake role and his goons GTFO

### CODE REVIEW

**Comment by Real-MAGNUM** [comment]
Bad PR format, looks like a kneejerk. Please at least try to explain your reasoning if/when you reopen, this isn't very constructive. Discussing with maintainers, or the original PR creator might help.

Also missing the map changes to fully remove added content.

**Comment by bobjension** [comment]
ironic

**Comment by bobjension** [comment]
holy shit I glanced at the fucking stats for the new roles

WHY DOES COUNCILLER GET 5 IN WRESTLING AND 2 IN FORTUNE?

**Comment by Real-MAGNUM** [comment]
As I originally stated, reformat your pr to explain removals and modifications please.

**Pull request closed without merging**
